---
title: "応募について"
date-modified: today
format: 
  html: 
    number-sections: true
toc: true
---

# 応募案内 {.unnumbered}

宋ゼミへ応募するためには以下の4点を**<u>すべて</u>**満たす必要があります。

1. 予め**「[**宋ゼミについて**](index.qmd)」ページ**を読む
1. **個別オフィス・アワーへ参加**する（合同オフィス・アワーではありません）
1. **LMSで応募書類を提出**する（全ゼミ共通）
1. **専用フォームで課題を提出**する

# オフィスアワー

本ゼミのオフィスアワーは**予約制**です。

<center>
<a href="https://www.jaysong.net/garage/2025/OH/reservation.html" class="btn btn-info btn-lg" target="_blank" role="button"><i class="bi bi-calendar-check"></i>&nbsp;&nbsp;&nbsp;オフィスアワーの予約</a>
</center>

- **場所：**宋の個人研究室（TA227）
   - A棟の2階にあります。
   - 参加者の数に応じて、ゼミ教室（TK108）へ変更される場合があります。変更が生じる場合は、予約時、登録したメールへお知らせします。
- **予約方法：**画面上段の[専用フォーム](https://www.jaysong.net/garage/2025/OH/reservation.html){target="_blank"}でご予約ください。
   - オフィスアワーには参加したいが、<u>希望する時間帯が掲載されていない場合</u>はメールでお問い合わせください（<song@kansai-u.ac.jp>）。適宜、枠を追加するか個別に対応します。
   - <u>メールでの予約受け付けも可能</u>です。希望する日付・時間帯を下記のリストから選び、メールでお知らせください。
- **注意事項** 
   - **1時間前までに予約者がゼロの場合**、当該時間帯のオフィス・アワーは開催されません。「行くかどうか迷っている」、「行けたらいく」の場合でもとりあえず予約をしてください。予約はいつでもキャンセル可能です。
   - 希望者の数に応じてオフィスアワーの枠が増える可能性があります（減ることはございません）。最新情報は本ページに掲載します。
   - 第1次募集時のオフィスアワーに参加された方は、第2次募集のオフィスアワーへの参加は不要です。

# 応募書類（LMS提出）

1. **【志望理由】**志望理由（500字以上）
   - **本ゼミに応募する理由、きっかけ、抱負など**を自由に書いてください。
      - とりあえず、本ゼミの説明をご覧になることを推奨します（やや長めです...）。
   - 志望理由に模範解答やテンプレなどは存在しません。ネットで検索すると志望理由書のテンプレ、雛形が見られますが、こちらは使わず、自分の考えを述べてください。
   - **生成型AIの使用もやめてください。**これくらいは自分の言葉で書いてください。ゼミ紹介のページをAIに読ませて志望理由を書かせた「量産型」志望理由が最近目立ちます。定員以内の第1希望であればやむを得ず受け入れることにはなりますが、印象が非常に悪くなりますし、宋の信頼を失うことになります。多分卒業されるまで宋に疑われ続けるでしょう。
2. **【課題等】**ここは空欄で結構です。応募者への課題については以下を参照してください。

# 課題（WEB提出）

- 以下のページから、応募者への課題を提出してください（**PC環境推奨**）。
   - 期限：**2025年10月17日（金）23時59分〆**
   
<center><a href="https://kandaisojo.qualtrics.com/jfe/form/SV_cuokni4Rt6DXVNI" class="btn btn-danger btn-lg" target="_blank" role="button"><i class="bi bi-journal-check"></i>&nbsp;&nbsp;&nbsp;課題提出</a></center><br/>

- 事前に以下の内容をメモ等で用意しておくとスムーズに提出できます。
   1. これまで最も熱心に取り組んだ授業の科目名（3〜5つ）
   1. あなたにとって興味のあるテーマと「問い」。問いの中には必ず「原因」、または「結果」を含むこと。両方あれば更に良い。（「XはYを引き起こすか」、「Yの原因はXか」、「Yの原因は何か」、「Xは何をもたらすか」、「なぜYが起こったのか」など）
   1. その問いに注目するようになったきっかけと（2）その問いに対する答えが得られた場合のメリット（合計300字以上）
- 複数回提出した場合、最後のものを提出物として認めます。