---
title: "よくある質問"
engine: knitr
---

```{css}
/*| echo: false */
.qa-1 {
    max-width: 700px;
    margin-bottom: 7px;
    border: 1px solid #d6dde3;
    border-radius: 5px;
}

.qa-1 summary {
    display: flex;
    justify-content: space-between;
    align-items: center;
    position: relative;
    padding: 1em 2em 1em 3em;
    color: #333333;
    font-weight: 600;
    cursor: pointer;
}

.qa-1 summary::before,
.qa-1 p::before {
    position: absolute;
    left: 1em;
    font-weight: 600;
    font-size: 1.3em;
}

.qa-1 summary::before {
    color: #75bbff;
    content: "Q";
}

.qa-1 summary::after {
    transform: translateY(-25%) rotate(45deg);
    width: 7px;
    height: 7px;
    margin-left: 10px;
    border-bottom: 3px solid #333333b3;
    border-right: 3px solid #333333b3;
    content: '';
    transition: transform .5s;
}

.qa-1[open] summary::after {
    transform: rotate(225deg);
}

.qa-1 p {
    position: relative;
    transform: translateY(-10px);
    opacity: 0;
    margin: 0;
    padding: .3em 3em 1.5em;
    color: #333;
    transition: transform .5s, opacity .5s;
    text-align: justify;
}

.qa-1[open] p {
    transform: none;
    opacity: 1;
}

.qa-1 p::before {
    color: #ff8d8d;
    line-height: 1.2;
    content: "A";
}
```

<details class="qa-1">
<summary>卒論のテーマは必ずゼミ応募時の研究テーマに合わせないといけませんか。</summary>
<p>
アコーディオンとして開閉できるQ&Aです。コンパクトに見せることができるので、質問の数が多い場合などにおすすめです。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>R言語やデータ分析に関する知識が皆無ですが、大丈夫ですか。</summary>
<p>
そもそも総情においてR言語の授業は3回生以上の授業であるため、R言語に関する知識は求めておりません。データ分析の知識については、もちろん「統計学」や「データリテラシー実習」、「データ分析実習」などの授業で基礎知識を習得したことに越したことはありませんが、やる気次第では3回生からでも十分身に付けられます。また、後述のように、本ゼミが求めているデータ分析のスキルのハードルは決して高くありません。 
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>宋ゼミで使うR言語というのはどんなものですか。食べ物ですか。</summary>
<p>
R言語はC言語やPython、JavaScriptのようなプログラミング言語です。性質としてはPythonのようなインタープリター言語、かつ動的言語です。ただし、Rは統計やデータ分析、データ加工、可視化に特化した言語です。むろん、プログラミング言語である以上、ゲームとかアプリも作れますが既存の言語よりも生産性が低いです。つまり、データ分析に特化したプログラミング言語だと思ってください。今のデータサイエンスの世界はRとPythonが主流であり、プロの世界では二刀流が多いです。宋もメインがR、サブがPythonです。C、Java、Pythonのような汎用言語よりも使い道が限られているので、これらの言語よりは難易度が低めです。ただし、他の言語ではあまり使わないデータ加工と可視化に関する機能が豊富です。残念ながら食べられません。 
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>データ分析ってどんな感じでしょうか。</summary>
<p>
大事なのは問いに対する答えを印象とか直感でなく、エビデンス（データ、観察）から導出することです。データ分析とはデータの使い方に過ぎません。平均値を計算して棒グラフに並べることも基礎的な手法ではありますが、データ分析とも言えます。本ゼミでは高度の手法を使って卒業論文を執筆された方もいますが、平均値の比較やクロス表だけで執筆する方も多いです。とりあえず、卒業論文に回帰分析を使うところを目指して頂きますが、自分が設定した問い、背景知識などに応じて柔軟に対応・指導します。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>文系でも大丈夫ですか。</summary>
<p>
宋ゼミのデータ分析には文系と理系の区分はございません。そもそも宋も法学部出身で、大学院も法学研究科です。総情に在籍している皆さん以上に生粋の文系だったわけです。たしかにデータ分析の中には微分とか積分とか最適化とかなんかよく分からん数式が登場する世界もあります。データ分析が研究の「対象」であればそうなりがちです。しかし、宋ゼミのデータ分析は研究の「対象」でなく、研究の「手法」に過ぎません。どういった分析をするかが決まったら、あとはパソコンに任せるべきです。分析に限って言えば、数行のコードで分析は終わります。もちろん、データ分析は簡単というわけではありませんが、それは新しく学習するものに共通することです。何かを新しく習得するためにはそれなりの時間と労力が必要でしょう。ただ、データ分析を「使う」ことに限定すると文系でも理系でもスタートラインはほぼ同じだと思って良いかと思います。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>部活をやっていますが、大丈夫ですか。</summary>
<p>
問題ありません。これまで体育会に所属したゼミ生も数人おり、無事卒業しました。ただし、部活・大会等による欠席に対する配慮はございません。欠席で遅れた分は自分で補うようにしてください。部活を選んだのも本人ですから「部活で忙しくて...」という言い訳は受け付けません。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>週1のゼミ以外のゼミ（= サブゼミ）はありますか。</summary>
<p>
時間割に掲載されている週1のゼミ以外のゼミはございません。ただし、3回生の場合、宋が担当する実習科目（3回生以上対象）の履修を強く推奨しています。後期の最後のゼミ（1月中旬頃）の代わりに、宋ゼミ内部の研究成果発表会を梅田キャンパスで行います。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>ゼミ外活動はありますか。</summary>
<p>
年3〜4回の懇親会、年1回のBBQ大会があります。ゼミ旅行、ゼミ合宿、他大学・他学部との合同ゼミは希望者がそれなりにいて、幹事役を引き受けてくださる方がいれば開催します。これらのゼミ外活動の参加は義務でなく、100%自由です。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>先輩たちの進路が知りたいです。</summary>
<p>
[ゼミ生の進路](course.qmd){target="_blank"}をご確認ください。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>取っておいた方が良い科目はありますか。</summary>
<p>
総情のすべての科目は何らかの形で皆さんに役立ちますので、答えは「すべての科目」ですが、1・2回生が履修できる授業の中で、宋ゼミの内容と密接な関連があるといえば「統計」、「データ」、「調査」という単語が含まれた科目すべてです。ただし、これらの授業の事前履修が必須というわけではありません。取っておけば、ゼミの内容がよりスムーズに理解できる程度のものであり、履修していなくても問題ありません。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>選考基準を教えてください。GPAは重要ですか。</summary>
<p>
志望理由、応募者への課題、GPAなど様々な要素を総合的に見て判断するため、「これが重要」といったものはございません。ただし、宋ゼミは多様性を重視しており、性別、国籍、関心分野、GPAの偏りをなるべく減らす方向で先行しております。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>男女比を教えてください。</summary>
<p>
理想としては半々ですが、総情の男女比を考えると少なくとも2:1から1:1の間を目指しております。これまでの宋ゼミには45人在籍しており（2025年10月現在）、男性29、女性16で総情の男女比よりもやや1:1に近いです。
</p>
</details>

<!--/* 区切り */-->

<details class="qa-1">
<summary>これまでの倍率が知りたいです。</summary>
<p>
[これまでの倍率](competition.qmd){target="_blank"}をご確認ください。
</p>
</details>



<!---
<details class="qa-1">
<summary>

</summary>
<p>

</p>
</details>
--->