---
title: "ゼミ紹介"
date-modified: today
format: 
  html: 
    number-sections: true
    toc: true
engine: knitr
---

```{css}
/*| echo: false */
.qa-1 {
    max-width: 950px;
    margin-bottom: 7px;
    border: 1px solid #d6dde3;
    border-radius: 5px;
}

.qa-1 summary {
    display: flex;
    justify-content: space-between;
    align-items: center;
    position: relative;
    padding: 1em 2em 1em 3em;
    color: #333333;
    font-weight: 600;
    cursor: pointer;
}

.qa-1 summary::before,
.qa-1 p::before {
    position: absolute;
    left: 1em;
    font-weight: 600;
    font-size: 1.3em;
}

.qa-1 summary::before {
    color: #75bbff;
    content: "✓";
}

.qa-1 summary::after {
    transform: translateY(-25%) rotate(45deg);
    width: 7px;
    height: 7px;
    margin-left: 10px;
    border-bottom: 3px solid #333333b3;
    border-right: 3px solid #333333b3;
    content: '';
    transition: transform .5s;
}

.qa-1[open] summary::after {
    transform: rotate(225deg);
}

section > p {
    text-align: justify;
}

.qa-1 p {
    position: relative;
    margin: 0;
    padding: .3em 3em 1.5em;
    color: #333;
    text-align: justify;
}

.mobile-only {
    display: none;
}

@media (max-width: 1024px) {
    .mobile-only {
        display: inline;
    }
}
```

<span class="mobile-only">※ スマホの場合、画面上段の <i class="bi bi-layout-text-sidebar-reverse"></i> アイコンをタップするとメニューが開きます。</span>

<br/>

<center>
[<i class="bi bi-mortarboard"></i> ゼミ紹介](index.qmd){class="btn btn-outline-primary" role="button"} [<i class="bi bi-person-add"></i> 応募について](entry.qmd){class="btn btn-outline-info" role="button"} [<i class="bi bi-patch-question"></i> よくある質問](faq.qmd){class="btn btn-outline-success" role="button"} [<i class="bi bi-instagram"></i> Instagram](https://www.instagram.com/song_officehour/){class="btn btn-outline-danger" role="button" target="_blank"}

<span style="font-size:0.75em;">※ Instagramがゼミ生が運営しており、宋は関与しておりません。現役ゼミ生に質問のある方はDM送ってみてください。</spa>
</center>

# 宋ゼミについて

　宋ゼミの目標は**社会に存在する様々な問いを印象や直感でなく、根拠（エビデンス、データ）を用いて答えるための考え方とスキルを身に付ける**ことです。ここで言っている「社会」というのは社会学という学問分野を指しているわけではありません。社会、経済、政治、マーケティング、文化、メディア、サブカルチャー、音楽、スポーツなど、これらをすべて含みます。「一つのゼミでこれらが全部できるか？」と疑問を持つ方もいるかも知れません。しかし、それが出来てしまう（？）のが宋ゼミです。[【ここ】](research.qmd)から宋ゼミの卒論、グループ研究の成果を確認してみればすぐに分かると思います。

　世の中には因果関係に関する様々な問いがあります。「[**お菓子の包装**]{style="color:firebrick;"}を変えれば、[**売上**]{style="color:royalblue;"}は上がるか」、「[**投票啓発活動**]{style="color:firebrick;"}は、[**投票率**]{style="color:royalblue;"}を上がるか」、「[**年齢**]{style="color:firebrick;"}が上がると、[**e-Sportsのパフォーマンス**]{style="color:royalblue;"}は下がるか」はいずれも[**因**]{style="color:firebrick;"}[**果**]{style="color:royalblue;"}関係に関する問いです。そもそも我々の人生におけるあらゆる選択、意思決定は因果関係の産物です。我々は常に「この行動はどの結果をもたらすか」を意識しながら生きています。企業もそうです。「この商品/広告を出せば会社の売上はどうなるか」を常に意識しているわけです。つまり、**私たちは誰一人例外なく、毎日因果推論をしています**。そして私たちは「多分、〜〜になるだろう」という直感や印象で選択肢を選ぶことが多いですし、実は多くの場面においてこっちの方が効率的です。しかし、重要な選択の分かれ道に立たせられた時、直感や印象だけで意思決定をことはあまりにも危険です。やはり、「多分」でなく、「Xをすれば、Yになる」という確証が欲しいでしょうね。因果推論とはこの確証を得るための考え方と手法の総称であり、2年間の宋ゼミで是非身につけて頂きたいスキルでもあります。

　以下は宋ゼミのゼミ生がこれまで行ってきた研究を少しアレンジしたものです。興味のある内容を読んでみてください。

<details class="qa-1">
<summary>宣伝方法と集客効果</summary>
<p>
　かつて弓道部所属のゼミ生がいました。彼は弓道部の部員がだんだん減っていくことを知り、弓道の魅力を広げて部員を増やしたいと思いました。彼は[数年前に弓道を主題としたアニメ](https://tsurune.com/tv/)を思い出しました。バスケットボール（スラムダンク）やテニス（~~テニヌ~~テニスの王子様）、バレーボール（ハイキュー！！）もアニメ・漫画の恩恵を受けていたと思っていた彼は、このアニメを宣伝に使えば良いのではないかと思いました。たとえば、来年度の4月1日の入学式にそのキャラクターを活用した宣伝で部員を集めてみるとします。その結果実際に入部希望者が前年よりも10名が増えたとします。この10名増はアニメを使った宣伝の効果でしょうか。答えは「わからない」です。もし、その年の部活の勧誘担当者が超イケメンだったり、美人だったり、面白い人だった可能性もあります。あるいは某有名人が弓道を嗜んでいる記事とかがあって、全国的な弓道ブームが起き、他の高校・大学の弓道部の入部希望者も同程度増えていた可能性もあります。
</p>

<p>
　ではどうすれば、この宣伝の効果が分かるでしょうか。答えは宋ゼミで確認してください。
</p>
</details>

<details class="qa-1">
<summary>子どもが増えると幸福度は上がるか</summary>
<p>
　これまで子どものいるゼミ生はいませんでしたが、なぜかグループ研究で提案されたテーマです。育児は大変とも言われていますが、でも子どものいる家庭を見ると幸せそうに見えます。子どもが幸福をもたらすのであれば、子どもが増えると幸福度はもっと上がるでしょうか。たとえば、全国世論調査を使って、子どもが0人の家族の幸福度の平均値が3.93点、1人のそれが4.02点、2人のそれが4.06点...だったことが分かりました（幸福度は1点から5点までの範囲で測定しています）。これを見ると子どもの数が増えると幸福度は右上がりで上がることが分かりますが、これは本当でしょうか。ここでの疑問は2つあります。（1）子どもが0人から2人へ増えることで幸福度が0.13点上がりましたが、これは誤差の範囲内、つまり偶然の結果じゃないでしょうか、そして（2）これは本当に因果関係ですか？とのことです。幸せだから子どもを2人産んだ可能性もありますね。つまり、因果は因果でも、逆の因果の可能性があるとのことです。逆の因果関係の可能性以外にも、経済力という第三の要因が子どもの数と幸福度両方に影響を与えている可能性もあります。
</p>

<p>
　ではどうすれば、子どもの数が幸福度に与える効果が分かるでしょうか。答えは宋ゼミで確認してください。
</p>
</details>

<details class="qa-1">
<summary>K-POPアルバムの販売形態の多様化は売上に貢献するか</summary>
<p>
　音楽のアルバムって普通CDで販売されています。しかし、CD以外の形態もあります。DVDやBlu-rayもありますが、CD以外の代表的な媒体といえば「レコード盤」とも呼ばれるLP盤でしょう。LP盤再生に必要なレコードプレイヤーを持っている人は少ないでしょうが、コレクト目的で買う人も多いようです。つまり、CDだけでなく、LP盤でも発売すれば、ファンの人がCDとLP盤両方を購入し、売上が上がるとも期待できます。K-POP業界ではCDとLP盤以外にも様々な販売形態があります。NEMO、SMC、Weverse、KIT、META、POCAなど様々です。販売形態を多様化すれば売上は上がるでしょうか。この問いに答えるために、これまでのK-POPアルバムの販売形態と売上に関するデータを集めて分析をしました。たとえば、販売形態が1つ増えると、アルバムの販売枚数が平均3万枚増えるという結果が得られたとします。ならば「販売形態が1つ増やすと、アルバムが3万枚さらに売れる」という結論を出しても良いでしょうか。もちろん、答えは「わかりません」です。販売形態を増やすということは資金面で苦しい中小規模の事務所では非現実的な話かも知れません。一方、SM、JYP、YG、HYBEのような大手事務所であれば、そこまで難しい話でもないでしょう。この現実を考えると、「販売形態が多いほど、販売枚数が増える」ということは実は販売形態でなく、事務所のパワーが原因である可能性があります。大手事務所の方が広告に使えるリソースが大きく、そもそも認知度も高いでしょう。そして、こういう事務所は金銭的にも余裕があるので様々な媒体でアルバムを販売することができるかも知れません。販売形態の多様さと販売枚数の関係を明らかにするためには、この可能性を遮断する必要があります。
</p>

<p>
　ではどうすれば、販売形態の多様さと販売枚数の関係が分かるでしょうか。答えは宋ゼミで確認してください。
</p>
</details>

# ゼミの活動

## 3回生（専門演習）

　総合情報学部における**ゼミの（形式上の）最終目標は卒業論文**、または卒業作品となります。これがないと卒業できません。あなたが「株式会社　キュウヨ・メッチャ・タカクテ・ホワイト・キギョウ」に内定をもらったとしても、卒論がないと卒業ができないわけです。しかし、いきなり卒論を書いてくださいと言われてもどこから始めればいいのか、全く分からないでしょう。実際、ゼミに入ってすぐ、みなさんに「卒論を書き始めましょう」なんかは言いません。まずは**3回生が履修する「専門演習」で卒業論文執筆のための基礎体力とスキルを習得**します。そこで必要な知識・経験とは（1）リサーチデザイン、（2）分析手法の習得、（3）簡単な研究の遂行経験です。

<details class="qa-1">
<summary>リサーチデザインについて</summary>
<p>
　リサーチデザインとは、研究を成功させるための**研究計画全体の枠組み**のことです。具体的には、研究の目的を明確にし、それを達成するためにどのような手法（データ収集、データ分析など）をどのような順番で、どのように行うかを体系的に設計するプロセスです。たとえば、「投票に行きましょう！のような啓発活動は本当に投票率を上げるのか」という問いを設定したとしましょう。そこで啓発活動をしたA市の投票率が60%、しなかったB市の投票率が50%だったとします。ならば、啓発活動の効果は10%ポイントでしょうか。答えは「わからない」です。このA市とB市が適切な比較対象であれば、啓発活動の効果は10%pです。そうでなければ、10%pではない可能性が非常に高いです。リサーチデザインの中には様々な工程が含まれていますが、中でも最も**大事なのは「比較可能な対象を見つける or 作る」こと**です。これには<u>文系も理系も関係ありません</u>。
</p>
<p>
　リサーチデザインはどうすれば習得できるでしょうか。むろん、世の中にはリサーチデザインに関する教科書も多数ありますし、本ゼミでもこれらの教科書の輪読会を行います。しかし、最も良い方法は別にあります。それはたくさんの研究に触れることです。言い換えれば他人のリサーチデザインから学ぶということでしょう。大学の先生のような研究のプロたちも、この過程を通じてリサーチデザインを身に付けてきました。本ゼミでも一般向けの学術書ややさしめ論文の輪読を通じて、教科書で学んだリサーチデザインが実際にどう活用されているかを確認してきます。
</p>
</details>

<details class="qa-1">
<summary>分析手法を勉強する</summary>
<p>
　分析手法には**データ分析の知識**と、そのための**ツールの使い方**に関する知識が含まれます。「データ分析は難しい」と思うかも知れませんし、その理解は半分正解です。データ分析の手法は数百種類はあると思いますが、中には宋でも理解できないレベルの高度な手法も含まれます。一方、みなさんにとっての馴染みのある平均値や棒グラフも立派なデータ分析の手法です。ミャクミャクが印刷されたパッケージのお菓子の平均売上が3億円、そうでないお菓子の平均売上が2億円なら、ミャクミャクが売上にもたらす効果は1億円（=3億円-2億円）になります。どうですか？「しょぼい」、「たったそれだけ？」、「思ったのと違うなー」と思うかも知れませんが、実はマーケティングで幅広く使われているABテストによる因果効果の推定はこんな感じです。つまり、（宋を含む）プロの世界でも使われる手法です。むろん、平均値の単純比較から信頼できる因果効果を得るためにはリサーチデザインが重要です。つまり、大事なのは研究のデザインであって、どれだけ複雑そうにみえる「それっぽい」手法を使ったか二の次です。
</p>

<p>
　もちろん、宋ゼミには高度な手法を使った卒論を執筆された方もいますが、単純平均の比較だけで問いに対する答えを導出した卒論も少なくありません。大事なのは直感や印象でなく、根拠に基づくことです。その根拠は高度な手法じゃないと得られないケースもありますが、多くの場合、かなり簡単な手法で信頼できるエビデンスが得られます。
</p>
</details>

<details class="qa-1">
<summary>とりあえず「研究」を味わってみる</summary>
<p>
　4回生になると卒論を執筆しなければなりません。いきなり一人で卒論を書くことは心細いでしょう。したがって、まずはグループでやってみます。テーマも興味本位のもので構いません。この段階では、社会的な意義や学術的な意義は考えなくて結構です（もちろんあった方が良いです）。テーマの選定、問いの設定、問いに対する暫定的な答え（仮説）の導出、仮説を検証するために必要なデータの収集と分析、分析結果のまとめ、これらの作業を3〜4人のグループでやってみます。結果として予想に反する結果、あるいは時間不足で不完全燃焼で終わってしまうかも知れませんが、それでも構いません。卒論執筆の際、その経験を活かせるのであれば、十分意義のあるグループ研究だと言えるでしょう。
</p>
</details>

　以下は3回生ゼミ（専門演習）そ進め方についてです。

<details class="qa-1">
<summary>3回生ゼミ（専門演習）の進め方</summary>
<p>
　3回生の専門演習は大きく「輪読会」と、「実習」、「グループ研究」で構成されます。**春学期は輪読会と実習**がメインとなり、リサーチデザインや因果推論の考え方に関する一般・学部生向けの入門書をみんなで読みます。実習はRを使ったデータ分析の入門書を1冊選定し、みんなで手を動かしながらRを使ったデータ分析を体験して頂きます。**秋学期は輪読会とグループ研究**がメインです。まずは一般向けの学術書、そして少し難易度のある学術書を1冊ずつ選定し、春学期同様、輪読会を行います。輪読会が終わりましたら、3〜4人程度のグループを形成し、グループ研究をします。メンバー同士で話し合い、テーマを決め、みんなで力を合わせてデータを収集し、分析してみましょう。必要ならばいつでも宋を呼んでください。秋学期の最終盤にはゼミ内で研究成果発表会&打ち上げを開催します。
</p>
</details>

<details class="qa-1">
<summary>週1ゼミ以外の活動について</summary>
<p>
　また、ゼミ以外の活動として宋が担当する実習科目の履修を強く推奨しております。総情でR言語とR言語を使用したデータ分析が学習できる唯一の授業です。春・秋で計2コマです。春学期はR言語そのものがメイン、秋学期はR言語を使ったデータ分析の実装がメインです。
</p>
</details>

## 4回生（卒業研究）

　大学生活の最後の4回生のみなさんにはは2つの大きな試練（？）に立ち向かって頂きます。その2つの試練とは**進路**、そして**卒業論文**です。

<details class="qa-1">
<summary>進路について</summary>
<p>
　まず、進路ですが民間企業に就職を考えている場合は就職活動、公務員を目指している場合は公務員試験の準備、進学を考えている方が院試の勉強があります。多くの場合、民間企業への就職となりますが、この場合は4回生になった瞬間からスタートしますね（最近は、業界によっては3回生の秋から始まるところも多いです）。とりあえず、みなさんにはこちらに全力を注いで頂きます。
</p>
</details>

<details class="qa-1">
<summary>卒業論文について</summary>
<p>
　卒業論文は3回生の時に勉強した知識と技能、そしてグループ研究の経験を活かした、みなさんの4年間の**大学生活の集大成**とも言えます。卒論が完成した時の達成感はこれからの人生でもなかなか味わえないと思います。卒論執筆は上から言われたことをやれば完成するものでなく、みなさんが主体的に積み上げていくものです。その積み上げの過程を宋がサポートします。しかし、毎回10名強のゼミ生がゼミ室に集い、卒論執筆の進捗共有、相談をしたら一人あたりの時間は10分弱となります。したがって、**4回生のゼミは毎回2名ずつ参加して頂きます**（第1回と第15回は全員参加）。したがって、みなさんにとって、**1学期あたりのゼミの回数は4〜5回**程度です。**残りの時間は就活・勉強に注力しながら、マイペースで卒論を執筆**してください。もちろん、「毎週チェックを受けないと不安」という方もたまにいます。公式的なゼミは週1のゼミのみですが、希望すれば個別に相談に乗ることも可能です。実際、4回生になってから毎週のように私に相談にきて、夏休み頃には卒論を完成した例も数件あります。
</p>
</details>

　つまり、就活（or 進学準備、公務員試験準備）を最優先にしつつ、マイペースで卒論を執筆していただきます。4回生のゼミ（卒業研究）は1学期4〜5回程度です。卒論は基本一人で執筆しますが、宋が認めた場合、共著も可能です（要相談）。秋学期の最終盤にはゼミ内で研究成果発表会&打ち上げを開催します。

# 入ゼミまでのおすすめ

　宋ゼミの場合、3回生になるまでにやっておくべきことはございません。3回生になったら皆が同じスタートラインに立っていると仮定し、ゼミを進めていきます。しかし、さらに充実したゼミ生活を送るための準備をするという選択肢もありますし、非常に賢い選択です。3回生に上がる直前の春休みは、ある意味、人生最後の「平穏」な休みです。3回生の夏からはインターンシップとかありますし、意外とやることも多いですね。この春休みを無意味に過ごしても、3回生に上る前のリフレッシュの時間に使っても、大学では学べない何かを学ぶために使っても、それは100%皆さんの選択ですし、100%尊重します。しかし、「ゼミで何かを得たい」という方にはある程度の準備をしておくことをおすすめします。かなり長い内容となりますので、以下の内容をお読みください。

<center>
[<i class="bi bi-book"></i> 春休みの賢い過ごし方](preparation.qmd){class="btn btn-outline-primary" role="button"}
</center>

# 入ゼミ希望者への一言

　異世界から転生してきて人生2+回目に突入した方を除き、ゼミは初めてでしょう。具体的にどういう雰囲気なのかも分かりませんし、難しいことされるのではないかと心配されている方もいるかも知れません。配属が決まったら2年間異動もできませんし、指導教員と合わなかったらどうしよーという方もいるでしょうね。ゼミについては楽しみもあるでしょうが、その分だけの不安もあると思います。

　恥ずかしいことですが、実は私は大学生時代、ゼミに所属しておりませんでした。私がいた大学は卒論が必須でなく、そもそもゼミも任意でした。むろん、1学期のみのゼミ形式の少人数授業や履修者が私一人でなぜかゼミみたいになった授業は受けたことがありますが、2年間、特定の教員から指導されながら研究をしたことはありません。ゼミにも入っていなかったため、むろん卒論というものを書いたこともありません。今になっては後悔しています。その時にゼミ入っとけば良かったなー、自分が4年間頑張った（?）証を卒論という形で残しておけば良かったなーとですね（ゼミに落ちたのではなく、そもそも応募もしませんでした）。そして、総情に宋ゼミができたのも2022年度であり、宋ゼミはまだまだ発展途上で、試行錯誤を繰り返しながら運営しています。**教員を含め、みんながゼミ初心者**です。**初心者同士で話し合いながら、より楽しいゼミを作っていきましょう**。

　宋ゼミは「好奇心」と「やる気」のある方を歓迎します。好奇心ややる気は人によって、場面によって異なる意味を持つでしょう。宋ゼミでの好奇心とは「**あらゆることに対し、鵜呑せず「なぜ？」、「本当？」と疑う**こと」を意味しします。指導教員が言われたこと、マスコミで報道されたこと、本や論文に書かれたこと、すべてです。与えられたものに疑問を持つことで一歩先へ踏み出すことができます。続いて、やる気とは「**分からないことを分からない放置しない**こと」です。分からないことは分かるまで粘りましょう。分かるまで宋に聞いても良いでしょう。

　また、**やる時には頑張り、休む時には全力で休みましょう**。ON/OFFの切り替えは大事です。頑張り続けることは体力的にも精神的にもダメージが大きいです。人生最後の学生時代にみなさんのすべてを捧げる必要はありません。しかし、やる時にはしっかり頑張りましょう。いつONモードで、いつOFFモードに入るか、これを決めることもみなさんです。自主性と計画性が試されますが、ON/OFFを意識し、試行錯誤しながら感覚を掴めていきましょう。

　ゼミの紹介にも書いてありましたが、「宋ゼミでは何でもできる」ことはお分かり頂けかと思います。なら「第1希望は本当に行きたいゼミに応募して、そこがダメかったら第2希望として、自分がやりたいことのできる宋ゼミに入れる」という戦略を取ることも可能です。非常に賢い戦略ですが、多くの方から次善の策扱いされると少し悲しくなるので、あえてアピールさせてください。宋ゼミを第1希望と第2希望で悩んでいる方は以下の内容を読んでみてください。

<details class="qa-1">
<summary>宋ゼミは第2希望に最適なゼミ？</summary>
<p>
　まず、第2次募集、第3次募集まで行くと選択の余地がかなり狭くなるので、何でも屋が最大の売りの宋ゼミを第1希望として選ぶ方が多いです。逆に言えば、第1次募集では第2希望で入れる方が多いです。第1次募集において宋ゼミを第1希望で出す方は（1）興味関心が広すぎて絞れていない、（2）何がしたいのかがまだ曖昧、（3）政治学でデータ分析したい方、この3パターンが多いです。やりたい研究対象・テーマが明確な方であれば、それに特化したゼミを第1希望にするのは当然の流れですが、そういう方であっても宋ゼミのメリットはあります。一点目は**指導可能な手法の幅広さ**です。データの制約があるなら話は別ですが、データさえあれば、分析はできます。世の中には食材があっても適切な包丁がなくて、料理を諦めるケースも多いですが、宋ゼミでは、少なくとも食材に見合った包丁がなくて捌けないことはありません。二点目は**ゼミ構成員の多様さ**です。ゼミ生の興味関心の広さが宋ゼミの特徴の一つです。悪く言えばまとまりがないと思うかも知れませんが、様々な興味関心を持つ人に囲まれることは意外と貴重な経験です。三点目は**宋が政治学以外は門外漢**ということです。これはデータ分析以外の内容については干渉しないとのことです。好きなことを自由にやっていけるのも宋ゼミの特徴の一つです。
</p>
</details>


# 担当教員について

　名前は宋財泫（そん・じぇひょん）です。ソウル（韓国）生まれ・ソウル育ちで、高校を卒業し、2005年に来日しました。徴兵と1年間の語学留学の時期を除けばずっと日本で暮らしていたので、日本歴もそろそろ20年になります。大学では政治学を勉強し、大学院でも政治学で博士学位を取得しました。趣味はグルメとゲームです。麺類（とりわけラーメン）が好きですが、最近は少し控えております。ゲームはRPG類全般が好きで、3D酔いがひどいのでFPSは苦手です。

　私の専門は政治学であり、その中でも政治行動論と政治学方法論を専門としています。政治行動論は政治における様々な主体（有権者、市民、政治家、官僚、マスコミ、若者、ネット民など）の行動や意識を観察したり、因果関係を分析する学問ですが、私の主な観察対象は有権者です。この観察や分析を支えるのが政治学方法論です。観察には観察済み（=既に公開されている）のデータを使うこともあれば、自分の問いを検証するために世論調査などを通じて観察する場合もあります。要するに私の仕事は政治的現象をデータを用いて分析することです。

<details class="qa-1">
<summary>宋の職歴</summary>
- 2021年度〜：[関西大学](https://www.kansai-u.ac.jp/ja/?stt_lang=ja)[総合情報学部](https://www.kansai-u.ac.jp/Fc_inf/)　准教授
- 2020年度：[同志社大学](https://www.doshisha.ac.jp/)[文化情報学部](https://www.cis.doshisha.ac.jp/)　助教
- 2018〜2019年度：[早稲田大学](https://www.waseda.jp/top/)[高等研究所](https://www.waseda.jp/inst/wias/)　講師
- 2017年度：日本学術振興会特別研究員（DC2）
</details>

<details class="qa-1">
<summary>宋の学歴</summary>
- 2015〜2017年度：[神戸大学](https://www.kobe-u.ac.jp/ja/)[法学研究科](https://www.law.kobe-u.ac.jp/)　博士課程後期課程
   - 博士（政治学）
      - 博士論文：「争点空間の歪みと有権者の選択―伸縮近接性モデルによる争点投票理論の統合―」
- 2012〜2014年度：[神戸大学](https://www.kobe-u.ac.jp/ja/)[法学研究科](https://www.law.kobe-u.ac.jp/)　博士課程前期課程
   - 修士（政治学）
      - 修士論文：「韓国は地域主義を超えられるか―選挙公約の役割の実証分析―」
   - 2012年度：語学留学（アメリカ）
- 2006〜2011年度：[慶應義塾大学](https://www.keio.ac.jp/ja/)[法学部](https://www.law.keio.ac.jp/)政治学科
   - 学士（法学）
   - 2009〜2010年度：兵役による休学
- 2002〜2004年度：[東国大学校師範大学附属高等学校](https://ddbk.sen.hs.kr/)
</details>