---
title: "春休みの過ごし方"
date-modified: today
format: 
  html: 
    number-sections: true
    toc: true
engine: knitr
---

```{css}
/*| echo: false */
section > p {
    text-align: justify;
}
p {
    text-align: justify;
}
```

　厳密な意味で、**3回生になるまでにやっておくべきことは特にありません。**3回生になったら皆が同じスタートラインに立っていると仮定し、ゼミを進めていきます。しかし、さらに充実したゼミ生活を送るための準備をするという選択肢もありますし、非常に賢い選択です。ここではさらに充実したゼミ生活を送りたい方のために、3回生になる前の春休み（2〜3月）中に読んでおけば良い本をいくつか紹介します。2ヶ月間、のんびりしながらでも達成できそうな分量に構成しています。好きなコースをお選びください。1 $\rightarrow$ 2の順で読んでください（3もあれば1 $\rightarrow$ 2 $\rightarrow$ 3の順番）。

::: {.callout-important}
## ★の意味

　書誌情報の前に「★ 」が付いているものはR言語による実習が含まれています。読むだけでなく、自分のPCでやってみましょう。もし、パソコンでやる内容があるにも関わらず★が付いていないのであれば、そこは読み物として読んで頂いて結構です。R言語のインストールなどについては、いつでも宋にご相談ください。12月には新ゼミ生のグループLINEを作成するので、個別にLINEで聞いてくれてもOKです。
:::

## コース1：バランスコース

1. 浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社.（第1〜3章）
1. 以下のうち、1冊
   - 伊藤公一朗. 2017. 『データ分析の力』光文社新書.
   - 中室牧子・津川友介. 2017.『「原因と結果」の経済学―データから真実を見抜く思考法』ダイヤモンド社.
1. ★ 浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社.（第4〜章）

## コース2：リサーチデザイン

1. 浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社.（第1〜3章）
1. 伊藤修一郎. 『政策リサーチ入門 増補版: 仮説検証による問題解決の技法』東京大学出版会.
1. 久米郁男. 2013. 『原因を推論する』有斐閣.

## コース3：因果推論

1. 以下のうち、1冊
   - 伊藤公一朗. 2017. 『データ分析の力』光文社新書.
   - 中室牧子・津川友介. 2017.『「原因と結果」の経済学―データから真実を見抜く思考法』ダイヤモンド社.
1. 以下のうち、1冊
   - 松林哲也. 2022. 『政治学と因果推論』岩波書店.
   - Angrist, Joshua D., Jorn-steffen Pischke. 2014. *Mastering 'Metrics: The Path from Cause to Effect.* Princeton University Press.


## コース4：R言語 + データ分析

1. ★ エレーナ ローデ・今井耕介 (著), 原田勝孝 (訳). 2025 『新・社会科学のためのデータ分析入門 導入編』岩波書店.
1. 以下のうち、1冊
   - ★ 浅野正彦・矢内勇生. 2018. 『Rによる計量政治学』オーム社.
   - ★ 今井耕介 (著), 粕谷祐子・原田勝孝・久保浩樹 (訳). 2018. 『社会科学のためのデータ分析入門 (上/下)』岩波書店.
   - ★ Imai, Kosuke, and Nora Webb Williams. 2022. *Quantitative Social Science: An Introduction in tidyverse.* Princeton University Press.

## コース5：R言語

1. 以下のうち、1冊
   - ★ Hadley Wickham・Garrett Grolemund (著), 黒川利明 (訳). 2017『Rではじめるデータサイエンス』オライリージャパン.
   - ★ 松村優哉・湯谷啓明・紀ノ定保礼・前田和寛. 2021. 『RユーザのためのRStudio[実践]入門〜tidyverseによるモダンな分析フローの世界（改訂2版）』技術評論社.
1. ★ 宋財泫・矢内勇生『私たちのR: ベストプラクティスの探求』web-book.