---
title: "ゼミ生の研究"
toc: true
---

```{r}
#| include: false
pacman::p_load(tidyverse, gt)
df <- read_csv("_data/list.csv")
```

## 卒業研究（4回生）

```{r}
#| echo: false
df |> 
    filter(Type == 4 & !is.na(ID)) |> 
    arrange(desc(Year), ID) |> 
    mutate(File = if_else(!is.na(File), paste0("_abstract/", Year, "/", File, ".pdf"), NA)) |> 
    select(-Type, -ID) |> 
    mutate(Year = str_c(Year, "年度")) |> 
    group_by(Year) |> 
    gt() |> 
    fmt_url(columns = File, as_button = TRUE, label = "PDF") |> 
    fmt_markdown(columns = Title) |> 
    sub_missing(missing_text = "") |> 
    cols_label("Name"  = "氏名",
               "Title" = "題目",
               "File"  = "概要") |> 
    cols_align(columns = File, align = "center") |> 
    cols_width(Name  ~ px(150),
               File  ~ px(150))
```

## グループ研究（3回生）

```{r}
#| echo: false
df |> 
    filter(Type == 3 & !is.na(ID)) |> 
    arrange(desc(Year), ID) |> 
    mutate(File = if_else(!is.na(File), paste0("_abstract/", Year, "/", File, ".pdf"), NA)) |> 
    select(-Type, -ID) |> 
    mutate(Year = str_c(Year, "年度")) |> 
    group_by(Year) |> 
    gt() |> 
    fmt_url(columns = File, as_button = TRUE, label = "PDF") |> 
    fmt_markdown(columns = Title) |> 
    sub_missing(missing_text = "") |> 
    cols_label("Name"  = "氏名",
               "Title" = "題目",
               "File"  = "概要") |> 
    cols_align(columns = File, align = "center") |> 
    cols_width(Name  ~ px(150),
               File  ~ px(150))
```