project:
  type: website
  output-dir: docs

#language: _language.yml
lang: ja

website:
  site-url: "https://www.jaysong.net/"
  title: "Jaehyun Song, Ph.D."
  page-footer: "Copyright 2024, Jaehyun Song. Powered by [Quarto](https://quarto.org/)"
  google-analytics: "G-BCE61P2YP7"
  favicon: "imgs/favicon.png"
  navbar:
    search: true
    logo: "imgs/logo.png"
    background: "#1955A6" # royal blue
    left:
      - text: "CV"
        href: cv/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - sidebar:seminar
      - text: "Software"
        href: software/index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "Tutorials"
        href: tutorial/index.qmd
    right: 
      - icon: github
        href: https://github.com/JaehyunSong
      - icon: google
        href: https://scholar.google.com/citations?user=8a-NxjkAAAAJ&hl=ja
      - icon: mortarboard-fill
        href: https://researchmap.jp/jaysong
  sidebar:
    - id: seminar
      title: "Seminar"
      style: "docked"
      background: light
      contents:
        - text: 宋ゼミについて
          icon: bi-mortarboard
          href: seminar/index.qmd
        - text: 応募について
          icon: bi-person-add
          href: seminar/entry.qmd
        - text: よくある質問
          icon: bi-patch-question
          href: seminar/faq.qmd
        - text: "---"
        - text: 宋ゼミのメンバー
          href: seminar/people.qmd
        - text: ゼミ生の進路
          href: seminar/course.qmd
        - text: ゼミ生の研究成果
          href: seminar/research.qmd
        - text: これまでの倍率
          href: seminar/competition.qmd
        - text: 春休みの過ごし方
          href: seminar/preparation.qmd  
        - text: 担当教員について
          href: seminar/about_song.qmd  
  twitter-card:
    title: Jaehyun Song, Ph.D.
    description: Jaehyun Song's personal homepage
    card-style: summary
    creator: "@Tintstyle"
    site: "@Tintstyle"
    image: "imgs/favicon.png"
  open-graph:
    title: Jaehyun Song, Ph.D.
    description: Jaehyun Song's personal homepage
    image: "imgs/favicon.png"

format:
  html:
    theme: 
      light: flatly
    css: styles.css

resources: 
  - CNAME