---
title: "Jaehyun Song, Ph.D."
subtitle: "Ph.D. in Political Science"
about:
  template: solana
link-external-newwindow: true
---

```{r}
#| include: false
ff_ver <- system('plutil -extract "CFBundleShortVersionString" binary1 /Applications/Firefox.app/Contents/Info.plist -o -', intern = TRUE) |>
   stringr::str_extract("[0-9]+\\.[0-9]+\\.[0-9]+")

rs_ver1 <- system('plutil -extract "CFBundleShortVersionString" binary1 /Applications/RStudio.app/Contents/Info.plist -o -', intern = TRUE) |>
   stringr::str_extract("[0-9]+\\.[0-9]+\\.[0-9]+\\+[0-9]+")

macos_ver <- system('sw_vers -productVersion', intern = TRUE)
```

I am an associate professor in [Faculty of Informatics](https://www.kansai-u.ac.jp/Fc_inf/), [Kansai University](https://www.kansai-u.ac.jp/). I earned my Ph.D. and master degree in political science from [Kobe University](https://www.kobe-u.ac.jp/), and a bachelor degree in law from [Keio University](https://www.keio.ac.jp/ja/). My research interests are voting behavior, experimental political science, causal inference, and quantitative methodology. My CV is available [here](cv/cv.pdf).

:::{.callout-note}
## メニュー案内

* 宋のCVは[CV](cv/index.qmd)
* これまでの研究内容は[Research](research/index.qmd)
* 担当科目については[Teaching](teaching/index.qmd)
* 宋ゼミについては[Seminar](seminar/index.qmd)
* これまで作成したアプリ/パッケージ/スクリプトは[Software](software/index.qmd)
* 備忘録は[Note](notes/index.qmd)
* 分析/調査ツールのチュートリアルは[Tutorial](tutorial/index.qmd)
:::

:::{.callout-note}
## 宋の授業を履修する方へ（2022年度）

* [ミクロ政治データ分析実習](https://www.jaysong.net/micro-book/)（関西大学）
* [マクロ政治データ分析実習](https://www.jaysong.net/macro-book/)（関西大学）
* [社会科学における因果推論](https://www.jaysong.net/kandai-ci/)（関西大学）
* [方法論特殊講義III](https://www.jaysong.net/kobe-ci/)（神戸大学）
:::

:::{.callout-note}
## Information

* Last Update: `r format(Sys.Date(), "%Y/%m/%d")`
* Environment
   * macOS `r macos_ver` "Ventura"
   * Firefox `r ff_ver`
   * `r version$version.string`
   * RStudio `r rs_ver1`
   * Quarto `r quarto::quarto_inspect()$quarto$version`
   * R package {quarto} `r packageVersion("quarto")`
:::
