---
title: "Software / Packages / Scripts / Datasets"
date-modified: today
link-external-newwindow: true
---

## R Packages

* BalanceR <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/BalanceR)</span>
   * 実験データの共変量チェック; A balance check for experimental data using standaradized biases
* SimpleConjoint <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/SimpleConjoint)</span>
   * サーバーなしで（ていうか、宋のサーバーで）コンジョイント実験を行う（要Qualtrics）
* PRcalc <span class="jay_btn">[Manual](https://www.jaysong.net/PRcalc/)</span> <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/PRcalc)</span>
   * 比例代表計算機; Proportional Representation Calculator
* woRdle <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/woRdle)</span>
   * Rパッケージ名で遊ぶWordle; woRdle: Enjoying Wordle with R package names.
* q2c <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/q2c)</span> <span class="jay_btn">[Sample Dataset](Data/q2c_sample.csv)</span>
   * Qualtris + Conjoint Survey Design Toolで収集されたデータを読み込み、{cjoint}/{cregg}に適したデータへ加工

## Web Application

* PRcalc for Web <span class="jay_btn">[ShinyApps](https://jaysong.shinyapps.io/prcalc4web/) [GitHub](https://github.com/JaehyunSong/PRcalc4Web)</span>
* Web Conjoint <span class="jay_btn">[ShinyApps](https://jaysong.shinyapps.io/webconjoint/) [GitHub](https://github.com/JaehyunSong/web-conjoint)</span> <span class="jay_btn">[Sample Dataset](Data/webconjoint_sample.csv)</span>

## Scripts

#### For Qualtrics

* [リスト実験をする時に項目をランダマイズするスクリプト](scripts/list_randomizer.qmd)
* 画像URLをランダムに取得するスクリプト<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/RIP)</span>
* SimpleConjoint.js <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/SimpleConjoint.js)</span>
   * サーバーなしでコンジョイント実験を行う（要Qualtrics）
* [RPP: Rakuten p-Parameter Parser](scripts/rpp.qmd)
   * Qualtricsで楽天インサイトのpパラメーターをパーシングする。
- Item randomizer for Qualtrics <span class="jay_btn">[GitHub](https://github.com/JaehyunSong/qualtrics-list-js)</span>
   - Qualtricsでリスト実験（list experiment / item count technique）を実装する際、項目をランダム化するスクリプト

## Datasets

* M-1 グランプリ決勝データ<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/M-1_Grand_Pix)</span>
* インスタントラーメンの栄養成分データ<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/InstantNoodle)</span>
- 日本の中高等学校データ<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/highschool-japan/)</span>
- 中古車（プリウス）データ<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/dataset_prius)</span>
- モバイルOSシェア（2009-2022）<span class="jay_btn">[GitHub](https://github.com/JaehyunSong/mobile-os-share)</span>