---
title: "因果推論の道具箱"
date: "`r Sys.Date()`"
link-external-newwindow: true
toc: true
---

少しずつ埋めていきます

## 因果推論全般

* [Miguel A. Hernán and James M. Robins. 2020. *Causal Inference: What If.* Boca Raton: Chapman & Hall/CRC.](https://www.amazon.co.jp/dp/B08N6PV975) [[Web](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/)]
* [Scott Cunningham. 2021. *Causal Inference: The Mixtape*. Yale University Press.](https://www.amazon.co.jp/dp/0300251688) [[Web](https://mixtape.scunning.com/index.html)]
* [Nick Huntington-Klein. 2021. *The Effect: An Introduction to Research Design and Causality.* CRC Press.](https://www.amazon.co.jp/dp/1032127457/) [[Web](https://theeffectbook.net/index.html)]
* [Guido W. Imbens and Donald B. Rubin. 2015. *Causal Inference for Statistics, Social, and Biomedical Sciences: An Introduction*. Cambridge University Press.](https://www.amazon.co.jp/dp/0521885884/)
* [Stephen L. Morgan and Christopher Winship. 2014. *Counterfactuals and Causal Inference: Methods and Principles for Social Research.* Cambridge University Press.](https://www.amazon.co.jp/dp/B00SJL7TGK/)
* [Judea Pearl, Madelyn Glymour, and Nicholas P. Jewell. 2016. *Causal Inference in Statistics: A Primer*. Wiley.](https://www.amazon.co.jp/dp/1119186846/)
    * [『入門 統計的因果推論』](https://www.amazon.co.jp/dp/4254122411/)
* [安井翔太. 2020.『効果検証入門』技術評論社](https://www.amazon.co.jp/dp/4297111179/)
* [Thad Dunning. 2008. "Improving Causal Inference: Strengths and Limitations of Natural Experiments." *Political Research Quarterly.* 61 (2): 282-293](https://journals.sagepub.com/doi/10.1177/1065912907306470)
* [Michael G. Findley, Kyosuke Kikuta, and Michael Denly. 2021. "External Validity." *Annual Review of Political Science.* 24: 365-393](https://www.annualreviews.org/doi/abs/10.1146/annurev-polisci-041719-102556)
* [Seonho Kim. Awesome Causal Inference](https://github.com/ksseono/awesome-causal-inference)
* [Brady Neal. *Introduction to Causal Inference*](https://www.bradyneal.com/causal-inference-course)
* [嶌田栄樹・依田高典. 2020.「因果性と異質性の経済学①：限界介入効果」『京都大学大学院経済学研究科ディスカッションペーパーシリーズ』No.J-20-002](http://www.econ.kyoto-u.ac.jp/dp/papers/j-20-002.pdf)
* [嶌田栄樹・依田高典. 2020.「因果性と異質性の経済学②：Causal Forest」『京都大学大学院経済学研究科ディスカッションペーパーシリーズ』No.J-20-004](http://www.econ.kyoto-u.ac.jp/dp/papers/j-20-004.pdf)
* [Bryan, Christopher J., Elizabeth Tipton and David S. Yeager. 2021. "Behavioural science is unlikely to change the world without a heterogeneity revolution," *Nature Human Behaviour.*](https://www.nature.com/articles/s41562-021-01143-3)
* [川田恵介. 『Rによる比較・予測・因果推論入門』](https://tetokawata.github.io/R_JPN/)
* [古川知志雄.『統計推論再考 – 概念と技法 –』](https://chishio318.github.io/statistics/index.html)

## Potential Outcome Framework

- [Francesca Dominici, Falco J. Bargagli-Stoffi, and Fabrizia Mealli. 2020. "From controlled to undisciplined data: estimating causal effects in the era of data science using a potential outcome framework." *arXiv*:2012.06865](https://arxiv.org/abs/2012.06865)
- [Laura Forastiere, Edoardo M. Airoldi, and Fabrizia Mealli. 2020. "Identification and Estimation of Treatment and Interference Effects in Observational Studies on Networks." *Journal of the American Statistical Association.*](https://doi.org/10.1080/01621459.2020.1768100)

## DAG

- [Peter W G Tennant, Eleanor J Murray, Kellyn F Arnold, Laurie Berrie, Matthew P Fox, Sarah C Gadd, Wendy J Harrison, Claire Keeble, Lynsie R Ranker, Johannes Textor, Georgia D Tomova, Mark S Gilthorpe, and George T H Ellison. 2020. "Use of directed acyclic graphs (DAGs) to identify confounders in applied health research: review and recommendations," *International Journal of Epidemiology*. dyaa213](https://academic.oup.com/ije/advance-article/doi/10.1093/ije/dyaa213/6012812)
- [Causal Inference Korea. *The Book of Why*](https://causal-inference-korea.gitbook.io/the-book-of-why/)

## Randomized Controlled Trials

* [Susan Athey and Guido Imbens. 2016. "The Econometrics of Randomized Experiments," *arXiv*:1607.00698](https://arxiv.org/abs/1607.00698)
* [長谷川龍樹・多田奏恵・米満文哉・池田鮎美・山田祐樹・高橋康介・近藤洋史. 2021.「実証的研究の事前登録の現状と実践ーOSF事前登録チュートリアル」『心理学研究』92(3): 188-196.](https://doi.org/10.4992/jjpsy.92.20217)
* [河野勝. 2016. 「政治学における実験研究」『早稻田政治經濟學雜誌』391: 7-16](https://www.waseda.jp/fpse/pse/assets/uploads/2014/05/276d84d747bfce10b40ccd7f03e08131.pdf)
* [多湖淳. 2021. 「政治学における実験研究 その2」『早稻田政治經濟學雜誌』397: 2-7](https://www.waseda.jp/fpse/pse/assets/uploads/2021/11/805d36cc62b5465d7ff291a93cd63f83.pdf)

### Field Experiments

* [Alan S. Gerber and Donald P. Green. 2012. *Field Experiments: Design, Analysis, and Interpretation.* W W Norton & Co Inc](https://www.amazon.co.jp/dp/0393979954/)
* [Trisha Phillips. 2021. "Ethics of Field Experiments," *Annual Review of Political Science.* 24: 277-300.](https://doi.org/10.1146/annurev-polisci-041719-101956)

### Laboratory Experiments

* -

### Survey Experiments

* [Song Jaehyun・秦正樹. 2020. 「オンライン・サーベイ実験の方法: 理論編」『理論と方法』35 (1): 92-108.](https://doi.org/10.11218/ojjams.35.92)
* [秦正樹・Song Jaehyun. 2020. 「オンライン・サーベイ実験の方法: 実践編」『理論と方法』35 (1): 109-127.](https://doi.org/10.11218/ojjams.35.109)
* [Christopher Grady. *10 Things to Know About Survey Experiments .*](https://egap.org/resource/10-things-to-know-about-survey-experiments/)
* [Sergio Martini and Francesco Olmastroni. 2021. "From the lab to the poll: The use of survey experiments in political research." *Italian Political Science Review / Rivista Italiana di Scienza Politica Italian Political Science Review.* ](https://www.cambridge.org/core/journals/italian-political-science-review-rivista-italiana-di-scienza-politica/article/from-the-lab-to-the-poll-the-use-of-survey-experiments-in-political-research/D511DF7A99A9202EC43807AE6D6424E3)
* [Luke W. Miratrix, Jasjeet S. Sekhon, Alexander G. Theodoridis, and Luis F. Campos. Worth Weighting? "How to Think About and Use Weights in Survey Experiments." *Political Analysis.* 26(3): 275-291. ](https://www.cambridge.org/core/journals/political-analysis/article/worth-weighting-how-to-think-about-and-use-weights-in-survey-experiments/C22485D7BA0F76400B75E02559F110E2)
* [Ingar Haaland, Christopher Roth and Johannes Wohlfart. forthcoming. "Designing Information Provision Experiments," *Journal of Economic Literature*](https://www.aeaweb.org/articles?id=10.1257/jel.20211658)
* [David J. Hauser, Phoebe C. Ellsworth and Richard Gonzalez. 2018. "Are Manipulation Checks Necessary?," *Frontiers in Psychology,* 9:998](https://www.frontiersin.org/articles/10.3389/fpsyg.2018.00998/full)

#### Survey Experiments: Priming/Framing

* -

#### Survey Experiments: List

* (多変量解析を用いた被験者の属性ごとの予測値の推定1) Imai Kosuke. 2011. "Multivariate Regression Analysis for the Item Count Technique." *Journal of the American Statistical Association.* 106(494):407–416.
* (多変量解析を用いた被験者の属性ごとの予測値の推定2) Blair Graeme, Imai Kosuke. 2012. "Statistical Analysis of List Experiments." *Political Analysis.* 20(1):47–77
* (Cobminedリスト実験とその仮定の検定) [Peter M. Aronow, Alexander Coppock, Forrest W. Crawford, and Donald P. Green. 2015. "Combining List Experiment and Direct Question Estimates of Sensitive Behavior Prevalence." *Journal of Survey Statistics and Methodology,* 3(1):43–66.](https://doi.org/10.1093/jssam/smu023)
* (予測値を説明変数として用いる手法) [Kosuke Imai, Bethany Park, and Kenneth F. Greene. 2017. "Using the Predicted Responses from List Experiments as Explanatory Variables in Regression Models." *Political Analysis.* 23(2): 180-196.](https://www.cambridge.org/core/journals/political-analysis/article/using-the-predicted-responses-from-list-experiments-as-explanatory-variables-in-regression-models/9696A7F03D046AC70D4F5C647D9AAACE)
* [Winston Chou, Kosuke Imai, and Bryn Rosenfeld. 2020. "Sensitive Survey Questions with Auxiliary Information." *Sociological Methods & Research.* 49(2): 418-454.](https://journals.sagepub.com/doi/full/10.1177/0049124117729711)
* (洗練化されたリスト実験) [Tsuchiya Takahiro, Hirai Yoko. 2010. "Elaborate Item Count Questioning: Why Do People Underreport in Item Count Responses?" *Survey Research Methods.* 4(3):139–149.](https://ojs.ub.uni-konstanz.de/srm/article/view/4620)
* (教育水準の低い被験者における過大推定/統制群にプラセボ項目を挿入し、バイアスを抑制) [Guillem Riambau and Kai Ostwald. 2020. "Placebo statements in list experiments: Evidence from a face-to-face survey in Singapore." *Political Science Research and Methods.* 9(1):172-179.](https://doi.org/10.1017/psrm.2020.18)
* (リスト実験から得られた推定値の不安定性について) [Stefanie Gosen, Peter Schmidt, Stefan Thörner and Jürgen Leibold. 2018. "Is the List Experiment Doing its Job?: Inconclusive Evidence!" *Einstellungen und Verhalten in der empirischen Sozialforschung.* pp.179-205.](https://link.springer.com/chapter/10.1007/978-3-658-16348-8_8)
* [Graeme Blair, Alexander Coppock, and Magaret Moor. 2020. "When to Worry about Sensitivity Bias: A Social Reference Theory and Evidence from 30 Years of List Experiments." *American Political Science Review,* 114(4): 1297–1315.](https://doi.org/10.1017/S0003055420000374)
* [Patrick M. Kuhn and Nick Vivyan. 2021. "The Misreporting Trade-Off Between List Experiments and Direct Questions in Practice: Partition Validation Evidence from Two Countries," *Political Analysis,* 30(3): 381-402.](https://doi.org/10.1017/pan.2021.10)
* [John S. Ahlquist. 2017. "List Experiment Design, Non-Strategic Respondent Error, and Item Count Technique Estimators," *Political Analysis,* 26(1): 34-53.](https://doi.org/10.1017/pan.2017.31)

#### Survey Experiments: Conjoint

* (解説1) [Jens Hainmueller, Daniel J. Hopkins, and Teppei Yamamoto. 2014. "Causal Inference in Conjoint Analysis: Understanding Multidimensional Choices via Stated Preference Experiments." *Political Analysis.* 22(1):1–30.](https://www.cambridge.org/core/journals/political-analysis/article/causal-inference-in-conjoint-analysis-understanding-multidimensional-choices-via-stated-preference-experiments/414DA03BAA2ACE060FFE005F53EFF8C8)
* (解説2) [Kirk Bansak, Jens Hainmueller, Dan Hopkins, and Teppei Yamamoto. "Conjoint Survey Experiments," in Jamie Druckman and Don Green ed. *Cambridge Handbook of Advances in Experimental Political Science.*](https://cpb-us-w2.wpmucdn.com/web.sas.upenn.edu/dist/f/49/files/2019/09/handbook-draft-07-09202019-1.pdf)
* (AMCEについて) [Kirk Bansak, Jens Hainmueller, Daniel J. Hopkins, and Teppei Yamamoto. "Using Conjoint Experiments to Analyze Elections: The Essential Role of the Average Marginal Component Effect (AMCE)" *SSRN.*](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3588941)
* (MMについて) [Thomas J. Leeper, Sara B. Hobolt, and James Tilley. 2019. "Measuring Subgroup Preferences in Conjoint Experiments," *Political Analysis.* 28(2): 207-221.](https://www.cambridge.org/core/journals/political-analysis/article/abs/measuring-subgroup-preferences-in-conjoint-experiments/4F2C21AC02753F1FFF2F5EA0F943C1B2)
* (属性数について) [Kirk Bansak, Jens Hainmueller, Daniel J. Hopkins, and Teppei Yamamoto. 2019. "Beyond the Breaking Point? Survey Satisficing in Conjoint Experiments," *Political Science Research and Methods.*](https://www.cambridge.org/core/journals/political-science-research-and-methods/article/abs/beyond-the-breaking-point-survey-satisficing-in-conjoint-experiments/47EBFC9D8CE2CA88D6C01870192F8956)
* (タスク数について) [Kirk Bansak, Jens Hainmueller, Daniel J. Hopkins, and Teppei Yamamoto. 2018. "The Number of Choice Tasks and Survey Satisficing in Conjoint Experiments." *Political Analysis.* 26 (1): 112-119.](https://www.cambridge.org/core/journals/political-analysis/article/number-of-choice-tasks-and-survey-satisficing-in-conjoint-experiments/5BBACB75CF59C10E1B42AB20D9F085F0)
* (日本の事例) [宋財泫・善教将大. 2016. 「コンジョイント実験の方法論的検討」『法と政治』67(2): 67-108.](https://kwansei.repo.nii.ac.jp/?action=pages_view_main&active_action=repository_view_main_item_detail&item_id=18253&item_no=1&page_id=30&block_id=85)
* (外的妥当性について1) [Jens Hainmueller, Dominik Hangartner, and Teppei Yamamoto. 2015. "Validating vignette and conjoint survey experiments against real-world behavior." *Proceedings of the National Academy of Sciences of the United States of America,* 112(8), 2395–2400.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4345583/)
* (外的妥当性について2) [Brandon de la Cuesta, Naoki Egami, and Kosuke Imai. 2021. "Improving the External Validity of Conjoint Analysis: The Essential Role of Profile Distribution." *Political Analysis.*](https://www.cambridge.org/core/journals/political-analysis/article/abs/improving-the-external-validity-of-conjoint-analysis-the-essential-role-of-profile-distribution/B911EF14513292A24ECB4AC4BAA3FA6B)
* [Erik Knudsen and Mikael Poul Johannesson. 2019. "Beyond the Limits of Survey Experiments: How Conjoint Designs Advance Causal Inference in Political Communication Research." *Political Communication.* 36(2): 259-271](https://www.tandfonline.com/doi/full/10.1080/10584609.2018.1493009)

## Matching

## Propensity Score

* [Gary King and Richard Nielsen. 2019. "Why Propensity Scores Should Not Be Used for Matching." *Political Analysis.* 27(4): 435-454.](https://www.cambridge.org/core/journals/political-analysis/article/why-propensity-scores-should-not-be-used-for-matching/94DDE7ED8E2A796B693096EB714BE68B/share/9d9a82aedc7dcce1a9d9a6a25cf4641af04e81ad)

* [Edward H. Kennedy. 2017. "Nonparametric Causal Effects Based on Incremental Propensity Score Interventions." *Journal of the American Statistical Association.* 114 (526): 645-656.](https://www.tandfonline.com/doi/full/10.1080/01621459.2017.1422737)

* [芝孝一郎.「傾向（プロペンシティ）スコアの各使用法の仮定・解釈の違いを比較してみた」](https://www.krsk-phs.com/entry/propensity_score_comparison)

## Difference in Difference

- [Difference-in-Difference](https://diff.healthpolicydatascience.org/)

- [Coady Wing, Kosali Simon, and Ricardo A. Bello-Gomez. 2018. "Designing Difference in Difference Studies: Best Practices for Public Health Policy Research." *Annual Review of Public Health*. 39:453-469.](https://www.annualreviews.org/doi/full/10.1146/annurev-publhealth-040617-013507)

- (Diff-in-DiffとSCM) [Bongho Lee. "Difference in Difference"](https://bonokr.notion.site/Difference-in-Difference-44ab9e0d0dbe4b71b641f317dbc4fe7a)

- [Andrew Goodman-Bacon. 2021. "Difference-in-differences with variation in treatment timing," *Journal of Econometrics*](https://doi.org/10.1016/j.jeconom.2021.03.014)

- [Asjad Naqvi. *DiD literature.*](https://asjadnaqvi.github.io/DiD/)

## Synthetic Control Method

- [前田豊・鎌田 拓馬. 2019.「Synthetic Control Methodを用いた個別事例の因果効果の識別」『理論と方法』34 (1): 78-96](https://www.jstage.jst.go.jp/article/ojjams/34/1/34_78/_article/-char/ja)

## Regression Discontinuity Design

* [Takuya Ishihara and Masayuki Sawada. 2021. "Manipulation-Robust Regression Discontinuity Designs." *arXiv*:2009.07551](https://arxiv.org/abs/2009.07551)

* [Justin McCrary. 2008. "Manipulation of the running variable in the regression discontinuity design: A density test." *Journal of Econometrics.* 142 (2): 698-714.](https://www.sciencedirect.com/science/article/abs/pii/S0304407607001133)

* [Andrew Gelman and Guido Imbens. 2019. "Why High-Order Polynomials Should Not Be Used in Regression Discontinuity Designs." *Journal of Business & Economic Statistics.* 37(3): 447-456.](https://www.tandfonline.com/doi/full/10.1080/07350015.2017.1366909)

* [Marinho Bertanha and Guido W. Imbens. 2019. "External Validity in Fuzzy Regression Discontinuity Designs." *Journal of Business & Economic Statistics.* 38(3): 593-612](https://www.tandfonline.com/doi/full/10.1080/07350015.2018.1546590)

* [Erin Hartman. 2020. "Equivalence Testing for Regression Discontinuity Designs." *Political Analysis.* ](https://doi.org/10.1017/pan.2020.43)

* [Matias D. Cattaneo, Nicolás Idrobo, and Rocío Titiunik. 2020. *A Practical Introduction to Regression Discontinuity Designs: Foundations.* Cambridge University Press.](https://www.amazon.co.jp/dp/1108710204) [[arXiv]](https://arxiv.org/abs/1911.09511)

* [Metin Bulus. 2021. "Minimum Detectable Effect Size Computations for Cluster-Level Regression Discontinuity Studies: Specifications Beyond the Linear Functional Form," *Journal of Research on Educational Effectiveness.*](https://doi.org/10.1080/19345747.2021.1947425)

* [Yoichi Arai, Taisuke Otsu, Myung Hwan Seo. 2021. "Regression Discontinuity Design with Potentially Many Covariates," arXiv:2109.08351](https://arxiv.org/abs/2109.08351)

## Instrumental Variable

- [Joshua D. Angrist and Alan B. Krueger. 2001. "Instrumental Variables and the Search for Identification: From Supply and Demand to Natural Experiments," *Journal of Economic Perspectives,* 15 (4): 69-85.](https://www.aeaweb.org/articles?id=10.1257/jep.15.4.69)
- [Allison J. Sovey and Donald P. Green. 2010. "Instrumental Variables Estimation in Political Science: A Readers’ Guide," *American Journal of Political Science,* 55(1): 188-200.](https://doi.org/10.1111/j.1540-5907.2010.00477.x)
- [Kenneth A. Bollen. 2012. "Instrumental Variables in Sociology and the Social Sciences," *Annual Review of Sociology,* 38:37-72.](https://doi.org/10.1146/annurev-soc-081309-150141)
- [Peter M. Aronow and Allison Carnegie. 2013. "Beyond LATE: Estimation of the Average Treatment Effect with an Instrumental Variable," *Political Analysis,* 21 (4): 492-506.](https://www.cambridge.org/core/journals/political-analysis/article/beyond-late-estimation-of-the-average-treatment-effect-with-an-instrumental-variable/604E0803793175CF88329DB34DAA80B3)

## Balance Check

- [Stefan Tübbicke. "Entropy Balancing for Continuous Treatments." *arXiv*:2001.06281 ](https://arxiv.org/abs/2001.06281)
- (分散比について) [Peter C. Austin. 2009. "Using the Standardized Difference to Compare the Prevalence of a Binary Variable Between Two Groups in Observational Research." *Communications in Statistics-Simulation and Computation.* 38 (6): 1228-1234. ](https://doi.org/10.1080/03610910902859574)
- (標準化差分について) [Svetlana V. Belitser, Edwin P. Martens, Wiebe R. Pestman, Rolf H.H. Groenwold, Anthonius de Boer, and Olaf H. Klungel. 2011. "Measuring Balance and Model Selection in Propensity Score Methods." *Pharmacoepidemiology and Drug Safety,* 20(11): 1115–29.](https://doi.org/10.1002/pds.2188)
- (標準化差分について) [M. Sanni Ali, Rolf H. H. Groenwold, Wiebe R. Pestman, Svetlana V. Belitser, Kit C. B. Roes, Arno W. Hoes, Anthonius de Boer, and Olaf H. Klungel. 2014. "Propensity Score Balance Measures in Pharmacoepidemiology: A Simulation Study." *Pharmacoepidemiology and Drug Safety,* 23(8): 802–11](https://doi.org/10.1002/pds.3574)
- (標準化差分について) [Stuart, Elizabeth A., Brian K. Lee, and Finbarr P. Leacy. 2013. "Prognostic Score-Based Balance Measures Can Be a Useful Diagnostic for Propensity Score Methods in Comparative Effectiveness Research." *Journal of Clinical Epidemiology,* 66(8):S84.](https://doi.org/10.1016/j.jclinepi.2013.01.013)
- (経験CDF統計量(eCDF)について) [Peter C. Austin, and Elizabeth A. Stuart. 2015. “Moving Towards Best Practice When Using Inverse Probability of Treatment Weighting (IPTW) Using the Propensity Score to Estimate Causal Treatment Effects in Observational Studies.” *Statistics in Medicine,* 34(28):3661–3679.](https://doi.org/10.1002/sim.6607)

## Econometrics and Data Analysis

- [Bruce E. Hansen. *Econometrics*. Web](https://www.ssc.wisc.edu/~bhansen/econometrics/)
- [OpenIntro Statistics](https://www.openintro.org/book/os/)
   * [日本語版](http://www.kunitomo-lab.sakura.ne.jp/2021-3-3Open(S).pdf)あり
- [shinmee. 『俺の計量経済学』](https://datascience-blog.com/2019/12/21/post-607/)
- [Rachel Rosenberg et al.. *Computational Applications to Behavioral Science*](https://gsbdbi.github.io/ml_for_behavioral_science/)
* [Kohei Kawaguchi. Applied Econometrics Slides.](https://kohei-kawaguchi.github.io/AppliedEconometricsPublic/)

## Dataset

- [Hidenori Takahash. Data Source](https://sites.google.com/view/osipp-dsc/home)