---
title: "無料で読めるR教材"
date: "`r Sys.Date()`"
link-external-newwindow: true
---

少しずつ埋めていきます

## 全般

* [SONG Jaehyun・矢内勇生.『私たちのR: ベストプラクティスの探求』](https://www.jaysong.net/rbook)
* [森知晴.『卒業論文のためのR入門』](https://tomoecon.github.io/R_for_graduate_thesis/)
* [Nathaniel D. Phillips. *YaRrr! The Pirate’s Guide to R*](https://bookdown.org/ndphillips/YaRrr/)
* [Chester Ismay and Albert Y. Kim. *Statistical Inference via Data Science: A ModernDive into R and the Tidyverse*](https://moderndive.com/)
* [Hadley Wickham and Garrett Grolemund. *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.had.co.nz/) [[Korean](https://sulgik.github.io/r4ds/)]
* [Hadley Wickham. *Advanced R (2nd Ed.)*](https://adv-r.hadley.nz/)
* [Hadley Wickham and Jennifer Bryan. *R Packages: Organize, Test, Document and Share Your Code*](https://r-pkgs.org/)
* [Colin Gillespie and Robin Lovelace. *Efficient R programming: A Practical Guide to Smarter Programming*](https://csgillespie.github.io/efficientR/)
* [Roger D. Peng. *R Programming for Data Science*](https://bookdown.org/rdpeng/rprogdatascience/)
* [Garrett Grolemund. *Hands-On Programming with R: Write Your Own Functions and Simulations*](https://rstudio-education.github.io/hopr/)
* [The Carpentries. *R for Reproducible Scientific Analysis*](https://swcarpentry-ja.github.io/r-novice-gapminder/ja/)
* [Monash Data Fluency . *Reproducible Research in R*](https://monashdatafluency.github.io/r-rep-res/)
* [Garrett Grolemund. *Master the Tidyverse*](https://github.com/rstudio-education/master-the-tidyverse)
* [Hadley Wickham. *The tidyverse style guide*](https://style.tidyverse.org/)
* [Oscar Baruffa. *Big Book of R*](https://www.bigbookofr.com/)
* [Mark van der Laan, Jeremy Coyle, Ivana Malenica, Rachael Phillips, and Rachael Phillips. *Targeted Learning in R: Causal Data Science with the tlverse Software *](https://tlverse.org/tlverse-handbook/index.html)
* [Andrew Ba Tran. *R for Journalists*](https://learn.r-journalism.com/en/)
* [nissinbo. 「医療情報DB解析のためのデータハンドリング大全」](https://nissinbo.github.io/medical_database_RBook/)
* [김길환. 2021. R 프로그래밍 (개정판)](https://kilhwan.github.io/rprogramming/)
* [Yang Feng and Jianan Zhu. *R Programming: Zero to Pro*](https://r02pro.github.io/)
* [Socio-Econ. 『資料 R&Rパッケージを利用した社会経済データの取得と利用方法(作成中)』](https://toad-office.github.io/socio-econ/)
* [山本雅資『2021年度データ分析入門』](https://yamamoto-masashi.github.io/DSlec/)
* [Jaeyeon Kim. *Computational Thinking for Social Scientists.*](https://jaeyk.github.io/PS239T/)
* [Syunsuke Fukuda.『Rビギナーズガイド』](https://syunsuke.github.io/r_beginners_guide/)
* [R Bootcamp](https://r-bootcamp.netlify.app/)

## 可視化

* [Kieran Healy. *Data Visualization: A practical introduction*](https://socviz.co/)
* [Claus O. Wilke. *Fundamentals of Data Visualization*](https://clauswilke.com/dataviz/)
* [Winston Chang. *R Graphics Cookbook (2nd Ed.)*](https://r-graphics.org/)
* [*The R Graph Gallery*](https://www.r-graph-gallery.com/)
* [World Bank. *R Econ Visual Library*](https://worldbank.github.io/r-econ-visual-library/index.html)

## R Markdown

* [Yihui Xie, J. J. Allaire, and Garrett Grolemund. *R Markdown: The Definitive Guide*](https://bookdown.org/yihui/rmarkdown/)
* [Yihui Xie, Christophe Dervieux, and Emily Riederer. *R Markdown Cookbook*](https://bookdown.org/yihui/rmarkdown-cookbook/)
   * [『R Markdown クックブック』](https://gedevan-aleksizde.github.io/rmarkdown-cookbook/)
* [Yihui Xie, Amber Thomas, and Alison Presmanes Hill. *blogdown: Creating Websites with R Markdown*](https://bookdown.org/yihui/blogdown/)
* [Yihui Xie. *bookdown: Authoring Books and Technical Documents with R Markdown*](https://bookdown.org/yihui/bookdown/)
* [Resul Umit. *Writing Reproducible Research Papers with R Markdown*](https://github.com/resulumit/rmd_workshop)
* [Matthew Crump. *Open tools for writing open interactive textbooks*](https://crumplab.github.io/OER_bookdown/)
* [高橋康介.「[連載] R Markdownで楽々レポートづくり」](https://gihyo.jp/admin/serial/01/r-markdown)

## Shiny

* [Hadley Wickham. *Mastering Shiny.*](https://mastering-shiny.org/)
* [David Granjon. *Outstanding User Interfaces with Shiny.*](https://unleash-shiny.rinterface.com/)

## 計量経済学、計量政治学、統計学

* [土井翔平.『Rで計量政治学入門』](https://shohei-doi.github.io/quant_polisci/)
* [津田裕之.『Rによる統計入門』](https://htsuda.net/stats/)
* [安藤道人・三田匡能.『Rで学ぶ計量経済学と機械学習』](https://michihito-ando.github.io/econome_ml_with_R/)
* [Christoph Hanck, Martin Arnold, Alexander Gerber, and Martin Schmelzer. *Introduction to Econometrics with R*](https://www.econometrics-with-r.org/)
* [Florian Heiss. *Using R for Introductory Econometrics, 2nd edition*](http://www.urfie.net/read/index.html)
   * [Pythonバージョン](http://www.upfie.net/read/index.html)
* [Neale Batra (Ed.). *The Epidemiologist R Handbook*](https://epirhandbook.com/)
* [Adam Fleischhacker. *A Business Analyst's Introduction to Business Analytics*](https://www.causact.com/)

## ベイジアン統計学

* [A Solomon Kurz. *Statistical Rethinking with brms, ggplot2, and the tidyverse.*](https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/)
* [Alicia A. Johnson, Miles Ott and Mine Dogucu. *Bayes Rules! An Introduction to Bayesian Modeling with R.*](https://www.bayesrulesbook.com/)
* [Virgilio Gómez-Rubio. *Bayesian inference with INLA.*](https://becarioprecario.bitbucket.io/inla-gitbook/index.html)

## 因果推論

* [矢内勇生.『KUT 計量経済学応用: 統計的因果推論入門』](https://yukiyanai.github.io/econometrics2/)
* [Paul C. Bauer. *Applied Causal Analysis (with R)*](https://bookdown.org/paul/applied-causal-analysis/)
* [Gertler, Paul J., Sebastian Martinez, Patrick Premand, Laura B. Rawlings, and Christel M. J. Vermeersch. *Impact Evaluation in Practice, Second Edition*](https://openknowledge.worldbank.org/handle/10986/25030)
   * [Solution] [Liam F. Beiser-McGrath. *Impact Evaluation in Practice: Solutions for Second Edition in R*](https://lfbeisermcgrath.github.io/rimpactevaluation/)

## その他

* [国里愛彦・竹林由武.『今日からできる再現可能な論文執筆』](https://ykunisato.github.io/jpa2020-tws-002/)
* [Max Kuhn and Julia Silge. *Tidy Modeling with R*](https://www.tmwr.org/)
* [Paul Roback and Julie Legler. *Beyond Multiple Linear Regression: Applied Generalized Linear Models and Multilevel Models in R*](https://bookdown.org/roback/bookdown-BeyondMLR/)
* [Rafael A. Irizarry. *Introduction to Data Science: Data Analysis and Prediction Algorithms with R*](https://rafalab.github.io/dsbook/)
* [Julia Silge and David Robinson. *Text Mining with R: A Tidy Approach*](https://www.tidytextmining.com/)
* [Pablo Casas. *Data Science Live Book*](https://livebook.datascienceheroes.com/)
* [Mathias Harrer, Pim Cuijpers, Toshi A. Furukawa, and David D. Ebert. *Doing Meta-Analysis in R: A Hands-on Guide*](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/)
* [슬기로운 통계생활. 딥러닝 공략집 with R](https://statisticsplaybook.github.io/deeplearning-playbook/)
* [Chris Brown, Murray Cadzow, Paula A Martinez, Rhydwyn McGuire, David Neuzerling, David Wilkinson, Saras Windecker. *Github actions with R.*](https://orchid00.github.io/actions_sandbox/)
* [Yan Lu and Sharon L. Lohr. *R Companion for Sampling: Design and Analysis (3rd Ed.)*](https://www.sharonlohr.com/sampling-design-and-analysis-3e)