<!DOCTYPE html>
<html lang="ja-jp">
    <head>
        
        
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96999602-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-96999602-1');
  gtag('set', {'user_id': 'USER_ID'});
</script>


        
        <script defer src="../fa/fontawesome-all.js"></script>
        

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>dplyr入門 (新版)</title>
        
        <style>

    html body {
        font-family: 'Noto Sans', sans-serif;
        background-color: white;
    }

    :root {
        --accent: darkred;
        --border-width:  5px ;
    }

</style>


<link rel="stylesheet" href="https://www.jaysong.net/css/main.css">





<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto%20Sans">


 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css"> 


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/php.min.js"></script>
    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/html.min.js"></script>
    
    <script>hljs.initHighlightingOnLoad();</script>






<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>$(document).on('click', function() { $('.collapse').collapse('hide'); })</script>
 <meta name="generator" content="Hugo 0.70.0" />
        

        
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-96999602-1"></script>
            <script>
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments)};
              gtag('js', new Date());
              gtag('config', 'UA-96999602-1');
              gtag('set', {'user_id': 'USER_ID'});
            </script>
        

        
            <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
        

        

    </head>

    <body>
        

        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand visible-xs" href="#">dplyr入門 (新版)</a>
                    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    
                        <ul class="nav navbar-nav">
                            
                                <li><a href="../">Home</a></li>
                            
                                <li><a href="../about/">CV</a></li>
                            
                                <li><a href="../research/">Research</a></li>
                            
                                <li><a href="../teaching/">Teaching</a></li>
                            
                                <li><a href="../software/">Software</a></li>
                            
                                <li><a href="../notes/">Notes</a></li>
                            
                                <li><a href="../tutorial/">Tutorial</a></li>
                            
                        </ul>
                    
                    
                        <ul class="nav navbar-nav navbar-right">
                            
                                <li class="navbar-icon"><a href="mailto:jasong@mail.doshisha.ac.jp"><i class="far fa-envelope"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://twitter.com/Tintstyle/"><i class="fab fa-twitter"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.facebook.com/tintstyle"><i class="fab fa-facebook"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.instagram.com/tintstyle/"><i class="fab fa-instagram"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://github.com/JaehyunSong/"><i class="fab fa-github"></i></a></li>
                            
                        </ul>
                    
                </div>
            </div>
        </nav>


<main>

    <div>
        <h2><center>dplyr入門 (新版)</center></h2>
        <h5><center></center></h5>
        <center>
<a href="https://www.jaysong.net/tags/%E7%B5%B1%E8%A8%88%E5%AD%A6"><kbd class="item-tag">統計学</kbd></a>

<a href="https://www.jaysong.net/tags/r"><kbd class="item-tag">R</kbd></a>

<a href="https://www.jaysong.net/tags/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%8F%E3%83%B3%E3%83%89%E3%83%AA%E3%83%B3%E3%82%B0"><kbd class="item-tag">データハンドリング</kbd></a>

</center>
    </div>

    <div align="start" class="content">
<script src="../rmarkdown-libs/kePrint/kePrint.js"></script>


<div id="はじめに" class="section level2">
<h2>はじめに</h2>
<ul>
<li>以下の内容は現在執筆中の内容の一部となります。
<ul>
<li>Song Jaehyun・矢内勇生『私たちのR: あなたのために書いたわけじゃない (仮)』(E-book)</li>
<li>したがって、いきなり<strong>オブジェクト</strong>、<strong>関数</strong>、<strong>引数</strong>といった馴染みのない概念が出てきます。これらの概念に馴染みのない方は、予め「<a href="../rprogramming/">Rプログラミング入門の入門</a>」をご一読ください。</li>
</ul></li>
<li>2020年6月に公開されましたdplyr 1.0.0に対応しております。</li>
<li>2016年5月に作成しました旧版は<a href="../dplyr_intro_old/">ここ</a>から閲覧できます。</li>
<li>実習データは<a href="../Data/Ramen.csv">ここ</a>からダウンロード可能です。</li>
</ul>
<hr />
</div>
<div id="パッケージと実習用データの読み込み" class="section level2">
<h2>パッケージと実習用データの読み込み</h2>
<p>パッケージは<code>dplyr</code>でも、<code>tidyverse</code>でもどれでも構いません。ここではデータをtibble型として読み込むため、<code>tidyverse</code>を読み込んでおきます。</p>
<pre class="r numberLines"><code>library(tidyverse)</code></pre>
<pre><code>## ─ Attaching packages ────────────────────────── tidyverse 1.3.0 ─</code></pre>
<pre><code>## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
## ✓ tibble  3.0.1     ✓ dplyr   1.0.0
## ✓ tidyr   1.1.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.5.0</code></pre>
<pre><code>## ─ Conflicts ──────────────────────────── tidyverse_conflicts() ─
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<p>それでは今回の実習用データを読み込みましょう。<a href="../Data/Ramen.csv">Ramen.csv</a>には「<a href="https://www.gnavi.co.jp">ぐるなび</a>」から取得したラーメン屋6292店舗の情報が入っています。具体的には東京、神奈川、千葉、埼玉、大阪、京都、兵庫、奈良、和歌山それぞれ都府県にあるラーメン屋の中から最大1000店舗の情報を抽出したものです。東京都は、ぐるなびに登録したラーメン屋が3000店舗以上ですが、1000店舗の基準はぐるなびの「おすすめ」の順で上位1000店舗となります。また、店側またはぐるなびが登録したカテゴリを基準に抽出したため、実際はラーメン屋ではないにもかかわらずラーメン屋としてデータ内に含まれている可能性があります。</p>
<p>まず、このデータを読み込み、<code>df</code>という名付けます。R内蔵関数である<code>read.csv()</code>を使ってデータを読み込んでも以下の内容を実習するにあたって全く問題はございません。<code>read.csv()</code>から読み込まれたデータのクラスはデータフレーム、<code>read_csv()</code>の場合はtibbleです。tibbleはデータフレームの拡張版であり、データフレームで可能な操作は全てtibbleにおいても可能です。ここではtibbleを使いますが、こちらの方が、結果が読みやすく出力されるからです。</p>
<pre class="r numberLines"><code># ファイルのパスは適宜修正してください
df &lt;- read_csv(&quot;Data/Ramen.csv&quot;)</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_character(),
##   Name = col_character(),
##   Pref = col_character(),
##   Zipcode = col_double(),
##   Latitude = col_double(),
##   Longitude = col_double(),
##   Line = col_character(),
##   Station = col_character(),
##   Walk = col_double(),
##   Bus = col_double(),
##   Car = col_double(),
##   Budget = col_double(),
##   ScoreN = col_double(),
##   Score = col_double()
## )</code></pre>
<p>本サンプルデータはUTF-8で保存されており、文字化けが生じる場合、以下のように対処してください。</p>
<pre class="r"><code># readrパッケージのread_csv()を使う場合
df &lt;- read_csv(&quot;Data/Ramen.csv&quot;, locale = locale(encoding = &quot;utf8&quot;))

# R内臓のread.csv()を使う場合
df &lt;- read_csv(&quot;Data/Ramen.csv&quot;, fileEncoding = &quot;utf8&quot;)</code></pre>
<p>データの中身を確認してみましょう。</p>
<pre class="r numberLines"><code>df</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    ID    Name  Pref  Zipcode Latitude Longitude Line  Station  Walk   Bus   Car
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 e539… 居酒屋 … 東京都… 1040031     35.7      140. 地下鉄有… 銀座一丁目駅…     3    NA    NA
##  2 gfeb… 本格上海… 東京都… 1100005     35.7      140. 地下鉄日… 仲御徒町駅…     1    NA    NA
##  3 ggt5… 食べ飲み… 東京都… 1250041     35.8      140. ＪＲ常磐… 金町駅      2    NA    NA
##  4 g181… 博多餃子… 東京都… 1920904     35.7      139. ＪＲ  八王子駅…     1    NA    NA
##  5 ggww… まさ屋 … 東京都… 1500042     35.7      140. 地下鉄半… 渋谷駅      7    NA    NA
##  6 gdzk… 完全個室… 東京都… 1000013     35.7      140. 地下鉄銀… 虎ノ門駅…     3    NA    NA
##  7 ga2g… 鶏そば … 東京都… 1760006     35.7      140. 西武池袋… 江古田駅…     2    NA    NA
##  8 gg9m… 宴会個室… 東京都… 1010021     35.7      140. ＪＲ  秋葉原駅…     4    NA    NA
##  9 gdvk… 中国料理… 東京都… 1000006     35.7      140. ＪＲ  有楽町駅…     1    NA    NA
## 10 gggb… 中国料理… 東京都… 1140002     35.8      140. 地下鉄南… 王子駅      2    NA    NA
## # … with 6,282 more rows, and 3 more variables: Budget &lt;dbl&gt;, ScoreN &lt;dbl&gt;,
## #   Score &lt;dbl&gt;</code></pre>
<p>1行目の<code># A tibble: 6,292 x 14</code>から、ケース数 (店舗数)は6292、変数は14個あることが分かります。各変数の詳細は以下の通りです。</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
変数名
</th>
<th style="text-align:left;">
説明
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>ID</code>
</td>
<td style="text-align:left;">
店舗ID
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Name</code>
</td>
<td style="text-align:left;">
店舗名
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Pref</code>
</td>
<td style="text-align:left;">
店舗の所在地 (都府県)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Zipcode</code>
</td>
<td style="text-align:left;">
店舗の郵便番号
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Latitude</code>
</td>
<td style="text-align:left;">
緯度
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Longitude</code>
</td>
<td style="text-align:left;">
経度
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Line</code>
</td>
<td style="text-align:left;">
最寄りの駅の路線
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Station</code>
</td>
<td style="text-align:left;">
最寄りの駅
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Walk</code>
</td>
<td style="text-align:left;">
最寄りの駅からの距離 (徒歩; 分)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Bus</code>
</td>
<td style="text-align:left;">
最寄りの駅からの距離 (バス; 分)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Car</code>
</td>
<td style="text-align:left;">
最寄りの駅からの距離 (車; 分)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Budget</code>
</td>
<td style="text-align:left;">
平均予算 (円)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>ScoreN</code>
</td>
<td style="text-align:left;">
口コミの数
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Score</code>
</td>
<td style="text-align:left;">
口コミ評価の平均値
</td>
</tr>
</tbody>
</table>
<p>それではここからは<code>df</code>を用いた<code>dplyr</code>の様々な機能を紹介していきます。</p>
<hr />
</div>
<div id="パイプ演算子" class="section level2">
<h2>パイプ演算子 (<code>%&gt;%</code>)</h2>
<p><code>dplyr</code>パッケージを利用する前にパイプ演算子について説明します。パイプ演算子は<code>dplyr</code>に含まれている演算子ではなく、<code>magrittr</code>という別のパッケージから提供される演算子ですが、<code>tidyverse</code>パッケージを読み込むと自動的に読み込まれます。パイプ演算子は<code>x %&gt;% y()</code>のような書き方となりますが、これは「<code>x</code>を<code>y()</code>の第一引数として渡す」ことを意味します。<code>x</code>の部分はベクトルやデータフレームのようなオブジェクトでも、関数でも構いません。なぜなら、関数から得られた結果もまたベクトルやデータフレームといったものになるからです。つまり、<code>x() %&gt;% y()</code>という使い方も可能です。そして、パイプは無限に繋ぐこともできます。「データ<code>df</code>を関数<code>x()</code>で処理をし、その結果をまた関数<code>y()</code>で処理する」ことは、パイプを使うと<code>df %&gt;% x() %&gt;% y()</code>のような書き方となります。</p>
<p>たとえば、「<code>paste(3, "+", 5, "=", 8)</code>を実行し、その結果を<code>rep()</code>関数を使って3回複製し、それを<code>print()</code>を使って出力する」コードを考えてみましょう。方法としては2つ考えられます。まずは、それぞれの処理を別途のオブジェクトに格納する方法です。そして二つ目は関数の中に関数を使う方法です。</p>
<pre class="r numberLines"><code># 方法1: 一関数一オブジェクト
Result1 &lt;- paste(3, &quot;+&quot;, 5, &quot;=&quot;, 8)
Result2 &lt;- rep(Result1, 3)
print(Result2)</code></pre>
<pre><code>## [1] &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot;</code></pre>
<pre class="r numberLines"><code># 方法2: 関数の中に関数の中に関数
print(rep(paste(3, &quot;+&quot;, 5, &quot;=&quot;, 8), 3))</code></pre>
<pre><code>## [1] &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot;</code></pre>
<p>どれも結果は同じです。コードを書く手間を考えれば、後者の方が楽かも知れませんが、可読性があまりよくありません。一方、前者は可読性は良いものの、コードも長くなり、オブジェクトを2つも作ってしまうのでメモリの無駄遣いになります。</p>
<p>コードの可読性と書く手間、両方を満足する書き方がパイプ演算子<code>%&gt;%</code>です。まずは、例から見ましょう。</p>
<pre class="r"><code># %&gt;%を使う
paste(3, &quot;+&quot;, 5, &quot;=&quot;, 8) %&gt;% rep(3) %&gt;% print()</code></pre>
<pre><code>## [1] &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot; &quot;3 + 5 = 8&quot;</code></pre>
<p>まず、結果は先ほどと同じです。それではコードの説明をしましょう。まずは、<code>paste(3, "+", 5, "=", 8)</code>を実行します。そしてその結果をそのまま<code>rep()</code>関数の第一引数として渡されます。つまり、<code>rep(paste(3, "+", 5, "=", 8), 3)</code>になるわけです。ここでは<code>rep(3)</code>と書きましたが、第一引数が渡されたため、<code>3</code>は第二引数扱いになります (パイプ演算子前のオブジェクトを第二、三引数として渡す方法は適宜説明します。)。そして、これをまた<code>print()</code>関数に渡します。結果としては<code>print(rep(paste(3, "+", 5, "=", 8), 3))</code>となります。</p>
<p>関数を重ねると読む順番は「カッコの内側から外側へ」になりますが、パイプ演算子を使うと「左 (上)から右 (下)へ」といったより自然な読み方が可能になります。また、以下のコードのように、パイプ演算子後に改行を行うことでより読みやすいコードになります。これからはパイプ演算子の後は必ず改行をします。</p>
<pre class="r numberLines"><code># 改行 (+字下げ)したらもっと読みやすくなる
paste(3, &quot;+&quot;, 5, &quot;=&quot;, 8) %&gt;% 
    rep(3) %&gt;% 
    print()</code></pre>
<p>パイプ演算子を使わない方法は図1のようにイメージできます。一回の処理ごとに結果を保存し、それをまた次の処理時においてデータとして使うイメージです。</p>
<div class="figure" style="text-align: center"><span id="fig:pipe1"></span>
<img src="Figures/Handling1/Pipeline1.png" alt="図1. パイプ演算子を使わない場合" width="444" />
<p class="caption">
Figure 1: 図1. パイプ演算子を使わない場合
</p>
</div>
<p>一方、図2はパイプ演算子を使う場合のプロセスです。処理後の結果を保存せず、すぐに次のプロセスに渡すことで、メモリ (図だとボウル)や時間、コードの無駄を減らすことができます。むろん、図<a href="#fig:pipe1">1</a>の結果1を使って色々試してみたい場合は、一旦結果1までは格納し、適宜引き出して使った方が効率的でしょう。パイプ演算子はたしかに便利で、「今どき」のRの書き方を象徴するようなものですが、一つの結果を出すまであまりにも多くのパイプ演算子を使うことはあ望ましくありません。</p>
<div class="figure" style="text-align: center"><span id="fig:pipe2"></span>
<img src="Figures/Handling1/Pipeline2.png" alt="図2. パイプ演算子を使う場合" width="100%" />
<p class="caption">
Figure 2: 図2. パイプ演算子を使う場合
</p>
</div>
<p>データハンドリングもこれど同様に、様々な作業を順に沿って行う必要があります。例えば、「(1) 列を選択して、(2) 欠損値を含む列を除去して、 (3) ある変数の値を100倍にして、(4) ある変数の値がが小さい行から大きい順へ並び替える」といった手順です。これらの作業はパイプ演算子を使えば、スムーズに行うことが可能です。</p>
</div>
<div id="列の抽出" class="section level2">
<h2>列の抽出</h2>
<div id="特定の列を抽出する" class="section level3">
<h3>特定の列を抽出する</h3>
<p>まずは、データフレーム (または、tibble)から特定の列のみを残す、除去する方法について紹介します。たとえば、<code>df</code>から<code>ID</code>、<code>Name</code>、<code>Pref</code>、<code>Score</code>のみを残すとします。<code>dplyr</code>を使わない方法と<code>dplyr</code>の<code>select()</code>関数を使った方法を紹介します。</p>
<pre class="r numberLines"><code># dplyrを使わない方法
df[, c(&quot;ID&quot;, &quot;Name&quot;, &quot;Pref&quot;, &quot;Score&quot;)]</code></pre>
<pre><code>## # A tibble: 6,292 x 4
##    ID      Name                                                     Pref   Score
##    &lt;chr&gt;   &lt;chr&gt;                                                    &lt;chr&gt;  &lt;dbl&gt;
##  1 e539604 居酒屋 龍記 京橋店                                       東京都 NA   
##  2 gfeb600 本格上海料理 新錦江 上野御徒町本店                       東京都  4.5 
##  3 ggt5900 食べ飲み放題×中華ビストロ NOZOMI（のぞみ）               東京都 NA   
##  4 g181340 博多餃子軒 八王子店 タピオカ店 Bull Pulu（ブルプル）併設 東京都 NA   
##  5 ggww100 まさ屋 渋谷店                                            東京都 NA   
##  6 gdzk500 完全個室 上海レストラン 檸檬 霞ヶ関ビル内店              東京都 NA   
##  7 ga2g202 鶏そば きらり                                            東京都 NA   
##  8 gg9m100 宴会個室×餃子酒場 北京飯店 秋葉原本店                    東京都  3.33
##  9 gdvk200 中国料理 宝龍                                            東京都  2.5 
## 10 gggb200 中国料理 天安門                                          東京都 NA   
## # … with 6,282 more rows</code></pre>
<pre class="r numberLines"><code># dplyr::select()を使う方法
# select(df, ID, Name, Pref, Score)でもOK
df %&gt;%
  select(ID, Name, Pref, Score)</code></pre>
<pre><code>## # A tibble: 6,292 x 4
##    ID      Name                                                     Pref   Score
##    &lt;chr&gt;   &lt;chr&gt;                                                    &lt;chr&gt;  &lt;dbl&gt;
##  1 e539604 居酒屋 龍記 京橋店                                       東京都 NA   
##  2 gfeb600 本格上海料理 新錦江 上野御徒町本店                       東京都  4.5 
##  3 ggt5900 食べ飲み放題×中華ビストロ NOZOMI（のぞみ）               東京都 NA   
##  4 g181340 博多餃子軒 八王子店 タピオカ店 Bull Pulu（ブルプル）併設 東京都 NA   
##  5 ggww100 まさ屋 渋谷店                                            東京都 NA   
##  6 gdzk500 完全個室 上海レストラン 檸檬 霞ヶ関ビル内店              東京都 NA   
##  7 ga2g202 鶏そば きらり                                            東京都 NA   
##  8 gg9m100 宴会個室×餃子酒場 北京飯店 秋葉原本店                    東京都  3.33
##  9 gdvk200 中国料理 宝龍                                            東京都  2.5 
## 10 gggb200 中国料理 天安門                                          東京都 NA   
## # … with 6,282 more rows</code></pre>
<p>どれも結果は同じですが、<code>select()</code>関数を使った方がより読みやすいコードになっているでしょう。むろん、<code>select()</code>関数を使わない方がスッキリする方も知るかも知れません。実際、自分でパッケージなどを作成する際は<code>select()</code>を使わない場合が多いです。ただし、一般的な分析の流れでは<code>select()</code>の方がコードも意味も明確となり、パイプ演算子でつなぐのも容易です。</p>
<p><code>select()</code>関数の使い方は非常に簡単です。第一引数はデータフレーム (または、tibble)ですが、パイプ演算子を使う場合は省略可能です。第二引数以降の引数はデータフレーム/tibble内の変数名です。つまり、ここには残す変数名のみを書くだけで十分です。</p>
<p>また、<code>select()</code>関数を使って列の順番を変えることもできます。たとえば、<code>ID</code>、<code>Pref</code>、<code>Name</code>、<code>Score</code>の順で列を残すなら、この順番で引数を書くだけです。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID, Pref, Name)</code></pre>
<pre><code>## # A tibble: 6,292 x 3
##    ID      Pref   Name                                                    
##    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;                                                   
##  1 e539604 東京都 居酒屋 龍記 京橋店                                      
##  2 gfeb600 東京都 本格上海料理 新錦江 上野御徒町本店                      
##  3 ggt5900 東京都 食べ飲み放題×中華ビストロ NOZOMI（のぞみ）              
##  4 g181340 東京都 博多餃子軒 八王子店 タピオカ店 Bull Pulu（ブルプル）併設
##  5 ggww100 東京都 まさ屋 渋谷店                                           
##  6 gdzk500 東京都 完全個室 上海レストラン 檸檬 霞ヶ関ビル内店             
##  7 ga2g202 東京都 鶏そば きらり                                           
##  8 gg9m100 東京都 宴会個室×餃子酒場 北京飯店 秋葉原本店                   
##  9 gdvk200 東京都 中国料理 宝龍                                           
## 10 gggb200 東京都 中国料理 天安門                                         
## # … with 6,282 more rows</code></pre>
</div>
<div id="特定の列を抽出し列名を変更する" class="section level3">
<h3>特定の列を抽出し、列名を変更する</h3>
<p>また、特定の列を残す際、変数名を変更することも可能です。今回も<code>ID</code>、<code>Name</code>、<code>Pref</code>、<code>Score</code>のみを残しますが、<code>Pref</code>列は<code>Prefecture</code>に変えてみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID, Name, Prefecture = Pref, Score)</code></pre>
<pre><code>## # A tibble: 6,292 x 4
##    ID      Name                                                 Prefecture Score
##    &lt;chr&gt;   &lt;chr&gt;                                                &lt;chr&gt;      &lt;dbl&gt;
##  1 e539604 居酒屋 龍記 京橋店                                   東京都     NA   
##  2 gfeb600 本格上海料理 新錦江 上野御徒町本店                   東京都      4.5 
##  3 ggt5900 食べ飲み放題×中華ビストロ NOZOMI（のぞみ）           東京都     NA   
##  4 g181340 博多餃子軒 八王子店 タピオカ店 Bull Pulu（ブルプル）併設… 東京都     NA   
##  5 ggww100 まさ屋 渋谷店                                        東京都     NA   
##  6 gdzk500 完全個室 上海レストラン 檸檬 霞ヶ関ビル内店          東京都     NA   
##  7 ga2g202 鶏そば きらり                                        東京都     NA   
##  8 gg9m100 宴会個室×餃子酒場 北京飯店 秋葉原本店                東京都      3.33
##  9 gdvk200 中国料理 宝龍                                        東京都      2.5 
## 10 gggb200 中国料理 天安門                                      東京都     NA   
## # … with 6,282 more rows</code></pre>
<p>抽出する際、変数を<code>新しい変数名 = 既存の変数名</code>にするだけで、変数名が簡単に変更できました。もし、特定の列は抽出しないものの、変数名を変えるにはどうすれば良いでしょうか。ここでは<code>df</code>の<code>Pref</code>を<code>Prefecture</code>に、<code>Walk</code>を<code>Distance</code>に変更してみます。<code>dplyr</code>を使わない場合と<code>dplyr</code>の<code>rename()</code>関数を使う場合を両方紹介します。</p>
<p>まずは、<code>name()</code>関数についてですが、これはデータフレーム (または、tibble)の変数名をベクトルとして出力する関数です。</p>
<pre class="r numberLines"><code>names(df)</code></pre>
<pre><code>##  [1] &quot;ID&quot;        &quot;Name&quot;      &quot;Pref&quot;      &quot;Zipcode&quot;   &quot;Latitude&quot;  &quot;Longitude&quot;
##  [7] &quot;Line&quot;      &quot;Station&quot;   &quot;Walk&quot;      &quot;Bus&quot;       &quot;Car&quot;       &quot;Budget&quot;   
## [13] &quot;ScoreN&quot;    &quot;Score&quot;</code></pre>
<p>察しの良い読者は気づいたかも知れませんが、<code>names(データフレーム/tibble名)</code>の結果はベクトルであり、上書きも可能です。つまり、<code>names(df)</code>の3番目と9番目の要素を<code>"Prefecture"</code>と<code>"Distance"</code>に上書きすることができるということです。</p>
<pre class="r numberLines"><code># dplyrを使わずに列名を変更する方法
names(df)[c(3, 9)] &lt;- c(&quot;Prefecture&quot;, &quot;Distance&quot;)

# dfの中身を出力
df</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    ID    Name  Prefecture Zipcode Latitude Longitude Line  Station Distance
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1 e539… 居酒屋 … 東京都     1040031     35.7      140. 地下鉄有… 銀座一丁目駅…        3
##  2 gfeb… 本格上海… 東京都     1100005     35.7      140. 地下鉄日… 仲御徒町駅…        1
##  3 ggt5… 食べ飲み… 東京都     1250041     35.8      140. ＪＲ常磐… 金町駅         2
##  4 g181… 博多餃子… 東京都     1920904     35.7      139. ＪＲ  八王子駅…        1
##  5 ggww… まさ屋 … 東京都     1500042     35.7      140. 地下鉄半… 渋谷駅         7
##  6 gdzk… 完全個室… 東京都     1000013     35.7      140. 地下鉄銀… 虎ノ門駅…        3
##  7 ga2g… 鶏そば … 東京都     1760006     35.7      140. 西武池袋… 江古田駅…        2
##  8 gg9m… 宴会個室… 東京都     1010021     35.7      140. ＪＲ  秋葉原駅…        4
##  9 gdvk… 中国料理… 東京都     1000006     35.7      140. ＪＲ  有楽町駅…        1
## 10 gggb… 中国料理… 東京都     1140002     35.8      140. 地下鉄南… 王子駅         2
## # … with 6,282 more rows, and 5 more variables: Bus &lt;dbl&gt;, Car &lt;dbl&gt;,
## #   Budget &lt;dbl&gt;, ScoreN &lt;dbl&gt;, Score &lt;dbl&gt;</code></pre>
<p>簡単に変数名の変更ができました。続いて、<code>dplyr</code>の<code>rename()</code>関数を使った方法です。今回は、<code>Prefecture</code>を<code>Pref</code>に、<code>Distance</code>を<code>Walk</code>に戻して見ましょう。そして、出力するだけにとどまらず、<code>df</code>に上書きしましょう。</p>
<pre class="r numberLines"><code># dfのPrefectureをPrefに、DistanceをWalkに変更し、上書きする
df &lt;- df %&gt;%
  rename(Pref = Prefecture, Walk = Distance)</code></pre>
<p>これで終わりです。実は<code>select()</code>関数と使い方がほぼ同じです。ただし、残す変数名を指定する必要がなく、名前を変更する変数名と新しい変数名を入れるだけです。変数が少ないデータなら<code>select()</code>でもあまり不便は感じないかも知れませんが、変数が多くなると<code>rename()</code>関数は非常に便利です。</p>
</div>
<div id="特定の列を除外する" class="section level3">
<h3>特定の列を除外する</h3>
<p>逆に、一部の変数をデータフレーム (または、tibble)から除去したい場合もあるでしょう。たとえば、緯度 (<code>Latitude</code>)と経度 (<code>Longitude</code>)はラーメン屋の情報としては不要かもしれません。この2つの変数を除外するためにはどうすれば良いでしょうか。まず考えられるのは、この2つの変数を除いた変数を指定・抽出する方法です。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID, Name, Pref, Zipcode, 
         Line, Station, Walk, Bus, Car, Budget, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 6,292 x 12
##    ID    Name  Pref  Zipcode Line  Station  Walk   Bus   Car Budget ScoreN Score
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 e539… 居酒屋 … 東京都… 1040031 地下鉄有… 銀座一丁目駅…     3    NA    NA   3000      0 NA   
##  2 gfeb… 本格上海… 東京都… 1100005 地下鉄日… 仲御徒町駅…     1    NA    NA   2000      2  4.5 
##  3 ggt5… 食べ飲み… 東京都… 1250041 ＪＲ常磐… 金町駅      2    NA    NA   2980      0 NA   
##  4 g181… 博多餃子… 東京都… 1920904 ＪＲ  八王子駅…     1    NA    NA   2000      0 NA   
##  5 ggww… まさ屋 … 東京都… 1500042 地下鉄半… 渋谷駅      7    NA    NA    380      0 NA   
##  6 gdzk… 完全個室… 東京都… 1000013 地下鉄銀… 虎ノ門駅…     3    NA    NA   2980      0 NA   
##  7 ga2g… 鶏そば … 東京都… 1760006 西武池袋… 江古田駅…     2    NA    NA    850      0 NA   
##  8 gg9m… 宴会個室… 東京都… 1010021 ＪＲ  秋葉原駅…     4    NA    NA   2000      3  3.33
##  9 gdvk… 中国料理… 東京都… 1000006 ＪＲ  有楽町駅…     1    NA    NA   1000      2  2.5 
## 10 gggb… 中国料理… 東京都… 1140002 地下鉄南… 王子駅      2    NA    NA   2000      0 NA   
## # … with 6,282 more rows</code></pre>
<p>かなり長いコードになりましたね。しかし、もっと簡単な方法があります。それは<code>-</code>を使う方法です。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(-Latitude, -Longitude) # select(-c(Latitude, Longitude))</code></pre>
<pre><code>## # A tibble: 6,292 x 12
##    ID    Name  Pref  Zipcode Line  Station  Walk   Bus   Car Budget ScoreN Score
##    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 e539… 居酒屋 … 東京都… 1040031 地下鉄有… 銀座一丁目駅…     3    NA    NA   3000      0 NA   
##  2 gfeb… 本格上海… 東京都… 1100005 地下鉄日… 仲御徒町駅…     1    NA    NA   2000      2  4.5 
##  3 ggt5… 食べ飲み… 東京都… 1250041 ＪＲ常磐… 金町駅      2    NA    NA   2980      0 NA   
##  4 g181… 博多餃子… 東京都… 1920904 ＪＲ  八王子駅…     1    NA    NA   2000      0 NA   
##  5 ggww… まさ屋 … 東京都… 1500042 地下鉄半… 渋谷駅      7    NA    NA    380      0 NA   
##  6 gdzk… 完全個室… 東京都… 1000013 地下鉄銀… 虎ノ門駅…     3    NA    NA   2980      0 NA   
##  7 ga2g… 鶏そば … 東京都… 1760006 西武池袋… 江古田駅…     2    NA    NA    850      0 NA   
##  8 gg9m… 宴会個室… 東京都… 1010021 ＪＲ  秋葉原駅…     4    NA    NA   2000      3  3.33
##  9 gdvk… 中国料理… 東京都… 1000006 ＪＲ  有楽町駅…     1    NA    NA   1000      2  2.5 
## 10 gggb… 中国料理… 東京都… 1140002 地下鉄南… 王子駅      2    NA    NA   2000      0 NA   
## # … with 6,282 more rows</code></pre>
<p>除外したい変数名の前に<code>-</code>を付けただけです。また、<code>-Latitude</code>と<code>-Longitude</code>をそれぞれ指定せず、<code>-c(Latitude, Longitude)</code>のように<code>c()</code>でまとめるのも可能です。</p>
</div>
<div id="隣接した列を指定する" class="section level3">
<h3>隣接した列を指定する</h3>
<p>先ほど、<code>df</code>から緯度 (<code>Latitude</code>)と経度 (<code>Longitude</code>)を除外する例を考えてみましょう。<code>-</code>を使うと簡単ですが、場合によっては残す変数名を指定する必要もあります。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID, Name, Pref, Zipcode, 
         Line, Station, Walk, Bus, Car, Budget, ScoreN, Score)</code></pre>
<p>よく考えてみれば、<code>ID</code>から<code>Zipcode</code>は隣接した列ですし、<code>Line</code>から<code>Score</code>までもそうです。これは<code>names()</code>関数で確認できます。</p>
<pre class="r numberLines"><code>names(df)</code></pre>
<pre><code>##  [1] &quot;ID&quot;        &quot;Name&quot;      &quot;Pref&quot;      &quot;Zipcode&quot;   &quot;Latitude&quot;  &quot;Longitude&quot;
##  [7] &quot;Line&quot;      &quot;Station&quot;   &quot;Walk&quot;      &quot;Bus&quot;       &quot;Car&quot;       &quot;Budget&quot;   
## [13] &quot;ScoreN&quot;    &quot;Score&quot;</code></pre>
<p>ここで便利な演算子が<code>:</code>です。これまで、<code>x</code>から<code>y</code>までの公差1の等差数列を作成する際に<code>x:y</code>を使って来ましたが、これに非常に似ています。データフレーム (または、tibble)の「<code>x</code>列から<code>y</code>列まで」の表記も<code>select()</code>関数内では<code>:</code>と書くことができます。したがって、上記のコードは以下のように短縮化可能です。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID:Zipcode, Line:Score)</code></pre>
<p>「<code>df</code>の<code>ID</code>から<code>Zipcode</code>まで、そして<code>Line</code>から<code>Score</code>までの列を選択する」という意味です。非常に便利な演算子ですので、<code>-</code>と合わせて覚えておきましょう。</p>
</div>
<div id="一部の列の順番だけを変える" class="section level3">
<h3>一部の列の順番だけを変える</h3>
<p>ある列の位置を替えたいとします。たとえば、<code>Score</code>と<code>ScoreN</code>をそれぞれ1列目、2列目にしたい場合、どうすれば良いでしょうか。これまで勉強したことを考えると、以下のようなコードで問題ないでしょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(Score, ScoreN, ID:Budget)</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    Score ScoreN ID    Name  Pref  Zipcode Latitude Longitude Line  Station  Walk
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1 NA         0 e539… 居酒屋 … 東京都… 1040031     35.7      140. 地下鉄有… 銀座一丁目駅…     3
##  2  4.5       2 gfeb… 本格上海… 東京都… 1100005     35.7      140. 地下鉄日… 仲御徒町駅…     1
##  3 NA         0 ggt5… 食べ飲み… 東京都… 1250041     35.8      140. ＪＲ常磐… 金町駅      2
##  4 NA         0 g181… 博多餃子… 東京都… 1920904     35.7      139. ＪＲ  八王子駅…     1
##  5 NA         0 ggww… まさ屋 … 東京都… 1500042     35.7      140. 地下鉄半… 渋谷駅      7
##  6 NA         0 gdzk… 完全個室… 東京都… 1000013     35.7      140. 地下鉄銀… 虎ノ門駅…     3
##  7 NA         0 ga2g… 鶏そば … 東京都… 1760006     35.7      140. 西武池袋… 江古田駅…     2
##  8  3.33      3 gg9m… 宴会個室… 東京都… 1010021     35.7      140. ＪＲ  秋葉原駅…     4
##  9  2.5       2 gdvk… 中国料理… 東京都… 1000006     35.7      140. ＪＲ  有楽町駅…     1
## 10 NA         0 gggb… 中国料理… 東京都… 1140002     35.8      140. 地下鉄南… 王子駅      2
## # … with 6,282 more rows, and 3 more variables: Bus &lt;dbl&gt;, Car &lt;dbl&gt;,
## #   Budget &lt;dbl&gt;</code></pre>
<p>しかし、<code>dplyr</code>には<code>relocate()</code>というより便利な専用関数を提供しています。<code>relocate()</code>には変数名を指定するだけですが、ここで指定した変数がデータフレーム (または、tibble)の最初列の方に移動します。</p>
<pre class="r numberLines"><code>df %&gt;%
  relocate(Score, ScoreN)</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    Score ScoreN ID    Name  Pref  Zipcode Latitude Longitude Line  Station  Walk
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1 NA         0 e539… 居酒屋 … 東京都… 1040031     35.7      140. 地下鉄有… 銀座一丁目駅…     3
##  2  4.5       2 gfeb… 本格上海… 東京都… 1100005     35.7      140. 地下鉄日… 仲御徒町駅…     1
##  3 NA         0 ggt5… 食べ飲み… 東京都… 1250041     35.8      140. ＪＲ常磐… 金町駅      2
##  4 NA         0 g181… 博多餃子… 東京都… 1920904     35.7      139. ＪＲ  八王子駅…     1
##  5 NA         0 ggww… まさ屋 … 東京都… 1500042     35.7      140. 地下鉄半… 渋谷駅      7
##  6 NA         0 gdzk… 完全個室… 東京都… 1000013     35.7      140. 地下鉄銀… 虎ノ門駅…     3
##  7 NA         0 ga2g… 鶏そば … 東京都… 1760006     35.7      140. 西武池袋… 江古田駅…     2
##  8  3.33      3 gg9m… 宴会個室… 東京都… 1010021     35.7      140. ＪＲ  秋葉原駅…     4
##  9  2.5       2 gdvk… 中国料理… 東京都… 1000006     35.7      140. ＪＲ  有楽町駅…     1
## 10 NA         0 gggb… 中国料理… 東京都… 1140002     35.8      140. 地下鉄南… 王子駅      2
## # … with 6,282 more rows, and 3 more variables: Bus &lt;dbl&gt;, Car &lt;dbl&gt;,
## #   Budget &lt;dbl&gt;</code></pre>
<p><code>relocate()</code>を使うと<code>ID:Budget</code>が省略可能となり、より短いコードになります。もう一つの例は、最初に持ってくるのではなく、「ある変数の前」または「ある変数の後」に移動させるケースです。これも<code>relocate()</code>で可能ですが、もう一つの引数が必要です。<code>Pref</code>と<code>Zipcdoe</code>の順番を変えるなら、まずは以下のような方法が考えられます。</p>
<pre class="r numberLines"><code>df %&gt;%
  select(ID:Name, Zipcode, Pref, Latitude:Score)</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    ID    Name  Zipcode Pref  Latitude Longitude Line  Station  Walk   Bus   Car
##    &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 e539… 居酒屋 … 1040031 東京都…     35.7      140. 地下鉄有… 銀座一丁目駅…     3    NA    NA
##  2 gfeb… 本格上海… 1100005 東京都…     35.7      140. 地下鉄日… 仲御徒町駅…     1    NA    NA
##  3 ggt5… 食べ飲み… 1250041 東京都…     35.8      140. ＪＲ常磐… 金町駅      2    NA    NA
##  4 g181… 博多餃子… 1920904 東京都…     35.7      139. ＪＲ  八王子駅…     1    NA    NA
##  5 ggww… まさ屋 … 1500042 東京都…     35.7      140. 地下鉄半… 渋谷駅      7    NA    NA
##  6 gdzk… 完全個室… 1000013 東京都…     35.7      140. 地下鉄銀… 虎ノ門駅…     3    NA    NA
##  7 ga2g… 鶏そば … 1760006 東京都…     35.7      140. 西武池袋… 江古田駅…     2    NA    NA
##  8 gg9m… 宴会個室… 1010021 東京都…     35.7      140. ＪＲ  秋葉原駅…     4    NA    NA
##  9 gdvk… 中国料理… 1000006 東京都…     35.7      140. ＪＲ  有楽町駅…     1    NA    NA
## 10 gggb… 中国料理… 1140002 東京都…     35.8      140. 地下鉄南… 王子駅      2    NA    NA
## # … with 6,282 more rows, and 3 more variables: Budget &lt;dbl&gt;, ScoreN &lt;dbl&gt;,
## #   Score &lt;dbl&gt;</code></pre>
<p>これを<code>relocate()</code>で書き換えるなら、<code>.after</code>または<code>.before</code>引数が必要になります。<code>relocate(変数名1, .after = 変数名2)</code>は「変数1を変数2の直後に移動させる」
ことを意味します。</p>
<pre class="r numberLines"><code>df %&gt;%
  relocate(Pref, .after = Zipcode)</code></pre>
<pre><code>## # A tibble: 6,292 x 14
##    ID    Name  Zipcode Pref  Latitude Longitude Line  Station  Walk   Bus   Car
##    &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 e539… 居酒屋 … 1040031 東京都…     35.7      140. 地下鉄有… 銀座一丁目駅…     3    NA    NA
##  2 gfeb… 本格上海… 1100005 東京都…     35.7      140. 地下鉄日… 仲御徒町駅…     1    NA    NA
##  3 ggt5… 食べ飲み… 1250041 東京都…     35.8      140. ＪＲ常磐… 金町駅      2    NA    NA
##  4 g181… 博多餃子… 1920904 東京都…     35.7      139. ＪＲ  八王子駅…     1    NA    NA
##  5 ggww… まさ屋 … 1500042 東京都…     35.7      140. 地下鉄半… 渋谷駅      7    NA    NA
##  6 gdzk… 完全個室… 1000013 東京都…     35.7      140. 地下鉄銀… 虎ノ門駅…     3    NA    NA
##  7 ga2g… 鶏そば … 1760006 東京都…     35.7      140. 西武池袋… 江古田駅…     2    NA    NA
##  8 gg9m… 宴会個室… 1010021 東京都…     35.7      140. ＪＲ  秋葉原駅…     4    NA    NA
##  9 gdvk… 中国料理… 1000006 東京都…     35.7      140. ＪＲ  有楽町駅…     1    NA    NA
## 10 gggb… 中国料理… 1140002 東京都…     35.8      140. 地下鉄南… 王子駅      2    NA    NA
## # … with 6,282 more rows, and 3 more variables: Budget &lt;dbl&gt;, ScoreN &lt;dbl&gt;,
## #   Score &lt;dbl&gt;</code></pre>
<p><code>.before</code>を使うことできます。この場合は「<code>Zipcode</code>を<code>Pref</code>の直前に移動させる」
ことを指定する必要があります。結果は省略しますが、自分でコードを走らせ、上と同じ結果が得られるかを確認してみてください。</p>
<pre class="r numberLines"><code>df %&gt;%
  relocate(Zipcode, .before = Pref)</code></pre>
</div>
<div id="selectの便利な機能" class="section level3">
<h3><code>select()</code>の便利な機能</h3>
<p><code>select()</code>関数は他にも便利な機能がいくつかあります。ここではいくつの機能を紹介しますが、より詳しい内容は<code>?dplyr::select</code>を参照してください。</p>
<p><strong><code>starts_with()</code>と<code>ends_with()</code>、<code>contains()</code>、<code>num_range()</code>: 特定の文字を含む変数を選択する</strong></p>
<p>まずは、特定の文字を含む変数名を指定する方法です。<code>starts_with("X")</code>、<code>ends_with("X")</code>、<code>contains("X")</code>は変数名が<code>"X"</code>で始まるか、<code>"X"</code>で終わるか、<code>"X"</code>を含むかを判断し、条件に合う変数名を返す関数です。実際の例を見ましょう。</p>
<pre class="r numberLines"><code># ID、Nameに続いて、Scoreで始まる変数名を抽出
df %&gt;%
  select(ID, Name, starts_with(&quot;Score&quot;))</code></pre>
<pre><code>## # A tibble: 6,292 x 4
##    ID      Name                                                     ScoreN Score
##    &lt;chr&gt;   &lt;chr&gt;                                                     &lt;dbl&gt; &lt;dbl&gt;
##  1 e539604 居酒屋 龍記 京橋店                                            0 NA   
##  2 gfeb600 本格上海料理 新錦江 上野御徒町本店                            2  4.5 
##  3 ggt5900 食べ飲み放題×中華ビストロ NOZOMI（のぞみ）                    0 NA   
##  4 g181340 博多餃子軒 八王子店 タピオカ店 Bull Pulu（ブルプル）併設      0 NA   
##  5 ggww100 まさ屋 渋谷店                                                 0 NA   
##  6 gdzk500 完全個室 上海レストラン 檸檬 霞ヶ関ビル内店                   0 NA   
##  7 ga2g202 鶏そば きらり                                                 0 NA   
##  8 gg9m100 宴会個室×餃子酒場 北京飯店 秋葉原本店                         3  3.33
##  9 gdvk200 中国料理 宝龍                                                 2  2.5 
## 10 gggb200 中国料理 天安門                                               0 NA   
## # … with 6,282 more rows</code></pre>
<pre class="r numberLines"><code># eで終わる変数名を除去
df %&gt;%
  select(-ends_with(&quot;e&quot;)) # !ends_with(&quot;e&quot;)も可能</code></pre>
<pre><code>## # A tibble: 6,292 x 8
##    ID      Pref   Station       Walk   Bus   Car Budget ScoreN
##    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 e539604 東京都 銀座一丁目駅     3    NA    NA   3000      0
##  2 gfeb600 東京都 仲御徒町駅       1    NA    NA   2000      2
##  3 ggt5900 東京都 金町駅           2    NA    NA   2980      0
##  4 g181340 東京都 八王子駅         1    NA    NA   2000      0
##  5 ggww100 東京都 渋谷駅           7    NA    NA    380      0
##  6 gdzk500 東京都 虎ノ門駅         3    NA    NA   2980      0
##  7 ga2g202 東京都 江古田駅         2    NA    NA    850      0
##  8 gg9m100 東京都 秋葉原駅         4    NA    NA   2000      3
##  9 gdvk200 東京都 有楽町駅         1    NA    NA   1000      2
## 10 gggb200 東京都 王子駅           2    NA    NA   2000      0
## # … with 6,282 more rows</code></pre>
<pre class="r numberLines"><code># reを含む変数名を抽出するが、ScoreNは除去する
df %&gt;%
  select(contains(&quot;re&quot;), -ScoreN)</code></pre>
<pre><code>## # A tibble: 6,292 x 2
##    Pref   Score
##    &lt;chr&gt;  &lt;dbl&gt;
##  1 東京都 NA   
##  2 東京都  4.5 
##  3 東京都 NA   
##  4 東京都 NA   
##  5 東京都 NA   
##  6 東京都 NA   
##  7 東京都 NA   
##  8 東京都  3.33
##  9 東京都  2.5 
## 10 東京都 NA   
## # … with 6,282 more rows</code></pre>
<p>他の使い方としては<code>X1</code>、<code>X2</code>のような「文字+数字」の変数を選択する際、<code>starts_with()</code>が活躍します。たとえば、以下のような<code>myDF1</code>があるとします。</p>
<pre class="r numberLines"><code># tibble()の代わりにdata.frame()も使用可能
myDF1 &lt;- tibble(
  ID  = 1:5,
  X1  = c(2, 4, 6, 2, 7),
  Y1  = c(3, 5, 1, 1, 0),
  X1D = c(4, 2, 1, 6, 9),
  X2  = c(5, 5, 6, 0, 2),
  Y2  = c(3, 3, 2, 3, 1),
  X2D = c(8, 9, 5, 0, 1),
  X3  = c(3, 0, 3, 0, 2),
  Y3  = c(1, 5, 9, 1, 3),
  X3D = c(9, 1, 3, 3, 8)
)

myDF1</code></pre>
<pre><code>## # A tibble: 5 x 10
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9
## 2     2     4     5     2     5     3     9     0     5     1
## 3     3     6     1     1     6     2     5     3     9     3
## 4     4     2     1     6     0     3     0     0     1     3
## 5     5     7     0     9     2     1     1     2     3     8</code></pre>
<p>この<code>myDF1</code>から<code>ID</code>、<code>Y1</code>、<code>Y2</code>、<code>Y3</code>を抽出するにはどうすれば良いでしょうか。これらの変数は隣接していないため、<code>:</code>も使えませんが、<code>starts_with()</code>を使えば簡単です。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  select(ID, starts_with(&quot;Y&quot;))</code></pre>
<pre><code>## # A tibble: 5 x 4
##      ID    Y1    Y2    Y3
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     3     3     1
## 2     2     5     3     5
## 3     3     1     2     9
## 4     4     1     3     1
## 5     5     0     1     3</code></pre>
<p>それでは、<code>ID</code>、<code>X1</code>、<code>X2</code>、<code>X3</code>はどうでしょうか。<code>starts_with("X")</code>だと、<code>X1c</code>なども選択されてしまいますね。ここで<code>-ends_with()</code>の出番です。つまり、「まずは<code>starts_with("X")</code>で<code>X</code>で始まる変数を選択し、続いて、<code>D</code>で終わるものを除外すればいいじゃん？」です。それでは、やってみましょうか。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  select(ID, starts_with(&quot;X&quot;), -ends_with(&quot;D&quot;))</code></pre>
<pre><code>## # A tibble: 5 x 3
##      X1    X2    X3
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     2     5     3
## 2     4     5     0
## 3     6     6     3
## 4     2     0     0
## 5     7     2     2</code></pre>
<p>あらら、<code>ID</code>も同時になくなりましたね<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>。実はこのような時のために用意された関数があり、それが<code>num_range()</code>です。<code>num_range()</code>の第一引数は<code>starts_with()</code>関数と同じですが、第二引数も必要です。この第二引数にはnumeric型のベクトルが必要です。<code>1:3</code>でも、<code>c(1, 2, 3)</code>でも構いません。たとえば、<code>ID</code>、<code>X1</code>、<code>X2</code>、<code>X3</code>するには以下のように書きます。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  select(ID, num_range(&quot;X&quot;, 1:3))</code></pre>
<pre><code>## # A tibble: 5 x 4
##      ID    X1    X2    X3
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2     5     3
## 2     2     4     5     0
## 3     3     6     6     3
## 4     4     2     0     0
## 5     5     7     2     2</code></pre>
<p>ぱっぱらぱー！</p>
<p><strong><code>all_of()</code>と<code>any_of()</code>: 文字型ベクトルを用いた変数の選択</strong></p>
<p><code>all_of()</code>と<code>any_of()</code>は<code>select()</code>内の変数名として文字型ベクトルを使う際に用いる関数です。これは抽出したい列名が既にcharacter型ベクトルとして用意されている場合、便利な関数です。たとえば、以下の<code>Name_Vec</code>を考えてみましょう。</p>
<pre class="r numberLines"><code>Name_Vec &lt;- c(&quot;X1&quot;, &quot;X2&quot;, &quot;X3&quot;)</code></pre>
<p>この<code>Name_Vec</code>の要素と同じ列名を持つ列と<code>ID</code>列を<code>myDF1</code>から抽出する方法は以下の2通りです。</p>
<pre class="r numberLines"><code>myDF1[, c(&quot;ID&quot;, Name_Vec)]</code></pre>
<pre><code>## # A tibble: 5 x 4
##      ID    X1    X2    X3
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2     5     3
## 2     2     4     5     0
## 3     3     6     6     3
## 4     4     2     0     0
## 5     5     7     2     2</code></pre>
<pre class="r numberLines"><code>myDF1 %&gt;%
  select(ID, all_of(Name_Vec))</code></pre>
<pre><code>## # A tibble: 5 x 4
##      ID    X1    X2    X3
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2     5     3
## 2     2     4     5     0
## 3     3     6     6     3
## 4     4     2     0     0
## 5     5     7     2     2</code></pre>
<p>今の例だと、<code>select()</code>を使わない前者の方が便利かも知れませんが、<code>select()</code>内に外の変数名も指定する場合も多いので、後者の方が汎用性は高いです。私から見れば、今の例でも後者の方が読みやすく、使いやすいと思います。</p>
<p>それでは以下のような<code>Name_Vec</code>はどうでしょう。今回は、<code>myDF1</code>に含まれていない<code>X4</code>と<code>X5</code>もあります。</p>
<pre class="r numberLines"><code>Name_Vec &lt;- c(&quot;X1&quot;, &quot;X2&quot;, &quot;X3&quot;, &quot;X4&quot;, &quot;X5&quot;)

myDF1 %&gt;%
  select(all_of(Name_Vec))</code></pre>
<pre><code>## Error: Can&#39;t subset columns that don&#39;t exist.
## [31mx[39m Columns `X4` and `X5` don&#39;t exist.</code></pre>
<p>このようにエラーが出てしまします。つまり、<code>all_of()</code>の場合、引数の要素全てがデータフレーム (または、tibble)に存在する必要があります。もし、ないものは無視して、合致する列だけ取り出したいはどうすれば良いでしょうか。そこで登場するのが<code>any_of()</code>です。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  select(any_of(Name_Vec))</code></pre>
<pre><code>## # A tibble: 5 x 3
##      X1    X2    X3
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     2     5     3
## 2     4     5     0
## 3     6     6     3
## 4     2     0     0
## 5     7     2     2</code></pre>
<p><code>any_of()</code>の方がより使いやすいと思う方も多いでしょうが、必ずしもそうとは限りません。たとえば、<code>Name_Vec</code>に誤字などが含まれる場合、<code>any_of()</code>だと誤字が含まれている変数は取り出しません。この場合はむしろちゃんとエラーを表示してくれた方が嬉しいですね。</p>
<p><strong><code>last_col()</code>: 最後の列を選択する</strong></p>
<p>普段あまり使わない機能ですが、最後の列を選択する<code>last_col()</code>という関数もあります。たとえば、<code>last_col(0)</code>にすると最後の列を選択し、<code>last_col(1)</code>なら最後から2番目の列を選択します。たとえば、<code>df</code>から<code>ID</code>と最後の列を取り出してみましょう。</p>
<pre class="r numberLines"><code># IDと最後の列のみを抽出
df %&gt;%
  select(ID, last_col(0))</code></pre>
<pre><code>## # A tibble: 6,292 x 2
##    ID      Score
##    &lt;chr&gt;   &lt;dbl&gt;
##  1 e539604 NA   
##  2 gfeb600  4.5 
##  3 ggt5900 NA   
##  4 g181340 NA   
##  5 ggww100 NA   
##  6 gdzk500 NA   
##  7 ga2g202 NA   
##  8 gg9m100  3.33
##  9 gdvk200  2.5 
## 10 gggb200 NA   
## # … with 6,282 more rows</code></pre>
<p>最後の2行分を取り出すことも可能です。この場合は<code>last_col()</code>の引数を長さ1ベクトルでなく、長さ2以上のベクトルにします。最後の行が<code>0</code>、その手前の行が<code>1</code>ですから、中の引数は<code>1:0</code>となります。<code>0:1</code>でも可能ですが、結果が若干異なります。</p>
<pre class="r numberLines"><code># IDと最後の2列分を抽出 (引数を1:0と設定)
df %&gt;%
  select(ID, last_col(1:0))</code></pre>
<pre><code>## # A tibble: 6,292 x 3
##    ID      ScoreN Score
##    &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt;
##  1 e539604      0 NA   
##  2 gfeb600      2  4.5 
##  3 ggt5900      0 NA   
##  4 g181340      0 NA   
##  5 ggww100      0 NA   
##  6 gdzk500      0 NA   
##  7 ga2g202      0 NA   
##  8 gg9m100      3  3.33
##  9 gdvk200      2  2.5 
## 10 gggb200      0 NA   
## # … with 6,282 more rows</code></pre>
<pre class="r numberLines"><code># IDと最後の2列分を抽出 (引数を0:1と設定)
df %&gt;%
  select(ID, last_col(0:1))</code></pre>
<pre><code>## # A tibble: 6,292 x 3
##    ID      Score ScoreN
##    &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;
##  1 e539604 NA         0
##  2 gfeb600  4.5       2
##  3 ggt5900 NA         0
##  4 g181340 NA         0
##  5 ggww100 NA         0
##  6 gdzk500 NA         0
##  7 ga2g202 NA         0
##  8 gg9m100  3.33      3
##  9 gdvk200  2.5       2
## 10 gggb200 NA         0
## # … with 6,282 more rows</code></pre>
<p><code>last_col()</code>の引数を<code>1:0</code>にするか<code>0:1</code>にするかによって抽出される順番が異なります。<code>1:0</code>は<code>c(1, 0)</code>、<code>0:1</code>は<code>c(0, 1)</code>と同じであることを考えると理由は簡単です。<code>c(1, 0)</code>の場合、<code>last_col(1), last_col(0)</code>の順番で処理をし、<code>c(0, 1)</code>は<code>last_col(0)</code>、<code>last_col(1)</code>の順番で処理を行うからです。</p>
<p>この<code>last_col()</code>の引数を空っぽにするとそれは最後の列を意味します。これを利用すれば、「ある変数の最後の列へ移動させる」こともできます。たとえば、<code>ID</code>を最後の列に移動させたい場合、<code>relocate(ID, .after = last_col())</code>のように書きます。</p>
<p><strong><code>where()</code>: データ型から変数を選択する</strong></p>
<p>最後に、「numeric型の列のみ抽出したい」、「character型の列だけほしい」場合に便利な<code>where()</code>関数を紹介します。<code>where()</code>の中に入る引数は一つだけであり、データ型を判定する関数名が入ります。たとえば、numeric型か否かを判断する関数は<code>is.numeric</code>です。<code>df</code>からnumeric型の変数のみを抽出したい場合は以下のように書きます。</p>
<pre class="r numberLines"><code># numeric型の列を抽出する
df %&gt;%
  select(where(is.numeric))</code></pre>
<pre><code>## # A tibble: 6,292 x 9
##    Zipcode Latitude Longitude  Walk   Bus   Car Budget ScoreN Score
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 1040031     35.7      140.     3    NA    NA   3000      0 NA   
##  2 1100005     35.7      140.     1    NA    NA   2000      2  4.5 
##  3 1250041     35.8      140.     2    NA    NA   2980      0 NA   
##  4 1920904     35.7      139.     1    NA    NA   2000      0 NA   
##  5 1500042     35.7      140.     7    NA    NA    380      0 NA   
##  6 1000013     35.7      140.     3    NA    NA   2980      0 NA   
##  7 1760006     35.7      140.     2    NA    NA    850      0 NA   
##  8 1010021     35.7      140.     4    NA    NA   2000      3  3.33
##  9 1000006     35.7      140.     1    NA    NA   1000      2  2.5 
## 10 1140002     35.8      140.     2    NA    NA   2000      0 NA   
## # … with 6,282 more rows</code></pre>
<p><code>!</code>を使って条件に合致する列を除外することも可能です。もし、character型の列を除外する場合は以下のように<code>!where(is.character)</code>を指定します。</p>
<pre class="r numberLines"><code># character型でない列を抽出する
df %&gt;%
  select(!where(is.character))</code></pre>
<pre><code>## # A tibble: 6,292 x 9
##    Zipcode Latitude Longitude  Walk   Bus   Car Budget ScoreN Score
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 1040031     35.7      140.     3    NA    NA   3000      0 NA   
##  2 1100005     35.7      140.     1    NA    NA   2000      2  4.5 
##  3 1250041     35.8      140.     2    NA    NA   2980      0 NA   
##  4 1920904     35.7      139.     1    NA    NA   2000      0 NA   
##  5 1500042     35.7      140.     7    NA    NA    380      0 NA   
##  6 1000013     35.7      140.     3    NA    NA   2980      0 NA   
##  7 1760006     35.7      140.     2    NA    NA    850      0 NA   
##  8 1010021     35.7      140.     4    NA    NA   2000      3  3.33
##  9 1000006     35.7      140.     1    NA    NA   1000      2  2.5 
## 10 1140002     35.8      140.     2    NA    NA   2000      0 NA   
## # … with 6,282 more rows</code></pre>
<p><code>&amp;</code>を使って複数の条件を使うことも可能です。たとえば、<code>ID</code>変数に加えて「<code>"L"</code>で始まる変数の中でnumeric型の列を抽出」するコードは以下のようになります。</p>
<pre class="r numberLines"><code># IDと、Lで始まるnumeric型の列を抽出する
df %&gt;%
  select(ID, starts_with(&quot;L&quot;) &amp; where(is.numeric))</code></pre>
<pre><code>## # A tibble: 6,292 x 3
##    ID      Latitude Longitude
##    &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 e539604     35.7      140.
##  2 gfeb600     35.7      140.
##  3 ggt5900     35.8      140.
##  4 g181340     35.7      139.
##  5 ggww100     35.7      140.
##  6 gdzk500     35.7      140.
##  7 ga2g202     35.7      140.
##  8 gg9m100     35.7      140.
##  9 gdvk200     35.7      140.
## 10 gggb200     35.8      140.
## # … with 6,282 more rows</code></pre>
<hr />
</div>
</div>
<div id="行の抽出" class="section level2">
<h2>行の抽出</h2>
<p>他にも特定の行を抽出する場合があります。多くの場合、「何かの条件と合致するケースのみ抽出する」または、「何かの条件と合致しないケースのみを抽出する」やこれらの組み合わせで行の抽出を行います。そこで登場するのが<code>dplyr()</code>パッケージの<code>filter()</code>関数です。<code>filter()</code>関数の使い方は以下の通りです。</p>
<pre class="r numberLines"><code># dplyr::filter()の使い方
filter(データフレーム/tibble名, 条件1, 条件2, ...)</code></pre>
<p>むろん、第一引数がデータですから、<code>%&gt;%</code>を使うことも可能です。</p>
<pre class="r numberLines"><code># dplyr::filter()の使い方 (パイプを使う方法)
データフレーム/tibble名 %&gt;%
  filter(条件1, 条件2, ...)</code></pre>
<p>まずは、条件が一つの場合を考えてみましょう。ここでは「<code>Pref</code>が<code>"京都府"</code>であるケースのみに絞り、<code>Name</code>と<code>Station</code>、<code>Score</code>列のみを出力する」ケースを考えてみましょう。まず、<code>filter()</code>関数で行を抽出し、続いて<code>select()</code>関数で抽出する列を指定します。むろん、今回の場合、<code>filter()</code>と<code>select()</code>の順番は替えても構いません。</p>
<pre class="r numberLines"><code># dfからPrefが&quot;京都府&quot;であるケースのみ残し、df2という名で保存
df2 &lt;- df %&gt;%
  filter(Pref == &quot;京都府&quot;)

# df2からName, Station, Score列を抽出
df2 %&gt;%
  select(Name, Station, Score)</code></pre>
<pre><code>## # A tibble: 414 x 3
##    Name                                                    Station    Score
##    &lt;chr&gt;                                                   &lt;chr&gt;      &lt;dbl&gt;
##  1 中国料理 鳳麟                                           くいな橋駅 NA   
##  2 黒毛和牛一頭買い焼肉と 炊き立て土鍋ご飯 市場小路 烏丸店 四条駅      3.19
##  3 京の中華 ハマムラ みやこみち店                          京都駅     NA   
##  4 焼肉処 真 桂店                                          桂駅       NA   
##  5 祇園京都ラーメン                                        祇園四条駅 NA   
##  6 創作料理 串カツ トンカツ jiro                           新田辺駅   NA   
##  7 祇園 晩餐のあと                                         祇園四条駅 NA   
##  8 DETAIL                                                  東山駅     NA   
##  9 めんや龍神                                              北大路駅   NA   
## 10 無尽蔵 京都八条家                                       京都駅      3.5 
## # … with 404 more rows</code></pre>
<p>これは<code>df</code>から<code>Pref == "京都府"</code>のケースのみ残したものを<code>df2</code>として格納し、それをまた<code>select()</code>関数を使って列を抽出するコードです。これでも問題ありませんが、これだとパイプ演算子の便利さが分かりません。パイプ演算子は複数使うことが可能です。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;京都府&quot;) %&gt;%
  select(Name, Station, Score)</code></pre>
<pre><code>## # A tibble: 414 x 3
##    Name                                                    Station    Score
##    &lt;chr&gt;                                                   &lt;chr&gt;      &lt;dbl&gt;
##  1 中国料理 鳳麟                                           くいな橋駅 NA   
##  2 黒毛和牛一頭買い焼肉と 炊き立て土鍋ご飯 市場小路 烏丸店 四条駅      3.19
##  3 京の中華 ハマムラ みやこみち店                          京都駅     NA   
##  4 焼肉処 真 桂店                                          桂駅       NA   
##  5 祇園京都ラーメン                                        祇園四条駅 NA   
##  6 創作料理 串カツ トンカツ jiro                           新田辺駅   NA   
##  7 祇園 晩餐のあと                                         祇園四条駅 NA   
##  8 DETAIL                                                  東山駅     NA   
##  9 めんや龍神                                              北大路駅   NA   
## 10 無尽蔵 京都八条家                                       京都駅      3.5 
## # … with 404 more rows</code></pre>
<p>全く同じ結果ですが、無駄に<code>df2</code>というデータフレーム (または、tibble)を作らず済むので、メモリの観点からも嬉しいですし、何よりコードが短く、しかも可読性も上がりました。</p>
<p>今回は<code>==</code>を使って<strong>合致する</strong>ものに絞りましたが、<code>!=</code>を使って<strong>合致しない</strong>ものに絞ることも可能です。または、比較演算子 (<code>&lt;</code>、<code>&gt;</code>、<code>&gt;=</code>、<code>&lt;=</code>など)を使うことも可能です。それでは、組み込み数 (<code>ScoreN</code>)が<em>0ではない</em>ケースを取り出し、<code>Name</code>、<code>Station</code>、<code>ScoreN</code>、<code>Score</code>列を出力させてみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(ScoreN != 0) %&gt;%
  select(Name, Station, starts_with(&quot;Score&quot;))</code></pre>
<pre><code>## # A tibble: 1,344 x 4
##    Name                                             Station         ScoreN Score
##    &lt;chr&gt;                                            &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt;
##  1 本格上海料理 新錦江 上野御徒町本店               仲御徒町駅           2  4.5 
##  2 宴会個室×餃子酒場 北京飯店 秋葉原本店            秋葉原駅             3  3.33
##  3 中国料理 宝龍                                    有楽町駅             2  2.5 
##  4 麺達 うま家                                      高田馬場駅           2  3   
##  5 刀削麺・火鍋・西安料理 XI’AN（シーアン） 後楽園店… 後楽園駅             1 NA   
##  6 七志らーめん 渋谷道玄坂店                        渋谷駅               7  4.5 
##  7 永楽                                             京成小岩駅           6  4.42
##  8 よってこや お台場店                              お台場海浜公園駅…      1  4   
##  9 ラーメン武藤製麺所                               竹ノ塚駅             4  3.5 
## 10 桂花ラーメン 新宿末広店                          新宿三丁目駅         8  3   
## # … with 1,334 more rows</code></pre>
<p>これで口コミ数が1以上の店舗のみに絞ることができました。ただし、店によっては口コミはあっても、評価 (<code>Score</code>)が付いていないところもあります。たとえば、「刀削麺・火鍋・西安料理 XI’AN（シーアン） 後楽園店」の場合、口コミはありますが、評価はありません。したがって、今回は評価が付いている店舗に絞ってみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Score != NA) %&gt;%
  select(Name, Station, starts_with(&quot;Score&quot;))</code></pre>
<pre><code>## # A tibble: 0 x 4
## # … with 4 variables: Name &lt;chr&gt;, Station &lt;chr&gt;, ScoreN &lt;dbl&gt;, Score &lt;dbl&gt;</code></pre>
<p>あらら、何の結果も表示されませんでした。これは<code>filter()</code>内の条件に合致するケースが存在しないことを意味します。しかし、先ほどの結果を見ても、評価が付いている店はいっぱいありましたね。これはなぜでしょう。</p>
<p>察しの良い読者さんは気づいているかと思いますが、<code>NA</code>か否かを判定する際は<code>==</code>や<code>!=</code>は使えません。<code>is.na()</code>を使います。<code>filter(is.na(Score))</code>なら「<code>Score</code>が<code>NA</code><strong>である</strong>ケースに絞る」ことを意味しますが、今回は「<code>Score</code>が<code>NA</code><strong>でない</strong>ケースに絞る」ことが目的ですので、<code>is.na()</code>の前に<code>!</code>を付けます。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Score)) %&gt;%
  select(Name, Station, starts_with(&quot;Score&quot;))</code></pre>
<pre><code>## # A tibble: 1,134 x 4
##    Name                                  Station          ScoreN Score
##    &lt;chr&gt;                                 &lt;chr&gt;             &lt;dbl&gt; &lt;dbl&gt;
##  1 本格上海料理 新錦江 上野御徒町本店    仲御徒町駅            2  4.5 
##  2 宴会個室×餃子酒場 北京飯店 秋葉原本店 秋葉原駅              3  3.33
##  3 中国料理 宝龍                         有楽町駅              2  2.5 
##  4 麺達 うま家                           高田馬場駅            2  3   
##  5 七志らーめん 渋谷道玄坂店             渋谷駅                7  4.5 
##  6 永楽                                  京成小岩駅            6  4.42
##  7 よってこや お台場店                   お台場海浜公園駅      1  4   
##  8 ラーメン武藤製麺所                    竹ノ塚駅              4  3.5 
##  9 桂花ラーメン 新宿末広店               新宿三丁目駅          8  3   
## 10 北斗 新橋店                           新橋駅                4  2.5 
## # … with 1,124 more rows</code></pre>
<p>これで口コミ評価が登録された店舗に絞ることができました。</p>
<p>続いて、複数の条件を持つケースを考えてみましょう。例えば、「京都府内の店舗で、口コミ評価が3.5以上の店舗」を出力したい場合、以下のようなコードとなります。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;京都府&quot;, Score &gt;= 3.5) %&gt;%
  select(Name, Station, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 53 x 4
##    Name               Station    ScoreN Score
##    &lt;chr&gt;              &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 無尽蔵 京都八条家  京都駅          2  3.5 
##  2 一蘭 京都河原町店  河原町駅        2  3.75
##  3 ミスター・ギョーザ 西大路駅        8  4.06
##  4 一蘭 京都八幡店    樟葉駅          3  4   
##  5 中華料理 清華園    京都駅          3  5   
##  6 まがり             &lt;NA&gt;            2  4   
##  7 魁力屋 北山店      北大路駅        2  4.25
##  8 大中BAL横店        &lt;NA&gt;            7  4.1 
##  9 こうちゃん         西舞鶴駅        1  5   
## 10 大黒ラーメン       伏見桃山駅      4  4.25
## # … with 43 more rows</code></pre>
<p>条件を<code>filter()</code>内に追加するだけです。今回は<code>!is.na(Score)</code>は不要です。なぜなら、<code>Score &gt;= 3.5</code>という条件で既に欠損値は対象外になるからです。条件文が複数ある場合、ANDかORかを指定する必要があります。つまり、条件文AとBがある場合、「AとB両方満たすものを出力する」か「AとBどちらかを満たすものを出力するか」を指定する必要があります。今の結果ってANDでしたよね。<code>filter()</code>関数は、別途の指定がない場合、全てAND扱いになります。RのAND演算子は<code>&amp;</code>ですので、以上のコードは以下のコードと同じです。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;京都府&quot; &amp; Score &gt;= 3.5) %&gt;%
  select(Name, Station, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 53 x 4
##    Name               Station    ScoreN Score
##    &lt;chr&gt;              &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 無尽蔵 京都八条家  京都駅          2  3.5 
##  2 一蘭 京都河原町店  河原町駅        2  3.75
##  3 ミスター・ギョーザ 西大路駅        8  4.06
##  4 一蘭 京都八幡店    樟葉駅          3  4   
##  5 中華料理 清華園    京都駅          3  5   
##  6 まがり             &lt;NA&gt;            2  4   
##  7 魁力屋 北山店      北大路駅        2  4.25
##  8 大中BAL横店        &lt;NA&gt;            7  4.1 
##  9 こうちゃん         西舞鶴駅        1  5   
## 10 大黒ラーメン       伏見桃山駅      4  4.25
## # … with 43 more rows</code></pre>
<p>AND演算子 (<code>&amp;</code>)が使えるということはOR演算子 (<code>|</code>)も使えることを意味します。たとえば、<code>Station</code>が<code>"高田馬場駅"</code>か<code>"三田駅"</code>の条件を指定したい場合、</p>
<pre class="r numberLines"><code>df %&gt;% 
  filter(Station == &quot;高田馬場駅&quot; | Station == &quot;三田駅&quot;) %&gt;%
  select(Name, Station, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 14 x 4
##    Name                                 Station    ScoreN Score
##    &lt;chr&gt;                                &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 麺達 うま家                          高田馬場駅      2  3   
##  2 らぁ麺 やまぐち                      高田馬場駅      7  4.08
##  3 博多一瑞亭 三田店                    三田駅          0 NA   
##  4 つけ麺屋 ひまわり                    高田馬場駅      4  2.75
##  5 石器ラーメン 高田馬場                高田馬場駅      0 NA   
##  6 旨辛らーめん 表裏                    高田馬場駅      0 NA   
##  7 三歩一                               高田馬場駅      8  4.56
##  8 えぞ菊 戸塚店                        高田馬場駅      4  3.62
##  9 麺屋　宗                             高田馬場駅      5  4.2 
## 10 とんこつラーメン 博多風龍 高田馬場店 高田馬場駅      2  3   
## 11 横浜家系ラーメン 馬場壱家            高田馬場駅      0 NA   
## 12 らーめん よし丸                      高田馬場駅      1  5   
## 13 札幌ラーメン どさん子 三田店         三田駅          0 NA   
## 14 天下一品 三田店                      三田駅          0 NA</code></pre>
<p>のように書きます（ちなみに高田馬場の「やまぐち」は本当に美味しいです）。むろん、複数の変数を用いたORも可能です。たとえば、「<code>Pref</code>が<code>"京都府"</code>か<code>Score</code>が3以上」のような条件も可能ですが (<code>Pref == "京都府" | Score &gt;= 3</code>)、実際、このような例はあまりありません。よく使うのは「変数<code>X</code>が<code>a</code>か<code>b</code>か<code>c</code>か」のような例です。ただし、この場合は<code>|</code>を使わないもっと簡単な方法があります。それは<code>%in%</code>演算子です。以下のコードは上のコードと同じものです。</p>
<pre class="r numberLines"><code>df %&gt;% 
  filter(Station %in% c(&quot;高田馬場駅&quot;, &quot;三田駅&quot;)) %&gt;%
  select(Name, Station, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 14 x 4
##    Name                                 Station    ScoreN Score
##    &lt;chr&gt;                                &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 麺達 うま家                          高田馬場駅      2  3   
##  2 らぁ麺 やまぐち                      高田馬場駅      7  4.08
##  3 博多一瑞亭 三田店                    三田駅          0 NA   
##  4 つけ麺屋 ひまわり                    高田馬場駅      4  2.75
##  5 石器ラーメン 高田馬場                高田馬場駅      0 NA   
##  6 旨辛らーめん 表裏                    高田馬場駅      0 NA   
##  7 三歩一                               高田馬場駅      8  4.56
##  8 えぞ菊 戸塚店                        高田馬場駅      4  3.62
##  9 麺屋　宗                             高田馬場駅      5  4.2 
## 10 とんこつラーメン 博多風龍 高田馬場店 高田馬場駅      2  3   
## 11 横浜家系ラーメン 馬場壱家            高田馬場駅      0 NA   
## 12 らーめん よし丸                      高田馬場駅      1  5   
## 13 札幌ラーメン どさん子 三田店         三田駅          0 NA   
## 14 天下一品 三田店                      三田駅          0 NA</code></pre>
<p>結局、<code>|</code>が使われるケースがかなり限定されます。あるとすれば、「変数<code>X</code>が<code>a</code>以下か、<code>b</code>以上か」のようなケースですね。ただし、<code>&amp;</code>と<code>|</code>を同時に使うケースは考えられます。たとえば、大阪駅と京都駅周辺のうまいラーメン屋を調べるとします。問題は美味しさの基準ですが、3.5点以上としましょう。ただし、京都府民はラーメンに非常に厳しく、3点以上なら美味しいと仮定します。この場合、「(<code>Station</code>が<code>"大阪駅"</code>かつ<code>Score &gt;= 3.5</code>)、または(<code>Station</code>が<code>"京都駅"</code>かつ<code>Score &gt;= 3</code>)」のような条件が必要になります。<code>()</code>は「<code>()</code>の中から判定せよ」という、普通の算数での使い方と同じです。それでは、実際に検索してみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter((Station == &quot;大阪駅&quot; &amp; Score &gt;= 3.5) | (Station == &quot;京都駅&quot; &amp; Score &gt;= 3)) %&gt;%
  select(Name, Station, Walk, ScoreN, Score)</code></pre>
<pre><code>## # A tibble: 6 x 5
##   Name                      Station  Walk ScoreN Score
##   &lt;chr&gt;                     &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1 Lei can ting 大阪ルクア店 大阪駅      3      3  4   
## 2 神座 ルクア大阪店         大阪駅      1     10  3.94
## 3 みつか坊主 醸             大阪駅     10      4  5   
## 4 無尽蔵 京都八条家         京都駅      5      2  3.5 
## 5 中華料理 清華園           京都駅     10      3  5   
## 6 ますたに 京都拉麺小路店   京都駅      9      3  3.67</code></pre>
<p>Songが大好きな神座がヒットして嬉しいです。</p>
<hr />
</div>
<div id="行のソート" class="section level2">
<h2>行のソート</h2>
<p>続いて、行のソートについて解説します。「食べログ」などのレビューサービスを利用する場合、口コミ評価が高い順で見るのが一般的でしょう<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>。また、サッカーのランキングも多くは1位から下の順位で掲載されるのが一般的です。ここではこのようにある変数の値順に行を並び替える方法について説明します。</p>
<p>ソートには<code>dplyr</code>パッケージの<code>arrange()</code>関数を使います。引数は変数名のみです。たとえば、奈良県のラーメン屋を検索してみましょう。並び替える順は駅から近い店舗を上位に、遠い店舗を下位に並べます。このような順は<strong>昇順 (ascending)</strong>と呼ばれ、ランキング表などでよく見ます。駅から近い順にソートするので、まず最寄りの駅情報が欠損でないことが必要です。また、ラーメン屋の評価も気になるので口コミが1つ以上付いている店舗に絞りましょう。表示する列は店舗名、最寄りの駅、徒歩距離、口コミ数、点数です。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;奈良県&quot;, !is.na(Station), ScoreN &gt; 0) %&gt;%
  select(Name, Station, Walk, ScoreN, Score) %&gt;%
  arrange(Walk) %&gt;%
  print(n = Inf)</code></pre>
<pre><code>## # A tibble: 24 x 5
##    Name                                  Station             Walk ScoreN Score
##    &lt;chr&gt;                                 &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 麺屋 あまのじゃく 本店                富雄駅                 2      2  4.5 
##  2 紀州和歌山らーめんきぶんや 奈良富雄店 富雄駅                 4      1  4   
##  3 ラーメン家 みつ葉                     富雄駅                 4      1  3.5 
##  4 天下一品 新大宮店                     新大宮駅               6      1  3   
##  5 麺屋 一徳                             天理駅                 7      1  3   
##  6 丸源ラーメン 橿原店                   金橋駅                 8      1  3.5 
##  7 らーめん食堂 よってこや 平群店        元山上口駅            10      1  4   
##  8 天理スタミナラーメン本店              櫟本駅                11      2  3.25
##  9 博多長浜らーめん夢街道 奈良土橋店     真菅駅                11      1  3.5 
## 10 ぶ～け                                奈良駅                11      1  5   
## 11 つけめん らーめん元喜神 押熊店        学研奈良登美ヶ丘駅    12      4  4.12
## 12 彩華ラーメン 本店                     前栽駅                12      5  3.6 
## 13 力皇                                  天理駅                13      1  3.5 
## 14 らーめん きみちゃん                   京終駅                14      2  4.5 
## 15 無鉄砲がむしゃら                      帯解駅                15      2  4   
## 16 彩華ラーメン 田原本店                 石見駅                15      1  4   
## 17 神座 大和高田店                       大和高田駅            17      2  3.75
## 18 彩華ラーメン 奈良店                   尼ヶ辻駅              17      3  4.33
## 19 彩華ラーメン 桜井店                   大福駅                18      1  3   
## 20 天下一品 東生駒店                     東生駒駅              19      1  3.5 
## 21 まりお流ラーメン                      新大宮駅              20      1  5   
## 22 どうとんぼり神座 奈良柏木店           西ノ京駅              22      1  3   
## 23 河童ラーメン本舗 押熊店               学研奈良登美ヶ丘駅    28      1  4   
## 24 博多長浜らーめん 夢街道 四条大路店    新大宮駅              29      4  2.88</code></pre>
<p>3行まではこれまで習ってきたもので、4行目がソートの関数、<code>arrange()</code>です。引数はソートの基準となる変数で、今回は最寄りの駅からの徒歩距離を表す<code>Walk</code>です。5行目は省略可能ですが、<code>tibble</code>クラスの場合、10行までしか出力されないので、<code>print(n = Inf)</code>で「すべての行を表示」させます。<code>n</code>を指定することで出力される行数が調整可能です。奈良県のラーメン屋の中で最寄りの駅から最も近い店は「<a href="https://www.menya-amanojaku.com">麺屋 あまのじゃく 本店</a>」で徒歩2分でした。京田辺店も駅から約2分ですし、近いですね。ちなみにSongはここの塩とんこつが好きです。世界一こってりなラーメンとも言われる「チョモランマ」で有名な「<a href="http://www.marioramen.com">まりお流ラーメン</a>」は新大宮駅から徒歩20分でかなり遠いことが分かります。</p>
<p>続いて、駅からの距離ではなく、評価が高い順にしてみましょう。評価が高いほど上に来るので、今回は昇順でなく、<strong>降順 (descending)</strong>でソートする必要があります。<code>arrange()</code>関数は基本的に、指定された変数を基準に昇順でソートします。降順にするためには<code>desc()</code>関数を更に用います。たとえば、<code>arrange(desc(変数名))</code>のようにです。それでは実際にやってみましょう。上のコードの4行目を<code>arange(Walk)</code>から<code>arrange(desc(Score))</code>にちょっと修正するだけです。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;奈良県&quot;, !is.na(Station), ScoreN &gt; 0) %&gt;%
  select(Name, Station, Walk, ScoreN, Score) %&gt;%
  arrange(desc(Score)) %&gt;%
  print(n = Inf)</code></pre>
<pre><code>## # A tibble: 24 x 5
##    Name                                  Station             Walk ScoreN Score
##    &lt;chr&gt;                                 &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 まりお流ラーメン                      新大宮駅              20      1  5   
##  2 ぶ～け                                奈良駅                11      1  5   
##  3 麺屋 あまのじゃく 本店                富雄駅                 2      2  4.5 
##  4 らーめん きみちゃん                   京終駅                14      2  4.5 
##  5 彩華ラーメン 奈良店                   尼ヶ辻駅              17      3  4.33
##  6 つけめん らーめん元喜神 押熊店        学研奈良登美ヶ丘駅    12      4  4.12
##  7 河童ラーメン本舗 押熊店               学研奈良登美ヶ丘駅    28      1  4   
##  8 無鉄砲がむしゃら                      帯解駅                15      2  4   
##  9 紀州和歌山らーめんきぶんや 奈良富雄店 富雄駅                 4      1  4   
## 10 彩華ラーメン 田原本店                 石見駅                15      1  4   
## 11 らーめん食堂 よってこや 平群店        元山上口駅            10      1  4   
## 12 神座 大和高田店                       大和高田駅            17      2  3.75
## 13 彩華ラーメン 本店                     前栽駅                12      5  3.6 
## 14 天下一品 東生駒店                     東生駒駅              19      1  3.5 
## 15 力皇                                  天理駅                13      1  3.5 
## 16 博多長浜らーめん夢街道 奈良土橋店     真菅駅                11      1  3.5 
## 17 ラーメン家 みつ葉                     富雄駅                 4      1  3.5 
## 18 丸源ラーメン 橿原店                   金橋駅                 8      1  3.5 
## 19 天理スタミナラーメン本店              櫟本駅                11      2  3.25
## 20 麺屋 一徳                             天理駅                 7      1  3   
## 21 どうとんぼり神座 奈良柏木店           西ノ京駅              22      1  3   
## 22 彩華ラーメン 桜井店                   大福駅                18      1  3   
## 23 天下一品 新大宮店                     新大宮駅               6      1  3   
## 24 博多長浜らーめん 夢街道 四条大路店    新大宮駅              29      4  2.88</code></pre>
<p>よく考えてみれば、「評価が同点の場合、どうなるの?」と疑問を抱く方がいるかも知れません。たとえば、7行目の「河童ラーメン本舗 押熊店」と8行目の「無鉄砲がむしゃら」はどれも評価が4点ですが、「河童ラーメン本舗 押熊店」が先に表示されます。そのこれは簡単です。同点の場合、データセット内で上に位置する行が先に表示されます。これを確認するには<code>which()</code>関数を使います。<code>()</code>内に条件文を指定することで、この条件に合致する要素の位置を返します。もし、条件に合致するものが複数あった場合は全ての位置を返します<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>。</p>
<pre class="r numberLines"><code>which(df$Name == &quot;河童ラーメン本舗 押熊店&quot;)</code></pre>
<pre><code>## [1] 6021</code></pre>
<pre class="r numberLines"><code>which(df$Name == &quot;無鉄砲がむしゃら&quot;)</code></pre>
<pre><code>## [1] 6040</code></pre>
<p>データ内に「河童ラーメン本舗 押熊店」がより上に位置することが分かります。「もし同点なら口コミ評価数が多いところにしたい」場合はどうすれば良いでしょうか。これは<code>arrange()</code>内に変数名を足すだけで十分です。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;奈良県&quot;, !is.na(Station), ScoreN &gt; 0) %&gt;%
  select(Name, Station, Walk, ScoreN, Score) %&gt;%
  arrange(desc(Score), desc(ScoreN)) %&gt;%
  print(n = Inf)</code></pre>
<pre><code>## # A tibble: 24 x 5
##    Name                                  Station             Walk ScoreN Score
##    &lt;chr&gt;                                 &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 まりお流ラーメン                      新大宮駅              20      1  5   
##  2 ぶ～け                                奈良駅                11      1  5   
##  3 麺屋 あまのじゃく 本店                富雄駅                 2      2  4.5 
##  4 らーめん きみちゃん                   京終駅                14      2  4.5 
##  5 彩華ラーメン 奈良店                   尼ヶ辻駅              17      3  4.33
##  6 つけめん らーめん元喜神 押熊店        学研奈良登美ヶ丘駅    12      4  4.12
##  7 無鉄砲がむしゃら                      帯解駅                15      2  4   
##  8 河童ラーメン本舗 押熊店               学研奈良登美ヶ丘駅    28      1  4   
##  9 紀州和歌山らーめんきぶんや 奈良富雄店 富雄駅                 4      1  4   
## 10 彩華ラーメン 田原本店                 石見駅                15      1  4   
## 11 らーめん食堂 よってこや 平群店        元山上口駅            10      1  4   
## 12 神座 大和高田店                       大和高田駅            17      2  3.75
## 13 彩華ラーメン 本店                     前栽駅                12      5  3.6 
## 14 天下一品 東生駒店                     東生駒駅              19      1  3.5 
## 15 力皇                                  天理駅                13      1  3.5 
## 16 博多長浜らーめん夢街道 奈良土橋店     真菅駅                11      1  3.5 
## 17 ラーメン家 みつ葉                     富雄駅                 4      1  3.5 
## 18 丸源ラーメン 橿原店                   金橋駅                 8      1  3.5 
## 19 天理スタミナラーメン本店              櫟本駅                11      2  3.25
## 20 麺屋 一徳                             天理駅                 7      1  3   
## 21 どうとんぼり神座 奈良柏木店           西ノ京駅              22      1  3   
## 22 彩華ラーメン 桜井店                   大福駅                18      1  3   
## 23 天下一品 新大宮店                     新大宮駅               6      1  3   
## 24 博多長浜らーめん 夢街道 四条大路店    新大宮駅              29      4  2.88</code></pre>
<p>ソートの基準は<code>arrange()</code>内において先に指定された変数の順番となります。「口コミ評価も評価数も同じなら、駅から近いところにしたい」場合は変数が3つとなり、<code>Score</code>、<code>ScoreN</code>、<code>Walk</code>の順で入れます。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(Pref == &quot;奈良県&quot;, !is.na(Station), ScoreN &gt; 0) %&gt;%
  select(Name, Station, Walk, ScoreN, Score) %&gt;%
  arrange(desc(Score), desc(ScoreN), Walk) %&gt;%
  print(n = Inf)</code></pre>
<pre><code>## # A tibble: 24 x 5
##    Name                                  Station             Walk ScoreN Score
##    &lt;chr&gt;                                 &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1 ぶ～け                                奈良駅                11      1  5   
##  2 まりお流ラーメン                      新大宮駅              20      1  5   
##  3 麺屋 あまのじゃく 本店                富雄駅                 2      2  4.5 
##  4 らーめん きみちゃん                   京終駅                14      2  4.5 
##  5 彩華ラーメン 奈良店                   尼ヶ辻駅              17      3  4.33
##  6 つけめん らーめん元喜神 押熊店        学研奈良登美ヶ丘駅    12      4  4.12
##  7 無鉄砲がむしゃら                      帯解駅                15      2  4   
##  8 紀州和歌山らーめんきぶんや 奈良富雄店 富雄駅                 4      1  4   
##  9 らーめん食堂 よってこや 平群店        元山上口駅            10      1  4   
## 10 彩華ラーメン 田原本店                 石見駅                15      1  4   
## 11 河童ラーメン本舗 押熊店               学研奈良登美ヶ丘駅    28      1  4   
## 12 神座 大和高田店                       大和高田駅            17      2  3.75
## 13 彩華ラーメン 本店                     前栽駅                12      5  3.6 
## 14 ラーメン家 みつ葉                     富雄駅                 4      1  3.5 
## 15 丸源ラーメン 橿原店                   金橋駅                 8      1  3.5 
## 16 博多長浜らーめん夢街道 奈良土橋店     真菅駅                11      1  3.5 
## 17 力皇                                  天理駅                13      1  3.5 
## 18 天下一品 東生駒店                     東生駒駅              19      1  3.5 
## 19 天理スタミナラーメン本店              櫟本駅                11      2  3.25
## 20 天下一品 新大宮店                     新大宮駅               6      1  3   
## 21 麺屋 一徳                             天理駅                 7      1  3   
## 22 彩華ラーメン 桜井店                   大福駅                18      1  3   
## 23 どうとんぼり神座 奈良柏木店           西ノ京駅              22      1  3   
## 24 博多長浜らーめん 夢街道 四条大路店    新大宮駅              29      4  2.88</code></pre>
<hr />
</div>
<div id="記述統計量の計算" class="section level2">
<h2>記述統計量の計算</h2>
<div id="summariseによる記述統計量の計算" class="section level3">
<h3><code>summarise()</code>による記述統計量の計算</h3>
<p>ある変数の平均値や標準偏差、最小値、最大値などの記述統計量 (要約統計量)を計算することも可能です。これは<code>summarize()</code>または<code>summarise()</code>関数を使いますが、この関数は後で紹介する<code>group_by()</code>関数と組み合わせることで力を発揮します。ここではグルーピングを考えずに、全データの記述統計量を計算する方法を紹介します。</p>
<p><code>summarise()</code>関数の使い方は以下の通りです。</p>
<pre class="r numberLines"><code># summarise()関数の使い方
データフレーム/tibble名 %&gt;%
  summarise(新しい変数名 = 関数名(計算の対象となる変数名))</code></pre>
<p>もし、<code>Score</code>変数の平均値を計算し、その結果を<code>Mean</code>という列にしたい場合は以下のようなコードになります。</p>
<pre class="r numberLines"><code>df %&gt;%
  summarise(Mean = mean(Score))</code></pre>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1    NA</code></pre>
<p>ただし、<code>mean()</code>関数は欠損値が含まれるベクトルの場合、<code>NA</code>を返します。この場合方法は2つ考えられます。</p>
<ol style="list-style-type: decimal">
<li><code>filter()</code>関数を使って<code>Score</code>が欠損しているケースを予め除去する。</li>
<li><code>na.rm</code>引数を指定し、欠損値を除去した平均値を求める。</li>
</ol>
<p>ここでは2番目の方法を使います。</p>
<pre class="r numberLines"><code>df %&gt;%
  summarise(Mean = mean(Score, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1  3.66</code></pre>
<p><code>df</code>の<code>Score</code>変数の平均値はNAであることが分かります。また、<code>summarise()</code>関数は複数の記述統計量を同時に計算することも可能です。以下は<code>Score</code>変数の平均値、中央値、標準偏差、最小値、最大値、第一四分位点、第三四分位点を計算し、<code>Score.Desc</code>という名のデータフレーム (または、tibble)に格納するコードです。</p>
<pre class="r numberLines"><code>Score.Desc &lt;- df %&gt;%
  summarize(Mean   =     mean(Score,       na.rm = TRUE),  # 平均値
            Median =   median(Score,       na.rm = TRUE),  # 中央値
            SD     =       sd(Score,       na.rm = TRUE),  # 標準偏差
            Min    =      min(Score,       na.rm = TRUE),  # 最小値
            Max    =      max(Score,       na.rm = TRUE),  # 最大値
            Q1     = quantile(Score, 0.25, na.rm = TRUE),  # 第一四分位点
            Q3     = quantile(Score, 0.75, na.rm = TRUE))  # 第三四分位点</code></pre>
<pre class="r numberLines"><code>Score.Desc</code></pre>
<pre><code>## # A tibble: 1 x 7
##    Mean Median    SD   Min   Max    Q1    Q3
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  3.66   3.58 0.719     1     5     3     4</code></pre>
<p>むろん、複数の変数に対して記述統計量を計算することも可能です。たとえば、平均予算 (<code>Budget</code>)、口コミ数 (<code>ScoreN</code>)、口コミ評価 (<code>Score</code>)の平均値を求めるとしたら、</p>
<pre class="r numberLines"><code>df %&gt;%
  summarize(Budget_Mean = mean(Budget, na.rm = TRUE), # 平均予算の平均値
            SocreN_Mean = mean(ScoreN, na.rm = TRUE), # 口コミ数の平均値
            Score_Mean  = mean(Score,  na.rm = TRUE)) # 評価の平均値</code></pre>
<pre><code>## # A tibble: 1 x 3
##   Budget_Mean SocreN_Mean Score_Mean
##         &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1       1232.       0.537       3.66</code></pre>
<p>のように書きます。実は<code>summarise()</code>はこれくらいで十分便利です。ただし、以上の操作はもっと簡単なコードに置換できます。ただし、ラムダ式など、やや高度な内容になるため、以下の内容は飛ばして、次の節 (グルーピング)を読んでいただいても構いません。</p>
<p>まずは、複数の変数に対して同じ記述統計量を求める例を考えてみましょう。たとえば、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>に対して平均値を求める例です。これは<code>across()</code>関数を使うとよりコードが短くなります。まずは<code>across()</code>関数の書き方から見ましょう。</p>
<pre class="r numberLines"><code># across()の使い方
データフレーム/tibble名 %&gt;%
  summarise(across(変数名のベクトル, 記述統計を計算する関数名, 関数の引数))</code></pre>
<p><em>変数名のベクトル</em>は長さ1以上のベクトルです。たとえば、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>の場合<code>c(Budget, ScoreN, Score)</code>になります。これは<code>df</code>内で隣接する変数ですから<code>Budget:Score</code>の書き方も使えます。また、<code>where()</code>や<code>any_of()</code>、<code>starts_with()</code>のような関数を使って変数を指定することも可能です。<em>関数名</em>は<code>mean</code>や<code>sd</code>などの関数名です。ここは<code>関数名()</code>でななく、<code>関数名</code>であることに注意してください。<em>引数</em>は前の関数に必要な引数です。引数を必要としない関数なら省略可能ですが、<code>na.rm = TRUE</code>などの引数が必要な場合は指定する必要があります。それでは<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>の平均値を計算してみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  summarize(across(Budget:Score, mean, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 3
##   Budget ScoreN Score
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1  1232.  0.537  3.66</code></pre>
<p><code>across()</code>使わない場合、4行必要だったコードが2行になりました。変数が少ない場合は<code>across()</code>を使わない方が、可読性が高くなる場合もあります。しかし、変数が多くなる場合、可読性がやや落ちても<code>across()</code>を使った方が効率的でしょう。</p>
<p>次は、ある変数に対して複数の記述統計量を計算したい場合について考えます。<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>変数の第一四分位点と第三四分位点を<code>across()</code>を使わずに計算すると家のような7行のコードになります。</p>
<pre class="r numberLines"><code>df %&gt;%
  summarize(Budget_Q1 = quantile(Budget, 0.25, na.rm = TRUE),
            Budget_Q3 = quantile(Budget, 0.75, na.rm = TRUE),
            ScoreN_Q1 = quantile(ScoreN, 0.25, na.rm = TRUE),
            ScoreN_Q3 = quantile(ScoreN, 0.75, na.rm = TRUE),
            Score_Q1  = quantile(Score,  0.25, na.rm = TRUE),
            Score_Q3  = quantile(Score,  0.75, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>この作業も<code>across()</code>を使ってより短縮することができます。ここではラムダ式の知識が必要になります。ラムダ関数とは関数名を持たない<a href="https://ja.wikipedia.org/wiki/無名関数">無名関数 (anonymous functions)</a>を意味しますが、詳細は割愛します。興味のある読者は<a href="https://ja.wikipedia.org/wiki/無名関数">Wikipedia</a>などを参照してください。簡単にいうとその場で即席に関数を作成し、計算が終わったら破棄する関数です。ただ、Rは基本的にラムダ式を提供しているのではなく、<code>purrr</code>パッケージのラムダ式スタイルを使用します。まずは、書き方から確認します。</p>
<pre class="r numberLines"><code># ラムダ式を用いたacross()の使い方
データフレーム/tibble名 %&gt;%
  summarise(across(変数名のベクトル, list(結果の変数名 = ラムダ式)))</code></pre>
<p>先ほどの書き方と似ていますが、関数を複数書く必要があるため、今回は関数名をlist型にまとめます。そして、<em>結果の変数名</em>は結果として出力されるデータフレーム (または、tibble)の列名を指定する引数です。たとえば、<code>Mean</code>にすると結果は<code>元の変数名1_Mean</code>、<code>元の変数名2_Mean</code>…のように出力されます。そして、ラムダ式が実際の関数が入る箇所です。とりあえず今回はコードを走らせ、結果から確認してみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  summarize(across(Budget:Score, list(Q1 = ~quantile(.x, 0.25, na.rm = TRUE),
                                      Q3 = ~quantile(.x, 0.75, na.rm = TRUE))))</code></pre>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>結果の列名が<code>Budget_Q1</code>、<code>Budget_Q3</code>、<code>ScoreN_Q1</code>…のようになり、それぞれの変数の第一四分位点と第三四分位点が出力されます。問題はラムダ式の方ですが、普通の関数に非常に近いことが分かります。<code>across()</code>内のラムダ式は<code>~関数名(.x, その他の引数)</code>のような書き方になります。関数名の前に<code>~</code>が付いていることに注意してください。分位数を求める関数は<code>quantile()</code>であり、<code>quantile(ベクトル, 分位数)</code>であり、必要に応じて<code>na.rm</code>を付けます。この分位数が0.25なら第一四分位点、0.5なら第二四分位点 (=中央値)、0.75なら第三四分位点になります。それではラムダ式<code>~quantile(.x, 0.25, na.rm = TRUE)</code>はどういう意味でしょうか。これは<code>.x</code>の箇所に<code>Budget</code>や<code>ScoreN</code>、<code>Score</code>が入ることを意味します。<code>.x</code>という書き方は決まりです。<code>.y</code>とか<code>.Song-san-Daisuki</code>などはダメです。そして、<code>0.25</code>を付けることによって第一四分位点を出力するように指定します。また、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>に欠損値がある場合、無視するように<code>na.rm = TRUE</code>を付けます。</p>
<p>ラムダ式を自分で定義する関数で表現すると、以下のようになります。</p>
<pre class="r numberLines"><code># 以下の3つは同じ機能をする関数である

# ラムダ式
~quantile(.x, 0.25, na.rm = TRUE)

# 一般的な関数の書き方1
名無し関数 &lt;- function(x) {
  quantile(x, 0.25, na.rm = TRUE)
}

# 一般的な関数の書き方2
名無し関数 &lt;- function(x) quantile(x, 0.25, na.rm = TRUE)</code></pre>
<p>この3つは全て同じですが、ラムダ式は関数名を持たず、その場で使い捨てる関数です。むろん、ラムダ式を使わずに事前に第一四分位点と第三四分位点を求める関数を予め作成し、ラムダ式の代わりに使うことも可能です。まずは第一四分位点と第三四分位点を求める自作関数<code>FuncQ1</code>と<code>FuncQ2</code>を作成します。</p>
<pre class="r numberLines"><code># ラムダ式を使わない場合は事前に関数を定義しておく必要がある
FuncQ1 &lt;- function(x) {
  quantile(x, 0.25, na.rm = TRUE)
}
FuncQ3 &lt;- function(x) {
  quantile(x, 0.75, na.rm = TRUE)
}</code></pre>
<p>後は先ほどのほぼ同じ書き方ですが、今回はラムダ式を使わないため関数名に<code>~</code>を付けず、関数名のみで十分です。</p>
<pre class="r numberLines"><code># やっておくと、summarise()文は簡潔になる
df %&gt;%
  summarize(across(Budget:Score, list(Q1 = FuncQ1, Q3 = FuncQ3)))</code></pre>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>事前に関数を用意するのが面倒ですが、<code>across()</code>の中身はかなりスッキリしますね。もし、このような作業を何回も行うなら、ラムダ式を使わず、自作関数を用いることも可能です。ただし、自作関数であっても引数が2つ以上必要な場合はラムダ式を使います。</p>
</div>
<div id="summariseに使える便利な関数" class="section level3">
<h3><code>summarise()</code>に使える便利な関数</h3>
<p>以下の内容は後で説明する<code>group_by()</code>関数を使っているため、まだ<code>group_by()</code>に馴染みのない読者はまずはここを読み飛ばし、グルーピングの節にお進みください。</p>
<p><strong><code>IQR()</code>: 四分位範囲を求める</strong></p>
<p>四分位範囲は第三四分位点から第一四分位点を引いた値であり、Rの内蔵関数である<code>IQR()</code>を使えば便利です。この関数は<code>mean</code>や<code>sd()</code>関数と同じ使い方となります。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Walk)) %&gt;% # 予め欠損したケースを除くと、後でna.rm = TRUEが不要
  group_by(Pref) %&gt;%
  summarise(Mean    = mean(Walk),
            SD      = sd(Walk),
            IQR     = IQR(Walk),
            N       = n(),
            .groups = &quot;drop&quot;) %&gt;%
  arrange(Mean)</code></pre>
<pre><code>## # A tibble: 9 x 5
##   Pref      Mean    SD   IQR     N
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 東京都    4.29  4.49     4   919
## 2 大阪府    5.92  6.08     6   932
## 3 神奈川県  8.21  7.91    10   878
## 4 京都府    8.38  6.95     9   339
## 5 兵庫県    8.52  7.27    10   484
## 6 奈良県   10.6   6.59    10   123
## 7 千葉県   10.6   8.21    12   776
## 8 埼玉県   11.6   8.99    14   817
## 9 和歌山県 12.8   6.83     9   107</code></pre>
<p><strong><code>first()</code>、<code>last()</code>、<code>nth()</code>: n番目の要素を求める</strong></p>
<p>稀なケースかも知れませんが、データ内、またはグループ内の<code>n</code>番目の行を抽出する時があります。たとえば、市区町村の情報が格納されているデータセットで、人口が大きい順でデータがソートされているとします。各都道府県ごとに最も人口が大きい市区町村のデータ、あるいは最も少ない市区町村のデータが必要な際、<code>first()</code>と<code>last()</code>関数が有効です。</p>
<p>それでは各都道府県ごとに「最も駅から遠いラーメン屋」の店舗名と最寄りの駅からの徒歩距離を出力したいとします。まずは、徒歩距離のデータが欠損しているケースを除去し、データを徒歩距離順でソートします。これは<code>filter()</code>と<code>arrange()</code>関数を使えば簡単です。続いて、<code>group_by()</code>を使って都府県単位でデータをグループ化します。最後に<code>summarise()</code>関数内に<code>last()</code>関数を使います。データは駅から近い順に鳴っているため、各都府県内の最後の行は駅から最も遠い店舗になるからです。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Walk)) %&gt;%
  arrange(Walk) %&gt;%
  group_by(Pref) %&gt;%
  summarise(Farthest  = last(Name),
            Distance  = last(Walk),
            .groups   = &quot;drop&quot;)</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     Farthest                           Distance
##   &lt;chr&gt;    &lt;chr&gt;                                 &lt;dbl&gt;
## 1 京都府   熱烈らぁめん                             30
## 2 埼玉県   札幌ラーメン どさん子 小鹿野店          116
## 3 神奈川県 札幌ラーメン どさん子 中津店             73
## 4 千葉県   札幌ラーメン どさん子 佐原51号店         59
## 5 大阪府   河童ラーメン本舗 岸和田店                38
## 6 東京都   てんがら 青梅新町店                      30
## 7 奈良県   博多長浜らーめん 夢街道 四条大路店       29
## 8 兵庫県   濃厚醤油 中華そば いせや 玉津店          43
## 9 和歌山県 中華そば まる乃                          30</code></pre>
<p>この<code>last()</code>を<code>first()</code>に変えると、最寄りの駅から最も近い店舗情報が表示されます。また、「<code>n</code>番目の情報」が必要な際は<code>nth()</code>関数を使います。<code>nth(Name, 2)</code>に変えることで2番目の店舗名が抽出できます。</p>
<p><strong><code>n_distinct()</code>: ユニーク値の個数を求める</strong></p>
<p><code>n_distinct()</code>は何種類の要素が含まれているかを計算する関数であり、<code>length(unique())</code>関数と同じ機能をします。たとえば、以下の<code>myVec1</code>に対して何種類の要素があるかを確認してみましょう。</p>
<pre class="r numberLines"><code>myVec1 &lt;- c(&quot;A&quot;, &quot;B&quot;, &quot;B&quot;, &quot;D&quot;, &quot;A&quot;, &quot;B&quot;, &quot;D&quot;, &quot;C&quot;, &quot;A&quot;)

unique(myVec1)</code></pre>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;D&quot; &quot;C&quot;</code></pre>
<p><code>myVec1</code>は<code>"A"</code>、<code>"B"</code>、<code>"D"</code>、<code>"C"</code>の要素で構成されていることが分かります。これが<code>myVec1</code>の<strong>ユニーク値 (unique values)</strong>です。そして、このユニーク値の個数を調べるために<code>length()</code>を使います。</p>
<pre class="r numberLines"><code>length(unique(myVec1))</code></pre>
<pre><code>## [1] 4</code></pre>
<p>これで<code>myVec1</code>は4種類の値が存在することが分かります。これと全く同じ機能をする関数が<code>n_distinct()</code>です。</p>
<pre class="r numberLines"><code>n_distinct(myVec1)</code></pre>
<pre><code>## [1] 4</code></pre>
<p>この関数を<code>summarise()</code>に使うことで、都府県ごとに駅の個数が分かります。あるいは「東京都内の選挙区に、これまでの衆院選において何人の候補者が存在したか」も分かります。ここでは<code>df</code>内の都府県ごとに駅の個数を計算してみましょう。最後の駅数が多い順でソートします。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Station)) %&gt;% # 最寄りの駅が欠損しているケースを除去
  group_by(Pref) %&gt;%
  summarise(N_Station = n_distinct(Station),
            .groups   = &quot;drop&quot;) %&gt;%
  arrange(desc(N_Station))</code></pre>
<pre><code>## # A tibble: 9 x 2
##   Pref     N_Station
##   &lt;chr&gt;        &lt;int&gt;
## 1 東京都         368
## 2 大阪府         341
## 3 千葉県         241
## 4 神奈川県       240
## 5 兵庫県         199
## 6 埼玉県         185
## 7 京都府         123
## 8 奈良県          52
## 9 和歌山県        46</code></pre>
<p>当たり前かも知れませんが、駅数が最も多いのは東京都で次が大阪府であることが分かります。</p>
<p><strong><code>any()</code>、<code>all()</code>: 条件に合致するか否かを求める</strong></p>
<p><code>any()</code>と<code>all()</code>はベクトル内の全要素に対して条件に合致するか否かを判定する関数です。ただし、<code>any()</code>は一つの要素でも条件に合致すれば<code>TRUE</code>を、全要素が合致しない場合<code>FALSE</code>を返します。一方、<code>all()</code>は全要素に対して条件を満たせば<code>TRUE</code>、一つでも満たさない要素があれば<code>FALSE</code>を返します。以下は<code>any()</code>と<code>all()</code>の例です。</p>
<pre class="r numberLines"><code>myVec1 &lt;- c(1, 2, 3, 4, 5)
myVec2 &lt;- c(1, 3, 5, 7, 11)

any(myVec1 %% 2 == 0) # myVec1を2で割った場合、一つでも余りが0か</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r numberLines"><code>all(myVec1 %% 2 == 0) # myVec1を2で割った場合、全ての余りが0か</code></pre>
<pre><code>## [1] FALSE</code></pre>
<pre class="r numberLines"><code>all(myVec2 %% 2 != 0) # myVec2を2で割った場合、全ての余りが0ではないか</code></pre>
<pre><code>## [1] TRUE</code></pre>
<p>それでは実際に<code>df</code>に対して<code>any()</code>と<code>all()</code>関数を使ってみましょう。一つ目は「ある都府県に最寄りの駅から徒歩60分以上の店舗が<strong>一つでも</strong>あるか」であり、二つ目は「ある都府県の店舗は<strong>全て</strong>最寄りの駅から徒歩30分以下か」です。それぞれの結果を<code>Over60</code>と<code>Within30</code>という列で出力してみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  group_by(Pref) %&gt;%
  summarise(Over60   = any(Walk &gt;= 60, na.rm = TRUE),
            Within30 = all(Walk &lt;= 30, na.rm = TRUE),
            .groups  = &quot;drop&quot;)</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     Over60 Within30
##   &lt;chr&gt;    &lt;lgl&gt;  &lt;lgl&gt;   
## 1 京都府   FALSE  TRUE    
## 2 埼玉県   TRUE   FALSE   
## 3 神奈川県 TRUE   FALSE   
## 4 千葉県   FALSE  FALSE   
## 5 大阪府   FALSE  FALSE   
## 6 東京都   FALSE  TRUE    
## 7 奈良県   FALSE  TRUE    
## 8 兵庫県   FALSE  FALSE   
## 9 和歌山県 FALSE  TRUE</code></pre>
<p>埼玉県と神奈川県において、最寄りの駅から徒歩60以上の店がありました。また、京都府、東京都、奈良県、和歌山県の場合、全店舗が最寄りの駅から徒歩30分以下ということが分かります。当たり前ですが<code>Over60</code>が<code>TRUE</code>なら<code>Within30</code>は必ず<code>FALSE</code>になりますね。</p>
<hr />
</div>
</div>
<div id="グルーピング" class="section level2">
<h2>グルーピング</h2>
<div id="group_byによるグループ化" class="section level3">
<h3><code>group_by()</code>によるグループ化</h3>
<p>先ほどの<code>summarise()</code>関数は確かに便利ですが、特段に便利とも言いにくいです。<code>df</code>の<code>Score</code>の平均値を計算するだけなら、<code>summarise()</code>関数を使わない方が楽です。</p>
<pre class="r numberLines"><code># これまでのやり方
df %&gt;%
  summarise(Mean = mean(Score, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1  3.66</code></pre>
<pre class="r numberLines"><code># 普通にこれでええんちゃう?
mean(df$Score, na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.663457</code></pre>
<p>しかし、これをグループごとに計算するならどうでしょう。たとえば、<code>Score</code>の平均値を都府県ごとに計算するとします。この場合、以下のようなコードになります。</p>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;東京都&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.674256</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;神奈川県&quot;], na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.533931</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;千葉県&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.715983</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;埼玉県&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.641573</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;大阪府&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.765194</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;京都府&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.684976</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;兵庫県&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.543936</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;奈良県&quot;],   na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.854762</code></pre>
<pre class="r numberLines"><code>mean(df$Score[df$Pref == &quot;和歌山県&quot;], na.rm = TRUE)</code></pre>
<pre><code>## [1] 3.96999</code></pre>
<p>変わったのは<code>df$Score</code>が<code>df$Score[df$Pref == "東京都"]</code>に変わっただけです。<code>df$Pref</code>が<code>"東京都"</code>であるか否かを<code>TRUE</code>と<code>FALSE</code>で判定し、これを基準に<code>df$Score</code>を抽出する仕組みです。<code>df$Score</code>と<code>df$Pref</code>は同じデータフレーム (または、tibble)ですから、このような書き方で問題ありません。</p>
<p>これだけでもかなり書くのが面倒ですが、これが47都道府県なら、あるいは200ヶ国ならかなり骨の折れる作業でしょう。ここで大活躍するのが<code>dplyr</code>パッケージの<code>group_by()</code>関数です。引数はグループ化する変数名だけです。先ほどの作業を<code>dplyr</code>を使うなら<code>Pref</code>変数でグループ化し、<code>summarise()</code>関数で平均値を求めるだけです。今回は<code>Score</code>だけでなく、<code>ScoreN</code>の平均値も求めてみましょう。そして、評価が高い順にソートもしてみます。</p>
<pre class="r numberLines"><code># ScoreNとScoreの平均値をPrefごとに求める
df %&gt;%
  group_by(Pref) %&gt;%
  summarise(ScoreN_Mean = mean(ScoreN, na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE)) %&gt;%
  arrange(desc(Score_Mean))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     ScoreN_Mean Score_Mean
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 和歌山県       0.593       3.97
## 2 奈良県         0.306       3.85
## 3 大阪府         0.516       3.77
## 4 千葉県         0.259       3.72
## 5 京都府         0.522       3.68
## 6 東京都         1.16        3.67
## 7 埼玉県         0.278       3.64
## 8 兵庫県         0.389       3.54
## 9 神奈川県       0.587       3.53</code></pre>
<p>評判が最も高い都府県は和歌山県、最も低いのは神奈川県ですね。Songも和歌山ラーメンは井出系も車庫前系も好きです。しかし、大事なのは「井出系」と「車庫前系」といった分類が正しいかどうかではありません。コードが非常に簡潔となり、ソートなども自由自在であることです。都府県ごとに<code>ScoreN</code>と<code>Score</code>の平均値を求める場合、<code>dplyr()</code>を使わなかったら18行のコードとなり、ソートも自分でやる必要があります。一方、<code>group_by()</code>関数を使うことによってコードが5行になりました。</p>
<p>また、これは2020年6月に公開された<code>dplyr</code>1.0.0からの問題ですが、<code>group_by()</code>の後に<code>summarise()</code>を使うと以下のようなメッセージが出力されます。</p>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>これは<code>group_by()</code>で指定された変数のグループ化が自動的に解除されたことを意味します。なぜなら<code>summarise()</code>をする際は<code>Pref</code>をグループ変数として使いましたが、出力された結果の<code>Pref</code>変数はもはやグループとして機能できなくなるからです。元の<code>df</code>には<code>Pref</code>が<code>"東京都"</code>だったケースが1000行、<code>"京都府"</code>だったのが414行あったので、<code>Pref</code>変数でグループ化する意味がありました。しかし、<code>summarise()</code>から得られたデータフレーム (または、tibble)は<code>Pref == "東京都"</code>の行が1つしかありません。これはグループ化する意味がなくなったことを意味します。したがって、自動的にグループを解除してくれます。自動的にやってくれるのはありがたいことですが、可能ならば関数内に自分で明記することが推奨されます。そこで使う引数が<code>.groups</code>であり、<code>"drop"</code>を指定すると<strong>全ての</strong>グループ化変数を解除します。以下のようなコードだと先ほどのメッセージが表示されません。今後、意識的に入れるようにしましょう。</p>
<pre class="r numberLines"><code># ScoreNとScoreの平均値をPrefごとに求める
df %&gt;%
  group_by(Pref) %&gt;%
  summarise(ScoreN_Mean = mean(ScoreN, na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE),
            .groups     = &quot;drop&quot;) %&gt;%
  arrange(desc(Score_Mean))</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     ScoreN_Mean Score_Mean
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 和歌山県       0.593       3.97
## 2 奈良県         0.306       3.85
## 3 大阪府         0.516       3.77
## 4 千葉県         0.259       3.72
## 5 京都府         0.522       3.68
## 6 東京都         1.16        3.67
## 7 埼玉県         0.278       3.64
## 8 兵庫県         0.389       3.54
## 9 神奈川県       0.587       3.53</code></pre>
<p>続いて、一つ便利な関数を紹介します。それはグループのサイズを計算する関数、<code>n()</code>です。この関数を<code>summarise()</code>内に使うと、各グループに属するケース数を出力します。先ほどのコードを修正し、各グループのサイズを<code>N</code>という名の列として追加してみましょう。そしてソートの順番は<code>N</code>を最優先とし、同じ場合は<code>Score_Mean</code>が高い方を上に出力させます。また、<code>ScoreN_Mean</code>の前に、口コミ数の合計も出してみましょう。</p>
<pre class="r numberLines"><code># Prefごとに口コミ数の合計、口コミ数の平均値、評価の平均値、店舗数を求める
# 店舗数-評価の平均値順でソートする
df %&gt;%
  group_by(Pref) %&gt;%
  summarise(ScoreN_Sum  = sum(ScoreN,  na.rm = TRUE),
            ScoreN_Mean = mean(ScoreN, na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE),
            N           = n(),
            .groups     = &quot;drop&quot;) %&gt;%
  arrange(desc(N), desc(Score_Mean))</code></pre>
<pre><code>## # A tibble: 9 x 5
##   Pref     ScoreN_Sum ScoreN_Mean Score_Mean     N
##   &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 大阪府          516       0.516       3.77  1000
## 2 千葉県          259       0.259       3.72  1000
## 3 東京都         1165       1.16        3.67  1000
## 4 埼玉県          278       0.278       3.64  1000
## 5 神奈川県        587       0.587       3.53  1000
## 6 兵庫県          230       0.389       3.54   591
## 7 京都府          216       0.522       3.68   414
## 8 奈良県           45       0.306       3.85   147
## 9 和歌山県         83       0.593       3.97   140</code></pre>
<p>記述統計をグループごとに求めるのは普通にあり得るケースですし、実験データの場合はほぼ必須の作業でう。統制群と処置群間においてグループサイズが均一か、共変量のバラツキが十分に小さいかなどを判断する際に<code>group_by()</code>と<code>summarise()</code>関数の組み合わせは非常に便利です。</p>
</div>
<div id="複数の変数を用いたグループ化" class="section level3">
<h3>複数の変数を用いたグループ化</h3>
<p>グループ化変数は2つ以上指定することも可能です。たとえば、都府県 (<code>Pref</code>)と最寄りの駅の路線 (<code>Line</code>)でグループ化することも可能です。それでは<code>Pref</code>と<code>Line</code>でグループ化し、店舗数と口コミ数、評価の平均値を計算し、ソートの順番は店舗数、店舗数が同じなら評価の平均値が高い順にしましょう。今回も<code>summarise()</code>内に<code>.group = "drop"</code>を指定し、グループ化を解除します。今回はTop 20まで出してみましょう。</p>
<pre class="r numberLines"><code># ScoreNとScoreの平均値をPrefごとに求める
df %&gt;%
  filter(!is.na(Line)) %&gt;% # Lineが欠損していないケースのみ残す
  group_by(Pref, Line) %&gt;% # PrefとLineでグループ化
  summarise(N           = n(),
            ScoreN_Sum  = sum(ScoreN,  na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE),
            .groups     = &quot;drop&quot;) %&gt;%
  arrange(desc(N), desc(Score_Mean)) %&gt;%
  print(n = 20)</code></pre>
<pre><code>## # A tibble: 523 x 5
##    Pref     Line                        N ScoreN_Sum Score_Mean
##    &lt;chr&gt;    &lt;chr&gt;                   &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 埼玉県   東武東上線                122         27       3.68
##  2 東京都   ＪＲ                      104        231       3.56
##  3 神奈川県 小田急小田原線             96         31       3.59
##  4 埼玉県   東武伊勢崎線               96         18       3.51
##  5 神奈川県 横浜市営ブルーライン       82         77       3.66
##  6 千葉県   京成本線                   82         29       3.34
##  7 神奈川県 京急本線                   68         40       3.33
##  8 千葉県   東武野田線                 63          2       4.75
##  9 神奈川県 小田急江ノ島線             62          8       3.79
## 10 大阪府   阪急京都本線               53         32       3.67
## 11 大阪府   南海本線                   52         11       4.22
## 12 兵庫県   阪神本線                   52         23       3.80
## 13 埼玉県   JR高崎線                   51          5       4   
## 14 兵庫県   山陽電鉄本線               51         15       2.98
## 15 千葉県   JR総武本線（東京-銚子）    47          8       4   
## 16 埼玉県   西武新宿線                 45          8       4.17
## 17 埼玉県   秩父鉄道線                 43         10       3.82
## 18 大阪府   京阪本線                   43         10       3.69
## 19 千葉県   新京成電鉄                 43          6       3.6 
## 20 京都府   阪急京都本線               43         27       3.5 
## # … with 503 more rows</code></pre>
<p>ぐるなびに登録されているラーメン屋が最も多い路線は埼玉県内の東武東上線で122店舗があります。東武東上線は東京都と埼玉県をまたがる路線ですので、東武東上線だけならもっと多いかも知れませんね。</p>
<p>ここで一つ考えたいのは<code>summarise()</code>内の<code>.groups</code>引数です。前回はグループ化に使った変数ごとに1行しか残っていなかったのでグループ化を全て解除しました。しかし、今回は状況がやや異なります。グループ化変数に使った<code>Pref</code>を考えると、まだ<code>Pref == "東京都"</code>であるケースがいくつかあります。やろうとすればまだグループ化出来る状態です。これは<code>Line</code>についても同じです。<code>Line == "東武東上線"</code>の行はここには表示されていないものの、まだデータに残っています。もし、これ以上グループ化しないなら今のように<code>.groups = "drop"</code>が正しいですが、もしもう一回グループ化したい場合はどうすればよいでしょうか。方法は2つ考えられます。</p>
<ol style="list-style-type: decimal">
<li>もう一度パイプ演算子を使って<code>group_by()</code>関数を使う (以下の9行目)。
<ul>
<li>結果を見ると<code>## # Groups:   Pref, Line [523]</code>で、ちゃんとグループ化されていることが分かります。</li>
</ul></li>
</ol>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Line)) %&gt;% 
  group_by(Pref, Line) %&gt;% 
  summarise(N           = n(),
            ScoreN_Sum  = sum(ScoreN,  na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE),
            .groups     = &quot;drop&quot;) %&gt;%
  arrange(desc(N), desc(Score_Mean)) %&gt;%
  group_by(Pref, Line) %&gt;% # group_by()、もう一度
  print(n = 5)</code></pre>
<pre><code>## # A tibble: 523 x 5
## # Groups:   Pref, Line [523]
##   Pref     Line                     N ScoreN_Sum Score_Mean
##   &lt;chr&gt;    &lt;chr&gt;                &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 埼玉県   東武東上線             122         27       3.68
## 2 東京都   ＪＲ                   104        231       3.56
## 3 神奈川県 小田急小田原線          96         31       3.59
## 4 埼玉県   東武伊勢崎線            96         18       3.51
## 5 神奈川県 横浜市営ブルーライン    82         77       3.66
## # … with 518 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><code>.groups</code>引数を何とかする。</li>
</ol>
<p>推奨される方法は2番です。具体的には<code>.groups = "keep"</code>を指定するだけであり、こっちの方が無駄なコードを省けることができます。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Line)) %&gt;% 
  group_by(Pref, Line) %&gt;% 
  summarise(N           = n(),
            ScoreN_Sum  = sum(ScoreN,  na.rm = TRUE),
            Score_Mean  = mean(Score,  na.rm = TRUE),
            .groups     = &quot;keep&quot;) %&gt;%
  arrange(desc(N), desc(Score_Mean)) %&gt;%
  print(n = 5)</code></pre>
<pre><code>## # A tibble: 523 x 5
## # Groups:   Pref, Line [523]
##   Pref     Line                     N ScoreN_Sum Score_Mean
##   &lt;chr&gt;    &lt;chr&gt;                &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 埼玉県   東武東上線             122         27       3.68
## 2 東京都   ＪＲ                   104        231       3.56
## 3 神奈川県 小田急小田原線          96         31       3.59
## 4 埼玉県   東武伊勢崎線            96         18       3.51
## 5 神奈川県 横浜市営ブルーライン    82         77       3.66
## # … with 518 more rows</code></pre>
<p><code>.groups</code>引数は<code>"drop"</code>と<code>"keep"</code>以外にも<code>"drop_last"</code>があります。実は<code>summarise()</code>に<code>.groups</code>引数を指定したい場合のデフォルト値は<code>.groups == "drop_last"</code>または<code>"keep"</code>ですが、ここがややこしいです。主なケースにおいてデフォルト値は<code>"drop"</code>となりますとなります。<code>.groups == "drop_last"</code>これは最後のグループ化変数のみ解除する意味です。今回の例だと、2番目のグループ化変数である<code>Line</code>がグループ化変数から外され、<code>Pref</code>のみがグループ化変数として残る仕組みです。</p>
<p>それではデフォルト値が<code>"keep"</code>になるのはいつでしょうか。それは記述統計量の結果が長さ2以上のベクトルである場合です。平均値を求める<code>mean()</code>、標準偏差を求める<code>sd()</code>などは、結果として長さ1のベクトルを返します。しかし、長さ2以上ののベクトルを返す関数もあります。たとえば、分位数を求める<code>quantile()</code>関数があります。<code>quantile(ベクトル名, 0.25)</code>の場合、第一四分位点のみ返すため、結果は長さ1のベクトルです。しかし、<code>quantile(ベクトル名, c(0.25, 0.5, 0.75))</code>のように第一四分位点から第三四分位点を同時に計算し、長さ3のベクトルが返されるケースもありますし、第二引数を省略すると、最小値・第一四分位点・第二四分位点・第三四分位点・最大値、つまり、長さ5のベクトルが返される場合があります。</p>
<pre class="r numberLines"><code># 第一四分位点のみを求める (長さ1のベクトル)
quantile(df$Walk, 0.25, na.rm = TRUE)</code></pre>
<pre><code>## 25% 
##   2</code></pre>
<pre class="r numberLines"><code># 引数を省略する (長さ5のベクトル)
quantile(df$Walk, na.rm = TRUE)</code></pre>
<pre><code>##   0%  25%  50%  75% 100% 
##    1    2    5   12  116</code></pre>
<p><code>.groups</code>のデフォルト値が<code>"keep"</code>になるのは、このように長さ2以上のベクトルが返されるケースです。たとえば、都府県と最寄りの駅の路線でグループ化し、店舗までの徒歩距離の平均値を求めるとします。デフォルト値の変化を見るために、ここではあえて<code>.groups</code>引数を省略しました。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Walk)) %&gt;%
  group_by(Pref, Line) %&gt;%
  summarise(Mean = mean(Walk))</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;Pref&#39; (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 509 x 3
## # Groups:   Pref [9]
##    Pref   Line                         Mean
##    &lt;chr&gt;  &lt;chr&gt;                       &lt;dbl&gt;
##  1 京都府 ＪＲ                         4   
##  2 京都府 ＪＲ京都線                  10   
##  3 京都府 ＪＲ嵯峨野線                 5   
##  4 京都府 ＪＲ山陰本線                19   
##  5 京都府 ＪＲ山陰本線（京都-米子）    9.23
##  6 京都府 JR山陰本線（京都-米子）      8.67
##  7 京都府 JR小浜線                    16.5 
##  8 京都府 ＪＲ小浜線                   9   
##  9 京都府 ＪＲ東海道本線（米原-神戸） 11.2 
## 10 京都府 JR東海道本線（米原-神戸）   16.3 
## # … with 499 more rows</code></pre>
<p>最初は<code>Pref</code>と<code>Line</code>でグループ化しましたが、<code>summarise()</code>の後、<code>Line</code>がグループ化変数から外されました。つまり、引数が<code>"drop_last"</code>になっていることです。</p>
<p>それでは、平均値に加えて、第一四分位点と第三四分位点も計算し、<code>Quantile</code>という名で格納してみましょう。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Walk)) %&gt;%
  group_by(Pref, Line) %&gt;%
  summarise(Mean     = mean(Walk),
            Quantile = quantile(Walk, c(0.25, 0.75)))</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;Pref&#39;, &#39;Line&#39; (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 1,018 x 4
## # Groups:   Pref, Line [509]
##    Pref   Line                       Mean Quantile
##    &lt;chr&gt;  &lt;chr&gt;                     &lt;dbl&gt;    &lt;dbl&gt;
##  1 京都府 ＪＲ                       4        1.25
##  2 京都府 ＪＲ                       4        5   
##  3 京都府 ＪＲ京都線                10       10   
##  4 京都府 ＪＲ京都線                10       10   
##  5 京都府 ＪＲ嵯峨野線               5        4.5 
##  6 京都府 ＪＲ嵯峨野線               5        6   
##  7 京都府 ＪＲ山陰本線              19       19   
##  8 京都府 ＪＲ山陰本線              19       19   
##  9 京都府 ＪＲ山陰本線（京都-米子）  9.23     3   
## 10 京都府 ＪＲ山陰本線（京都-米子）  9.23    13   
## # … with 1,008 more rows</code></pre>
<p>同じ<code>Pref</code>、<code>Line</code>のケースが2つずつ出来ています。最初に来る数値は第一四分位点、次に来るのが第三四分位点です。そして最初のグループ化変数であった<code>Pref</code>と<code>Line</code>が、<code>summarise()</code>後もグループ化変数として残っていることが分かります。</p>
<p><code>.groups</code>引数は記述統計量だけを計算する意味ではあまり意識する必要がありません。しかし、得られた記述統計量から何らかの計算をしたり、さらにもう一回記述統計量を求めたりする際、予期せぬ結果が得られる可能性があるため注意する必要があります。出来る限り<code>.groups</code>引数は指定するようにしましょう。</p>
<hr />
</div>
</div>
<div id="変数の計算" class="section level2">
<h2>変数の計算</h2>
<div id="mutate関数の使い方" class="section level3">
<h3><code>mutate()</code>関数の使い方</h3>
<p>続いて、データフレーム (または、tibble)内の変数を用いて計算を行い、その結果を新しい列として格納する<code>mutate()</code>関数について紹介します。まず、<code>mutate()</code>関数の書き方からです。</p>
<pre class="r numberLines"><code># mutate()関数の使い方
データフレーム/tibble名 %&gt;%
  mutate(新しい変数名 = 処理内容)</code></pre>
<p>これは何らかの処理を行い、その結果を新しい変数としてデータフレーム (または、tibble)に追加することを意味します。新しく出来た変数は、基本的に最後の列になります。ここでは分単位である<code>Walk</code>を時間単位に変換した<code>Walk_Hour</code>変数を作成するとします。処理内容は<code>Walk / 60</code>です。最後に、都府県名、店舗名、徒歩距離 (分)、徒歩距離 (時間)のみを残し、遠い順にソートします。</p>
<pre class="r numberLines"><code>df %&gt;%
  filter(!is.na(Walk)) %&gt;%
  mutate(Walk_Hour = Walk / 60) %&gt;%
  select(Pref, Name, Walk, Walk_Hour) %&gt;%
  arrange(desc(Walk_Hour))</code></pre>
<pre><code>## # A tibble: 5,375 x 4
##    Pref     Name                               Walk Walk_Hour
##    &lt;chr&gt;    &lt;chr&gt;                             &lt;dbl&gt;     &lt;dbl&gt;
##  1 埼玉県   札幌ラーメン どさん子 小鹿野店      116     1.93 
##  2 神奈川県 札幌ラーメン どさん子 中津店         73     1.22 
##  3 千葉県   札幌ラーメン どさん子 佐原51号店     59     0.983
##  4 神奈川県 札幌ラーメン どさん子 山際店         50     0.833
##  5 千葉県   札幌ラーメン どさん子 関宿店         49     0.817
##  6 兵庫県   濃厚醤油 中華そば いせや 玉津店      43     0.717
##  7 大阪府   河童ラーメン本舗 岸和田店            38     0.633
##  8 埼玉県   ラーメン山岡家 上尾店                35     0.583
##  9 兵庫県   濃厚醤油 中華そば いせや 大蔵谷店    35     0.583
## 10 大阪府   河童ラーメン本舗 松原店              31     0.517
## # … with 5,365 more rows</code></pre>
<p><code>mutate()</code>は3行目に登場しますが、これは<code>Walk</code>を60に割った結果を<code>Walk_Hour</code>としてデータフレーム (または、tibble)の最後の列として格納することを意味します。もし、最後の列でなく、ある変数の前、または後にしたい場合は、<code>.before</code>または<code>.after</code>引数を追加します。これは<code>select()</code>関数の<code>.before</code>と<code>.after</code>と同じ使い方です。たとえば、新しく出来た<code>Walk_Hour</code>を<code>ID</code>と<code>Name</code>の間に入れたい場合は</p>
<pre class="r numberLines"><code># コードの3行名を修正 (.before使用)
mutate(Walk_Hour = Walk / 60,
       .before   = Name)

# コードの3行名を修正 (.after使用)
mutate(Walk_Hour = Walk / 60,
       .after    = ID)</code></pre>
<p>のようにコードを修正します。</p>
<p>むろん、変数間同士の計算も可能です。たとえば、以下のような<code>df2</code>があり、1店舗当たりの平均口コミ数を計算し、<code>ScoreN_Mean</code>という変数名で<code>ScoreN_Sum</code>の後に格納うするとします。この場合、<code>ScoreN_Sum</code>変数を<code>N</code>で割るだけです。</p>
<pre class="r numberLines"><code>df2 &lt;- df %&gt;%
  group_by(Pref) %&gt;%
  summarise(Budget_Mean = mean(Budget, na.rm = TRUE),
            ScoreN_Sum  = sum(ScoreN, na.rm = TRUE),
            Score_Mean  = mean(Score, na.rm = TRUE),
            N           = n(),
            .groups     = &quot;drop&quot;)</code></pre>
<pre class="r numberLines"><code>df2 %&gt;%
  mutate(ScoreN_Mean = ScoreN_Sum / N,
         .after      = ScoreN_Sum)</code></pre>
<pre><code>## # A tibble: 9 x 6
##   Pref     Budget_Mean ScoreN_Sum ScoreN_Mean Score_Mean     N
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府         1399.        216       0.522       3.68   414
## 2 埼玉県         1147.        278       0.278       3.64  1000
## 3 神奈川県       1239.        587       0.587       3.53  1000
## 4 千葉県         1124.        259       0.259       3.72  1000
## 5 大阪府         1203.        516       0.516       3.77  1000
## 6 東京都         1283.       1165       1.16        3.67  1000
## 7 奈良県         1169.         45       0.306       3.85   147
## 8 兵庫県         1197.        230       0.389       3.54   591
## 9 和歌山県       1252          83       0.593       3.97   140</code></pre>
<p>このように、データ内の変数を用いた計算結果を新しい列として追加する場合は、<code>mutate()</code>が便利です。これを<code>mutate()</code>を使わずに処理する場合、以下のようなコードになりますが、可読性が相対的に低いことが分かります。</p>
<pre class="r numberLines"><code>df2$ScoreN_Mean &lt;- df2$ScoreN_Sum / df2$N
df2 &lt;- df2[, c(&quot;Pref&quot;, &quot;Budget_Mean&quot;, &quot;Walk_Mean&quot;, 
               &quot;ScoreN_Sum&quot;, &quot;ScoreN_Mean&quot;, &quot;Score_Mean&quot;, &quot;N&quot;)]</code></pre>
<p>むろんですが、計算には<code>+</code>や<code>/</code>のような演算子だけでなく、関数を使うことも可能です。たとえば、<code>Budget</code>が1000円未満なら<code>"Cheap"</code>、1000円以上なら<code>"Expensive"</code>と示す変数<code>Budget2</code>を作成する場合は<code>ifelse()</code>関数が使えます。</p>
<pre class="r numberLines"><code>df %&gt;% 
  mutate(Budget2 = ifelse(Budget &lt; 1000, &quot;Cheap&quot;, &quot;Expensive&quot;)) %&gt;%
  filter(!is.na(Budget2)) %&gt;% # Budget2が欠損した店舗を除外
  group_by(Pref, Budget2) %&gt;% # PrefとBudget2でグループ化
  summarise(N = n(),          # 店舗数を表示
            .groups = &quot;drop&quot;)</code></pre>
<pre><code>## # A tibble: 18 x 3
##    Pref     Budget2       N
##    &lt;chr&gt;    &lt;chr&gt;     &lt;int&gt;
##  1 京都府   Cheap        22
##  2 京都府   Expensive    28
##  3 埼玉県   Cheap        37
##  4 埼玉県   Expensive    45
##  5 神奈川県 Cheap        66
##  6 神奈川県 Expensive    54
##  7 千葉県   Cheap        64
##  8 千葉県   Expensive    72
##  9 大阪府   Cheap       104
## 10 大阪府   Expensive   115
## 11 東京都   Cheap       206
## 12 東京都   Expensive   236
## 13 奈良県   Cheap        11
## 14 奈良県   Expensive    10
## 15 兵庫県   Cheap        39
## 16 兵庫県   Expensive    27
## 17 和歌山県 Cheap        10
## 18 和歌山県 Expensive     5</code></pre>
<p>これは各都府県ごとの予算1000円未満の店と以上の店の店舗数をまとめた表となります。もし、500円未満なら<code>"Cheap"</code>、500円以上~1000円未満なら<code>"Reasonable"</code>、1000円以上なら<code>"Expensive"</code>になる<code>Budget3</code>変数を作るにはどうすればよいでしょうか。これは<code>ifelse()</code>を重ねることも出来ますが、ここでは<code>case_when()</code>関数が便利です。まずは、<code>ifelse()</code>を使ったコードは以下の通りです。</p>
<pre class="r numberLines"><code># ifelse()を使う場合
df %&gt;% 
  mutate(Budget3 = ifelse(Budget &lt; 500, &quot;Cheap&quot;, 
                          ifelse(Budget &gt;= 500 &amp; Budget &lt; 1000, &quot;Reasonable&quot;,
                                 &quot;Expensive&quot;))) %&gt;%
  filter(!is.na(Budget3)) %&gt;%
  group_by(Pref, Budget3) %&gt;%
  summarise(N = n(),         
            .groups = &quot;drop&quot;)</code></pre>
<p><code>case_when()</code>を使うと以下のような書き方になります。</p>
<pre class="r numberLines"><code># ifelse()を使う場合
df %&gt;% 
  mutate(Budget3 = case_when(Budget &lt; 500                  ~ &quot;Cheap&quot;,
                             Budget &gt;= 500 &amp; Budget &lt; 1000 ~ &quot;Reasonable&quot;,
                             Budget &gt;= 1000                ~ &quot;Expensive&quot;),
         # 新しく出来た変数をfactor型にその場で変換することも可能
         Budget3 = factor(Budget3, 
                          levels = c(&quot;Cheap&quot;, &quot;Reasonable&quot;, &quot;Expensive&quot;))) %&gt;%
  filter(!is.na(Budget3)) %&gt;%
  group_by(Pref, Budget3) %&gt;%
  summarise(N = n(),         
            .groups = &quot;drop&quot;)</code></pre>
<p>書く手間の観点では<code>case_when()</code>は<code>ifelse()</code>と大きく違いはないかも知れませんが、コードが非常に読みやすくなっています。<code>case_when()</code>関数の書き方は以下の通りです。</p>
<pre class="r numberLines"><code># case_when()の使い方
データフレーム/tibble名 %&gt;%
  mutate(新変数名 = case_when(条件1 ~ 条件1を満たす場合の結果値, 
                             条件2 ~ 条件2を満たす場合の結果値, 
                             条件3 ~ 条件3を満たす場合の結果値, 
                             ...))</code></pre>
<p>似たような機能をする関数として<code>recode()</code>関数があります。これは変数の値を単純に置換したい場合に便利な関数です。たとえば、都府県名をローマ字に変換するケースを考えてみましょう。</p>
<pre class="r numberLines"><code># recode()を使う場合
df2 %&gt;% 
  mutate(Pref2 = recode(Pref,
                        &quot;東京都&quot;   = &quot;Tokyo&quot;,
                        &quot;神奈川県&quot; = &quot;Kanagawa&quot;,
                        &quot;千葉県&quot;   = &quot;Chiba&quot;,
                        &quot;埼玉県&quot;   = &quot;Saitama&quot;,
                        &quot;大阪府&quot;   = &quot;Osaka&quot;,
                        &quot;京都府&quot;   = &quot;Kyoto&quot;,
                        &quot;兵庫県&quot;   = &quot;Hyogo&quot;,
                        &quot;奈良県&quot;   = &quot;Nara&quot;,
                        &quot;和歌山県&quot; = &quot;Wakayama&quot;,
                        .default  = &quot;NA&quot;))</code></pre>
<pre><code>## # A tibble: 9 x 6
##   Pref     Budget_Mean ScoreN_Sum Score_Mean     N Pref2   
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;   
## 1 京都府         1399.        216       3.68   414 Kyoto   
## 2 埼玉県         1147.        278       3.64  1000 Saitama 
## 3 神奈川県       1239.        587       3.53  1000 Kanagawa
## 4 千葉県         1124.        259       3.72  1000 Chiba   
## 5 大阪府         1203.        516       3.77  1000 Osaka   
## 6 東京都         1283.       1165       3.67  1000 Tokyo   
## 7 奈良県         1169.         45       3.85   147 Nara    
## 8 兵庫県         1197.        230       3.54   591 Hyogo   
## 9 和歌山県       1252          83       3.97   140 Wakayama</code></pre>
<p>使い方は非常に直感的です。</p>
<pre class="r numberLines"><code># recode()の使い方
データフレーム/tibble名 %&gt;%
  mutate(新変数名 = recode(元の変数名,
                            元の値1 =  新しい値1, 
                            元の値2 =  新しい値2, 
                            元の値3 =  新しい値3, 
                            ...,
                            .default = 該当しない場合の値))</code></pre>
<p>最後の<code>.default</code>引数は、もし該当する値がない場合に返す値を意味し、長さ1のベクトルを指定します。もし、指定しない場合は<code>NA</code>が表示されます。また、ここには紹介しておりませんでしたが、<code>.missing</code>引数もあり、これは欠損値の場合に返す値を意味します。</p>
<p>もう一つ注意すべきところは、今回はcharacter型変数をcharacter型へ変換したため、「<code>"東京都" = "Tokyo"</code>」のような書き方をしました。しかし、numeric型からcharacter型に変換する場合は数字の部分を<code>`</code>で囲む必要があります。たとえば、「<code>`1` = "Tokyo"</code>」といった形式です。ただし、character型からnumeric型への場合は「<code>"東京都" = 1</code>」で構いません。</p>
<p><code>recode()</code>は値をまとめる際にも便利です。たとえば、<code>EastJapan</code>という変数を作成し、関東なら<code>1</code>を、それ以外なら<code>0</code>を付けるとします。そして、これは<code>Pref</code>変数の後に位置づけます。</p>
<pre class="r numberLines"><code># 都府県を関東か否かでまとめる
df2 %&gt;% 
  mutate(EastJapan = recode(Pref,
                            &quot;東京都&quot;   = 1,
                            &quot;神奈川県&quot; = 1,
                            &quot;千葉県&quot;   = 1,
                            &quot;埼玉県&quot;   = 1,
                            &quot;大阪府&quot;   = 0,
                            &quot;京都府&quot;   = 0,
                            &quot;兵庫県&quot;   = 0,
                            &quot;奈良県&quot;   = 0,
                            &quot;和歌山県&quot; = 0,
                            .default  = 0),
         .after = Pref)</code></pre>
<pre><code>## # A tibble: 9 x 6
##   Pref     EastJapan Budget_Mean ScoreN_Sum Score_Mean     N
##   &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府           0       1399.        216       3.68   414
## 2 埼玉県           1       1147.        278       3.64  1000
## 3 神奈川県         1       1239.        587       3.53  1000
## 4 千葉県           1       1124.        259       3.72  1000
## 5 大阪府           0       1203.        516       3.77  1000
## 6 東京都           1       1283.       1165       3.67  1000
## 7 奈良県           0       1169.         45       3.85   147
## 8 兵庫県           0       1197.        230       3.54   591
## 9 和歌山県         0       1252          83       3.97   140</code></pre>
<p>ただし、関東以外は全て0になるため、以下のように省略することも可能です。</p>
<pre class="r numberLines"><code># .default引数を指定する場合
df3 &lt;- df2 %&gt;% 
  mutate(EastJapan = recode(Pref,
                            &quot;東京都&quot;   = 1,
                            &quot;神奈川県&quot; = 1,
                            &quot;千葉県&quot;   = 1,
                            &quot;埼玉県&quot;   = 1,
                            .default  = 0),
         .after = Pref)

df3</code></pre>
<pre><code>## # A tibble: 9 x 6
##   Pref     EastJapan Budget_Mean ScoreN_Sum Score_Mean     N
##   &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府           0       1399.        216       3.68   414
## 2 埼玉県           1       1147.        278       3.64  1000
## 3 神奈川県         1       1239.        587       3.53  1000
## 4 千葉県           1       1124.        259       3.72  1000
## 5 大阪府           0       1203.        516       3.77  1000
## 6 東京都           1       1283.       1165       3.67  1000
## 7 奈良県           0       1169.         45       3.85   147
## 8 兵庫県           0       1197.        230       3.54   591
## 9 和歌山県         0       1252          83       3.97   140</code></pre>
<p>新しく出来た<code>EastJapan</code>のデータ型はなんでしょうか。</p>
<pre class="r numberLines"><code>class(df3$EastJapan)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p><code>EastJapan</code>はnumeric型ですね。もし、これをfactor型にしたい場合はどうすればよいでしょうか。それは<code>mutate()</code>内で<code>EastJapan</code>を生成した後に<code>factor()</code>関数を使うだけです。</p>
<pre class="r numberLines"><code># EastJapan変数をfactor型にする
df3 &lt;- df2 %&gt;% 
  mutate(EastJapan = recode(Pref,
                            &quot;東京都&quot;   = 1,
                            &quot;神奈川県&quot; = 1,
                            &quot;千葉県&quot;   = 1,
                            &quot;埼玉県&quot;   = 1,
                            .default  = 0),
         EastJapan = factor(EastJapan, levels = c(0, 1)),
         .after = Pref)

df3$EastJapan</code></pre>
<pre><code>## [1] 0 1 1 1 0 1 0 0 0
## Levels: 0 1</code></pre>
<p><code>EastJapan</code>がfactor型になりました。実は、<code>recode</code>は再コーディングと同時にfactor化をしてくれる機能があります。ただし、<code>recode()</code>関数でなく、<code>recode_factor()</code>関数を使います。</p>
<pre class="r numberLines"><code># recode_factor()を使う方法
df3 &lt;- df2 %&gt;% 
  mutate(EastJapan = recode_factor(Pref,
                                   &quot;東京都&quot;   = 1,
                                   &quot;神奈川県&quot; = 1,
                                   &quot;千葉県&quot;   = 1,
                                   &quot;埼玉県&quot;   = 1,
                                   .default  = 0),
         .after = Pref)

df3$EastJapan</code></pre>
<pre><code>## [1] 0 1 1 1 0 1 0 0 0
## Levels: 1 0</code></pre>
<p>ただし、levelの順番は<code>recode_factor()</code>内で定義された順番になることに注意してください。</p>
</div>
<div id="factor型の処理に便利な関数" class="section level3">
<h3>factor型の処理に便利な関数</h3>
<hr />
</div>
</div>
<div id="行単位の操作" class="section level2">
<h2>行単位の操作</h2>
<p>ここでは行単位の操作について考えたいと思います。<code>select()</code>の説明で使った<code>myDF1</code>を見てみましょう。</p>
<pre class="r numberLines"><code>myDF1</code></pre>
<pre><code>## # A tibble: 5 x 10
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9
## 2     2     4     5     2     5     3     9     0     5     1
## 3     3     6     1     1     6     2     5     3     9     3
## 4     4     2     1     6     0     3     0     0     1     3
## 5     5     7     0     9     2     1     1     2     3     8</code></pre>
<p>ここで<code>X1</code>と<code>X2</code>と<code>X3</code>の平均値を計算し、<code>X_Mean</code>という名の変数にする場合、以下のような書き方が普通でしょう。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  mutate(X_Mean = mean(c(X1, X2, X3)))</code></pre>
<pre><code>## # A tibble: 5 x 11
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9   3.13
## 2     2     4     5     2     5     3     9     0     5     1   3.13
## 3     3     6     1     1     6     2     5     3     9     3   3.13
## 4     4     2     1     6     0     3     0     0     1     3   3.13
## 5     5     7     0     9     2     1     1     2     3     8   3.13</code></pre>
<p>あら、なんかおかしくありませんか。1行目の場合、<code>X1</code>と<code>X2</code>、<code>X3</code>それぞれ2、5、3であり、平均値は3.333であるはずなのに3.133になりました。これは2行目以降も同じです。なぜでしょうか。</p>
<p>実は<code>dplyr</code>は行単位の計算が苦手です。実際、データフレーム (または、tibble)というのは既に説明したとおり、縦ベクトルを横に並べたものです。列をまたがる場合、データ型が異なる場合も多いため、そもそも使う場面も多くありません。したがって、以下のような書き方が必要でした。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  mutate(X_Mean = (X1 + X2 + X3) / 3)</code></pre>
<pre><code>## # A tibble: 5 x 11
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9  3.33 
## 2     2     4     5     2     5     3     9     0     5     1  3    
## 3     3     6     1     1     6     2     5     3     9     3  5    
## 4     4     2     1     6     0     3     0     0     1     3  0.667
## 5     5     7     0     9     2     1     1     2     3     8  3.67</code></pre>
<p>先ほどの<code>mean(c(X1, X2, X3))</code>は(<code>X1</code>列と<code>X2</code>列、<code>X3</code>列)の平均値です。<code>X1</code>は長さ1のベクトルではなく、その列全体を指すものです。つまり、<code>mean(c(X1, X2, X3))</code>は<code>mean(c(myD1F$X1, myDF1$X2, myDF1$X3))</code>と同じことになります。だから全て3.133という結果が得られました。ただし、後者はベクトル同士の加減乗除になるため問題ありません。実際<code>c(1, 2, 3) + c(3, 5, 0)</code>は同じ位置の要素同士の計算になります。</p>
<p>ここで<code>mean()</code>関数を使う場合には全ての演算を、一行一行に分けて行う必要があります。ある一行のみに限定する場合、<code>mean(c(X1, X2, X3))</code>の<code>X1</code>などは長さ1のベクトルになるため、<code>(X1 + X2 + X3) / 3</code>と同じことになります。この「一行単位で処理を行う」ことを指定する関数が<code>rowwise()</code>関数です。これは行単位の作業を行う前に指定するだけです。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  rowwise() %&gt;%
  mutate(X_Mean = mean(c(X1, X2, X3)))</code></pre>
<pre><code>## # A tibble: 5 x 11
## # Rowwise: 
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9  3.33 
## 2     2     4     5     2     5     3     9     0     5     1  3    
## 3     3     6     1     1     6     2     5     3     9     3  5    
## 4     4     2     1     6     0     3     0     0     1     3  0.667
## 5     5     7     0     9     2     1     1     2     3     8  3.67</code></pre>
<p>これで問題なく行単位の処理ができるようになりました。今回は変数が3つのみだったので、これで問題ありませんが、変数が多くなると<code>:</code>や<code>starts_with()</code>、<code>num_range()</code>などを使って変数を選択したくなります。この場合は計算する関数内に<code>c_across()</code>を入れます。ここでは<code>X1</code>列から<code>X3D</code>列までの平均値を求めてみましょう。</p>
<pre class="r numberLines"><code>myDF1 %&gt;%
  rowwise() %&gt;%
  mutate(X_Mean = mean(X1:X3D))</code></pre>
<pre><code>## # A tibble: 5 x 11
## # Rowwise: 
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9    5.5
## 2     2     4     5     2     5     3     9     0     5     1    2.5
## 3     3     6     1     1     6     2     5     3     9     3    4.5
## 4     4     2     1     6     0     3     0     0     1     3    2.5
## 5     5     7     0     9     2     1     1     2     3     8    7.5</code></pre>
<p>実は<code>rowwise()</code>関数、2020年6月に公開されたdplyr 1.0.0で注目された関数ですが、昔のdplyrにも<code>rowwise()</code>関数はありました。ただし、<code>purrr</code>パッケージや<code>tidyr</code>パッケージの<code>nest()</code>関数などにより使い道がなくなりましたが、なぜか華麗に復活しました。データ分析に使うデータは基本単位は列であるため、実際に<code>rowwise()</code>が使われる場面は今の段階では多くないでしょう。また、簡単な作業なら<code>X1 + X2</code>のような演算でも対応できます。それでも、覚えておけば便利な関数であることには間違いありません。</p>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>実は<code>select(starts_with("X"), -ends_with("D"), ID)</code>のように順番を変えると<code>ID</code>は最後の列になりますが、とりあえず残ります。なぜなら、<code>select()</code>関数は左側から右側の方へコードを実行するからです。<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>サービスによってはこの機能が有料になっていたりもしますね。<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>たとえば、データ内に「ラーメンショップ」という店舗は3店舗あり、この場合、長さ3のベクトルが返されます。<a href="#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
</div>

</main>

        <footer>
            <p class="copyright text-muted" align = "center">© All rights reserved. Powered by <a href="https://gohugo.io">Hugo</a> and <a href="https://github.com/calintat/minimal">Minimal</a>. Customized by <a href="https://www.jaysong.net">Jaehyun Song</a></p>
        </footer>

        

        
    </body>

</html>

